import {describe,expect,it,vi} from 'vitest';
import {freezePairedDesign} from '../../supabase/functions/generate-concept/paired-design';
import {acceptOfflinePair,runOfflinePair,type OfflineRenderRuntime,type ReviewProgress} from '../../supabase/functions/generate-concept/paired-runner';
import {makePairedFixture} from '../test/paired-design-fixture';
function mockRuntime():OfflineRenderRuntime {
  return {mode:'offline-mock',render:vi.fn(async(artifact,source)=>({role:artifact.role,id:`mock-${artifact.role}`,identityId:artifact.identityId,manifestId:artifact.manifestId,specDigest:artifact.specDigest,sourceCollectibleId:source?.id||null,status:'offline-mock'})),persist:vi.fn(async()=>{})};
}
describe('offline paired reliability',()=>{
  it('persists hero first and conditions card on that exact identity',async()=>{const manifest=await freezePairedDesign(makePairedFixture());const runtime=mockRuntime();const result=await runOfflinePair(manifest,runtime,new AbortController().signal);expect(runtime.persist).toHaveBeenCalledTimes(2);expect(result.assets['story-card']?.sourceCollectibleId).toBe('mock-collectible');expect((await acceptOfflinePair(manifest,result)).assets.collectible?.id).toBe('mock-collectible');});
  it('resumes only missing card after terminal failure without automatic retries',async()=>{const manifest=await freezePairedDesign(makePairedFixture());const runtime=mockRuntime();let saved:ReviewProgress|undefined;runtime.persist=async(p)=>{saved=p;};const render=runtime.render;runtime.render=vi.fn(async(...args)=>{if(args[0].role==='story-card')throw new Error('terminal denial fixture');return render(...args);});await expect(runOfflinePair(manifest,runtime,new AbortController().signal)).rejects.toThrow('terminal denial');expect(runtime.render).toHaveBeenCalledTimes(2);if(!saved)throw new Error('Hero must be persisted');const recovery=mockRuntime();const result=await runOfflinePair(manifest,recovery,new AbortController().signal,saved);expect(recovery.render).toHaveBeenCalledTimes(1);expect(result.assets.collectible?.id).toBe('mock-collectible');});
  it('rejects changed specs and forged saved references before rendering',async()=>{const manifest=await freezePairedDesign(makePairedFixture());const saved=await runOfflinePair(manifest,mockRuntime(),new AbortController().signal);const other=await freezePairedDesign(makePairedFixture(1));const recovery=mockRuntime();await expect(runOfflinePair(other,recovery,new AbortController().signal,saved)).rejects.toThrow('different locked pair');const card=saved.assets['story-card'];if(!card)throw new Error('Missing card');card.sourceCollectibleId='forged';await expect(runOfflinePair(manifest,recovery,new AbortController().signal,saved)).rejects.toThrow('lineage');expect(recovery.render).not.toHaveBeenCalled();});
  it('ignores stopped late results without persistence or starting another stage',async()=>{const manifest=await freezePairedDesign(makePairedFixture());const runtime=mockRuntime();const abort=new AbortController();const render=runtime.render;runtime.render=vi.fn(async(...args)=>{const result=await render(...args);abort.abort();return result;});await expect(runOfflinePair(manifest,runtime,abort.signal)).rejects.toThrow();expect(runtime.render).toHaveBeenCalledTimes(1);expect(runtime.persist).not.toHaveBeenCalled();});
  it('never promotes an incomplete revision or mutates accepted identity',async()=>{const manifest=await freezePairedDesign(makePairedFixture());const old=await acceptOfflinePair(manifest,await runOfflinePair(manifest,mockRuntime(),new AbortController().signal));await expect(acceptOfflinePair(manifest,{...old,assets:{collectible:old.assets.collectible}})).rejects.toThrow('Finish both');expect(Object.isFrozen(old.assets)).toBe(true);expect(old.assets['story-card']?.id).toBe('mock-story-card');});
});