import { PAIRED_CONTRACT_VERSION, hasPairedCapabilities, isPairedConcept, verifyFrozenDesign, type FrozenPairedDesign, type PairedConcept, type PairedRole, type StoryLens } from '../../supabase/functions/generate-concept/paired-design';
export type PairedPlanRequest={brand:string;website:string;lens:StoryLens;exactText:string;context:{business:string}};
const record=(v:unknown):v is Record<string,unknown>=>Boolean(v&&typeof v==='object'&&!Array.isArray(v));
function target(){const url=import.meta.env.VITE_SUPABASE_URL;const key=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;if(!url||!key)throw new Error('The linked concept studio is not configured.');return{url:`${url}/functions/v1/generate-concept`,key};}
async function post(body:unknown,signal:AbortSignal){const{url,key}=target();const response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json',apikey:key},body:JSON.stringify(body),signal});const data=await response.json().catch(()=>null);if(!response.ok)throw new Error(record(data)&&typeof data.error==='string'?data.error:'The linked concept could not be completed.');return data;}
export async function supportsPairedGeneration(signal:AbortSignal){try{const{url,key}=target();const response=await fetch(url,{headers:{apikey:key},signal});return response.ok&&hasPairedCapabilities(await response.json());}catch{return false;}}
export async function planPairedDesign(input:PairedPlanRequest,signal:AbortSignal):Promise<{manifest:FrozenPairedDesign;evidence:{url:string;title:string;excerpt:string}}>{const data=await post({contractVersion:PAIRED_CONTRACT_VERSION,action:'plan',...input},signal);if(!record(data)||!record(data.manifest)||!await verifyFrozenDesign(data.manifest as FrozenPairedDesign)||!record(data.evidence)||typeof data.evidence.url!=='string'||typeof data.evidence.title!=='string'||typeof data.evidence.excerpt!=='string')throw new Error(record(data)&&typeof data.message==='string'?data.message:'The evidence or design plan did not pass validation.');return data as {manifest:FrozenPairedDesign;evidence:{url:string;title:string;excerpt:string}};}
export async function renderPairedAsset(manifest:FrozenPairedDesign,role:PairedRole,sourceCollectibleId:string|undefined,signal:AbortSignal):Promise<PairedConcept>{const data=await post({contractVersion:PAIRED_CONTRACT_VERSION,action:'render',manifest,role,...(sourceCollectibleId?{sourceCollectibleId}:{})},signal);if(!record(data)||!isPairedConcept(data.concept)||data.concept.role!==role||data.concept.manifest.manifestId!==manifest.manifestId)throw new Error('The returned artifact does not match the locked design.');return data.concept;}
export async function restorePairedAsset(id:string,signal:AbortSignal):Promise<PairedConcept>{const data=await post({id},signal);if(!record(data)||!isPairedConcept(data.concept)||data.concept.id!==id)throw new Error('The saved linked artifact could not be restored.');return data.concept;}
