import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { PROPOSAL_CAPABILITIES, type ProposalConcept, type ProposalRequest } from '../../supabase/functions/generate-concept/proposal';
import { planProposalRevision, requestProposalAsset, restoreProposalAsset, supportsProposalGeneration } from './proposal-api';
const id='00000000-0000-4000-8000-000000000001';const world:ProposalRequest={contractVersion:'offkin-proposal-v10',stage:'world',brand:'no-website',context:{business:'Paper gifts',exactWording:'  字\nCafé 🪁 '}};
function concept(overrides:Partial<ProposalConcept>={}):ProposalConcept{return {...world,id,stageVersion:'proposal-assets-v1',brand:'Paper',title:'Paper world',story:'A rich paper city.',design:'Many connected scenes',interaction:'Explore',worldElements:[{id:'house',label:'Paper house',description:'A proposed story home',kind:'proposal'}],sourceImageIds:[],image:'https://images.example/world.png',sourceUrl:'',sourceTitle:'',...overrides};}
const reply=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status});
const readiness=()=>reply({ready:true,capabilities:PROPOSAL_CAPABILITIES});
beforeEach(()=>{vi.stubEnv('VITE_SUPABASE_URL','https://test.invalid');vi.stubEnv('VITE_SUPABASE_PUBLISHABLE_KEY','public-key');});
afterEach(()=>{vi.unstubAllEnvs();vi.unstubAllGlobals();vi.restoreAllMocks();});
describe('Proposal API fail-closed negotiation',()=>{
 it('reads readiness without transmitting the direction',async()=>{const fetch=vi.fn(async(_url:string,_init:RequestInit)=>readiness());vi.stubGlobal('fetch',fetch);expect(await supportsProposalGeneration(new AbortController().signal)).toBe(true);expect(fetch.mock.calls[0][1]).not.toHaveProperty('body');});
 it('never downgrades v10 to the v9 backend',async()=>{const fetch=vi.fn(async()=>reply({ready:true,capabilities:{canvas:true,canvas_contract_version:'offkin-canvas-v9'}}));vi.stubGlobal('fetch',fetch);await expect(requestProposalAsset(world,new AbortController().signal)).rejects.toThrow(/not available/);expect(fetch).toHaveBeenCalledOnce();});
 it('rechecks capabilities immediately before generation and preserves exact context',async()=>{const fetch=vi.fn(async(_url,init)=>init.method==='POST'?reply({concept:concept()}):readiness());vi.stubGlobal('fetch',fetch);const c=await requestProposalAsset(world,new AbortController().signal);expect(c.context.exactWording).toBe(world.context.exactWording);expect(JSON.parse(fetch.mock.calls[1][1].body)).toEqual(world);});
 it('rejects a mismatched source, stage or returned context',async()=>{vi.stubGlobal('fetch',vi.fn(async(_url,init)=>init.method==='POST'?reply({concept:concept({context:{business:'Another customer'}})}):readiness()));await expect(requestProposalAsset(world,new AbortController().signal)).rejects.toThrow(/does not match/);});
 it('restores saved images without readiness or generation',async()=>{const fetch=vi.fn(async(_url:string,_init:RequestInit)=>reply({concept:concept()}));vi.stubGlobal('fetch',fetch);await restoreProposalAsset(id,new AbortController().signal);expect(fetch).toHaveBeenCalledOnce();expect(JSON.parse(String(fetch.mock.calls[0][1].body))).toEqual({id});});
 it('rejects wrong restored UUID and invalid images',async()=>{vi.stubGlobal('fetch',vi.fn(async()=>reply({concept:concept({id:'00000000-0000-4000-8000-000000000002'})})));await expect(restoreProposalAsset(id,new AbortController().signal)).rejects.toThrow(/could not be opened/);});
 it('keeps cancellation effective before and after a provider response',async()=>{const abort=new AbortController();abort.abort();const fetch=vi.fn();vi.stubGlobal('fetch',fetch);await expect(requestProposalAsset(world,abort.signal)).rejects.toMatchObject({name:'AbortError'});expect(fetch).not.toHaveBeenCalled();});
 it('rejects revision output with invalid context keys',async()=>{vi.stubGlobal('fetch',vi.fn(async(_url,init)=>init.method==='POST'?reply({plan:{scope:'packaging',context:{business:'X',newCredential:'no'},summary:'Blue box'}}):readiness()));await expect(planProposalRevision({contractVersion:'offkin-proposal-v10',action:'plan-revision',instruction:'Blue package',brand:'no-website',context:world.context,sourceWorldId:id,sourcePhysicalId:'00000000-0000-4000-8000-000000000002'},new AbortController().signal)).rejects.toThrow();});
});
