import { lazy, Suspense, useEffect, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { ArrowRight, ArrowUpRight, BadgeCheck, BookOpen, Box, Flag, Gem, Mountain, Sparkles, Star, Trophy } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { supabase } from '@/integrations/supabase/client';
import { studioBrand, displayStudioName } from '@/lib/studio-brand';
import type { AchievementDraft } from '@/lib/achievement-draft';
import hero from '@/assets/achievements/offkin-adventurer.jpg';
import runner from '@/assets/achievements/offkin-runner.jpg';
import store from '@/assets/achievements/offkin-first-store.jpg';
import './achievement-home.css';
const AchievementWizard = lazy(() => import('@/components/AchievementWizard'));
const examples = [
  { title: 'The finish-line feeling.', category: 'Personal · Marathon milestone', image: runner, description: 'For the moment you went further than you thought you could.', milestone: 'Finished my first marathon', type: 'personal' as const },
  { title: 'Your next chapter.', category: 'Personal · Career, graduation & hobbies', image: hero, description: 'A new beginning. A hard-earned skill. A little proof of how far you’ve come.', milestone: 'A career milestone', type: 'personal' as const },
  { title: 'Small shop. Big moment.', category: 'Business · First-store milestone', image: store, description: 'Turn a meaningful business chapter into an object with a story.', milestone: 'Opened our first store', type: 'business' as const },
];
export default function AchievementHome() {
  const [params, setParams] = useSearchParams();
  const mode = params.get('journey') === 'quest' ? 'quest' : params.get('journey') === 'achievement' ? 'achievement' : null;
  const initialType = params.get('type') === 'business' ? 'business' : 'personal';
  const [settings, setSettings] = useState({ title: studioBrand.name, logo: '', link: '/' });
  useEffect(() => {
    let active = true;
    Promise.resolve(supabase.from('site_settings').select('key,value')).then(({ data }) => {
      if (!active || !data) return;
      const next = { title: studioBrand.name, logo: '', link: '/' };
      for (const setting of data) {
        if (setting.key === 'site_title' && setting.value && !['dioramini','briq2.0','briq','form.','brandkin','stive','the absurd marshmallow test'].includes(setting.value.trim().toLowerCase())) next.title = setting.value;
        if (setting.key === 'logo_url' && /^https?:\/\//i.test(setting.value || '')) next.logo = setting.value;
        if (setting.key === 'logo_link' && setting.value && setting.value !== 'https://example.com' && (/^https?:\/\//i.test(setting.value) || setting.value.startsWith('/') && !setting.value.startsWith('//'))) next.link = setting.value;
      }
      setSettings(next);
    }).catch(() => {});
    return () => { active = false; };
  }, []);
  useEffect(() => { document.title = `${displayStudioName(settings.title)} — ${studioBrand.pageTitleSuffix}`; }, [settings.title]);
  function open(mode: AchievementDraft['mode'], type: AchievementDraft['type'] = 'personal') { setParams({ journey: mode, ...(type === 'business' ? { type } : {}) }); }
  return <div className="ah-home ah-theme"><a className="ah-skip" href="#achievement-main">Skip to content</a>
    <header className="ah-header ah-wrap"><a className="ah-logo" href={settings.link} aria-label={`${settings.title} home`}>{settings.logo ? <img src={settings.logo} alt={settings.title} /> : <span>{settings.title}</span>}<small>异趣伙伴</small></a><nav className="ah-nav" aria-label="Main navigation"><a href="#milestone-examples">The collectibles</a><a href="#how-it-works">How it works</a><a href="#business-milestones">For business</a><Button className="ah-primary" onClick={() => open('achievement')}>Create yours <ArrowUpRight /></Button></nav></header>
    <main id="achievement-main"><section className="ah-hero" aria-labelledby="achievement-headline"><img src={hero} alt="Original adventurer collectible concept with a matching illustrated mountain story card" width={1536} height={1024} fetchPriority="high" /><div className="ah-wrap"><div className="ah-hero-content"><p className="ah-eyebrow"><Sparkles size={15} /> Real milestones. A little more magic.</p><h1 id="achievement-headline">Your life is full of achievements.<br /><em>Make them collectible.</em></h1><p>Celebrate a real milestone with your own collectible figure and illustrated story card.</p><div className="ah-hero-actions"><Button className="ah-primary" onClick={() => open('achievement')}>Create My Collectible <ArrowRight /></Button><Button variant="ghost" className="ah-text-action" onClick={() => open('quest')}><Flag /> Start a Quest</Button></div><p className="ah-hero-note">Start with a written preview. No sign-up. No payment.</p><div className="ah-types"><span>A story for</span><Button variant="link" onClick={() => open('achievement', 'personal')}>You</Button><span>/</span><Button variant="link" onClick={() => open('achievement', 'business')}>Your business <ArrowUpRight /></Button></div></div></div><span className="ah-hero-caption">Inspirational concept artwork · physical edition subject to review</span></section>
    <div className="ah-intro ah-wrap"><span><Box /> One collectible. One meaningful story.</span><span><BadgeCheck /> Your milestone, not another challenge.</span><span><BookOpen /> Physical edition by proposal.</span></div>
    <section className="ah-section ah-wrap" id="how-it-works"><div className="ah-section-top"><div><p className="ah-eyebrow">From lived moment to little legend</p><h2>You did the hard part.<br />Let’s make it worth keeping.</h2></div><p>No quest to finish before you begin. Just a moment that matters to you.</p></div><ol className="ah-steps"><li><div className="ah-step-number">01 <Flag /></div><h3>Your milestone</h3><p>Tell us what you’re celebrating. A personal win or a business chapter — big or small.</p></li><li><div className="ah-step-number">02 <Gem /></div><h3>Your collectible + story card</h3><p>Explore a written concept direction, with clearly labelled example artwork. Keep a brief of your story.</p></li><li><div className="ah-step-number">03 <Box /></div><h3>Request a physical edition</h3><p>A complete saved concept can enter proposal review. Feasibility, pricing and production are agreed later.</p></li></ol></section>
    <section className="ah-examples-band" id="milestone-examples"><div className="ah-section ah-wrap"><div className="ah-section-top"><div><p className="ah-eyebrow">The inspiration shelf</p><h2>Different stories. Same little magic.</h2></div><p>Illustrative examples, not customer work or products available to buy.</p></div><div className="ah-examples">{examples.map(example => <article className="ah-example" key={example.title}><figure><img src={example.image} width={1024} height={1024} loading="lazy" alt={`${example.category}: inspirational collectible and matching story card`} /></figure><div><small>{example.category}</small><h3>{example.title}</h3><p>{example.description}</p><Button variant="ghost" className="ah-text-action" onClick={() => open('achievement', example.type)}>Celebrate a moment like this <ArrowUpRight /></Button></div></article>)}</div><div className="ah-example-footer"><span>Marathons, graduations, hobby breakthroughs, first stores — your story chooses the form.</span><Link to="/showcase">Explore brand-world studies <ArrowUpRight size={13} className="inline" /></Link></div></div></section>
    <section className="ah-section ah-wrap ah-pair"><figure><img src={runner} width={1024} height={1024} loading="lazy" alt="Example product pair: a runner miniature beside its matching illustrated story card" /><figcaption>OFFKIN art-direction example · not manufactured or print-ready</figcaption></figure><div><p className="ah-eyebrow"><Star size={15} /> A pair with a purpose</p><h2>A little figure.<br />A story only you can tell.</h2><p className="ah-pair-description">Not just a trophy on a desk. A small, personal world that takes you back to the moment.</p><dl><div><Gem /><dt>The collectible</dt><dd>A character, signature object or miniature inspired by your milestone.</dd></div><div><BookOpen /><dt>The illustrated story card</dt><dd>A matching visual chapter, with your milestone’s own narration.</dd></div><div><Box /><dt>The possible physical edition</dt><dd>3D-printing feasibility, materials and finish assessed in a separate build proposal.</dd></div></dl><Button className="ah-primary" onClick={() => open('achievement')}>Find your story <ArrowRight /></Button></div></section>
    <section className="ah-quest-band"><div className="ah-section ah-wrap ah-quest"><div><p className="ah-eyebrow"><Mountain size={15} /> The next chapter is optional</p><h2>Something to work toward.<br />Something to remember it by.</h2><p>Have a goal, not a finished milestone? Save an intention on this device. Return when you’re ready to celebrate.</p><Button variant="ghost" className="ah-text-action" onClick={() => open('quest')}>Plan a future quest <ArrowRight /></Button></div><div><div className="ah-shelf" aria-label="Trophy shelf coming soon"><div><Flag /><span>The beginning</span></div><div><Mountain /><span>The journey</span></div><div><Trophy /><span>The milestone</span></div></div><p className="ah-shelf-caption">Trophy Shelf · coming soon. A visual metaphor, not a live habit tracker.<br />Gold accents express a style, not monetary rarity or reward value.</p></div></div></section>
    <section className="ah-section ah-wrap ah-business" id="business-milestones"><div><p className="ah-eyebrow">For teams & brands</p><h2>Your business DNA.<br />Made collectible.</h2><p>Employee recognition. A first store. A merchandise milestone. Make an achievement feel like it belongs to your business.</p><div className="ah-inline-actions"><Button className="ah-primary" onClick={() => open('achievement', 'business')}>Celebrate a business milestone <ArrowRight /></Button><Button asChild variant="link" className="ah-text-action"><Link to="/?studio=brand">Open brand studio <ArrowUpRight /></Link></Button></div></div><div className="ah-business-notes"><p><strong>More than character figures.</strong>Choose a meaningful object, product-inspired miniature or business artifact as the direction.</p><p><strong>A STIVE merchandise milestone?</strong>That could be a starting brief — you supply and confirm the real achievement. It is not a claimed client result.</p><p><strong>Already have a saved concept?</strong><Link to="/?proposal=1">Open your saved proposal</Link> to continue to its existing request form. Requests are saved privately for owner review, not automatically emailed.</p></div></section>
    <section className="ah-bottom ah-wrap"><p className="ah-eyebrow justify-center"><Sparkles size={15} /> Your next keepsake starts here</p><h2>Some moments deserve a place<br />outside your camera roll.</h2><p>Tell the story. Explore the direction. Decide on the physical edition only after the details are clear.</p><Button className="ah-primary" onClick={() => open('achievement')}>Create My Collectible <ArrowRight /></Button><small>Concept preview. Final design, functionality and pricing confirmed during the build proposal.<br />No automatic purchase. No production promise from an image.</small></section>
    </main><footer className="ah-footer ah-wrap"><span>{settings.title} / 异趣伙伴 · Little objects. Real stories.</span><nav aria-label="Footer navigation"><Link to="/showcase">Showcase</Link><Link to="/?proposal=1">Saved proposals</Link><Link to="/?engine=paired-draft">Design review</Link></nav></footer>
    {mode && <Suspense fallback={<p className="ah-wrap" role="status">Opening your story…</p>}><AchievementWizard key={`${mode}-${initialType}`} mode={mode} initialType={initialType} onClose={() => setParams({})} /></Suspense>}
  </div>;
}