import { useEffect, useRef, useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { ArrowDown, ArrowRight, Check, ChevronRight, Copy, Download, ExternalLink, Eye, Layers3, LoaderCircle, LockKeyhole, Maximize2, MessageCircle, Plus, RotateCcw, Share2, Sparkles, Star, X } from 'lucide-react';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { supabase } from '@/integrations/supabase/client';
import { studioBrand } from '@/lib/studio-brand';
import { normalizeCompanyWebsite } from '@/lib/company-website';
import { requestConcept, type WebsiteEvidence } from '@/lib/concept-api';
import { CANVAS_CONTRACT_VERSION, requestCanvasConcept, restoreCanvasConcept, supportsCanvasGeneration } from '@/lib/canvas-api';
import { worldReferences } from '@/lib/world-references';
import { branchCanvasSession, canvasContext, decodeCanvasShare, emptyCanvasSession, encodeCanvasShare, loadCanvasSession, makeCanvasBrief, physicalFingerprint, saveCanvasSession, saveCanvasSnapshot, loadCanvasSnapshot, worldFingerprint, type CanvasBrief, type CanvasSession } from '@/lib/canvas-session';
import './canvas-studio.css';

type GeneratedConcept = NonNullable<Awaited<ReturnType<typeof requestCanvasConcept>>['concept']>;
type Element = { id: string; label: string; description: string; kind: 'fact'|'proposal'; x?: number; y?: number; thumbnailImage?: string };
type SiteSettings = { title:string;logo:string;link:string };
const storyChoices = ['The world we bring together', 'A signature ritual', 'An unexpected side of us'];
const interactionChoices = ['Turn to reveal','A meaningful click','Slide to discover','Display only'];
const safeLink = (value: string) => value.startsWith('/') && !value.startsWith('//') || /^https?:\/\//i.test(value) ? value : '/';

export default function CanvasStudio() {
  const location = useLocation(); const navigate = useNavigate();
  const [session,setSession] = useState<CanvasSession>(emptyCanvasSession);
  const [saved,setSaved] = useState<CanvasSession|null>(loadCanvasSession);
  const [hasStarted,setHasStarted] = useState(false);
  const [world,setWorld] = useState<GeneratedConcept|null>(null);
  const [physical,setPhysical] = useState<GeneratedConcept|null>(null);
  const [activeElement,setActiveElement] = useState('');
  const [replacement,setReplacement] = useState('');
  const [note,setNote] = useState('');
  const [status,setStatus] = useState('');
  const [saveProblem,setSaveProblem] = useState(false);
  const [snapshotFailures,setSnapshotFailures] = useState<string[]>([]);
  const [busy,setBusy] = useState<''|'website'|'world'|'physical'|'restore'>('');
  const [ready,setReady] = useState<boolean|null>(null);
  const [readinessAttempt,setReadinessAttempt] = useState(0);
  const [evidence,setEvidence] = useState<WebsiteEvidence|null>(null);
  const [conceptOpen,setConceptOpen] = useState(true);
  const [mobilePanel,setMobilePanel] = useState<'story'|'elements'|'physical'|null>(null);
  const [dialog,setDialog] = useState<'share'|'prototype'|'board'|'import'|null>(null);
  const [shared,setShared] = useState<CanvasSession|null>(null);
  const [shareLink,setShareLink] = useState('');
  const [shareStatus,setShareStatus] = useState('');
  const [includeGenerated,setIncludeGenerated] = useState(false);
  const [settings,setSettings] = useState<SiteSettings>({title:studioBrand.name,logo:'',link:'/'});
  const [imageErrors,setImageErrors] = useState<Record<string,boolean>>({});
  const controller = useRef<AbortController|null>(null);
  const run = useRef(0);
  const inFlight = useRef(false);
  const afterNavigation = useRef<null|{pathname:string;search:string;hash:string;requestEpoch:number;resume:()=>void}>(null);
  const reference = worldReferences.find(r=>r.id===session.referenceId) || worldReferences[0];
  const displayedWorld = world || session.sharedWorld || (session.worldId ? {title:'Your saved brand world',story:'Image metadata could not be restored. The original concept remains identified below; no reference artwork has been substituted.',worldElements:session.selected.map(id=>({id,label:id,description:'Saved element metadata unavailable. Restore this world to retrieve its description.',kind:'proposal' as const}))} : {title:reference.title,story:reference.story,worldElements:reference.elements});
  const elements: Element[] = displayedWorld.worldElements;
  const active = elements.find(e=>e.id===activeElement);
  const selectedCount = elements.filter(e=>session.selected.includes(e.id)).length;
  const worldIsCurrent = Boolean(world && (!session.worldFingerprint || session.worldFingerprint===worldFingerprint(session)));
  const physicalIsCurrent = Boolean(physical && session.physicalFingerprint===physicalFingerprint(session));
  const hasOwnWorld=Boolean(world||session.worldId||session.sharedWorld);
  const worldImage = hasOwnWorld ? world?.image || '' : reference.worldImage;
  const physicalImage = physical?.image || (!hasOwnWorld ? reference.physicalImage : '');
  const locked = Boolean(busy);
  const storageProblem = saveProblem || snapshotFailures.some(id=>id===session.worldId||id===session.physicalId);

  useEffect(()=>{let live=true; supabase.from('site_settings').select('key,value').then(({data})=>{
    if(!live||!data)return; const next={title:studioBrand.name,logo:'',link:'/'};
    data.forEach(s=>{ if(s.key==='site_title'&&s.value&&!['dioramini','briq2.0','briq','form.','brandkin','stive','the absurd marshmallow test'].includes(s.value.trim().toLowerCase()))next.title=s.value;
      if(s.key==='logo_url'&&/^https?:\/\//i.test(s.value||''))next.logo=s.value;
      if(s.key==='logo_link'&&s.value&&s.value!=='https://example.com')next.link=safeLink(s.value); }); setSettings(next);
  });return()=>{live=false;};},[]);
  useEffect(()=>{document.title=`${settings.title}｜异趣伙伴 — ${studioBrand.headline}`;},[settings.title]);
  useEffect(()=>{const abort=new AbortController();setReady(null);supportsCanvasGeneration(abort.signal).then(value=>{if(!abort.signal.aborted)setReady(value);});return()=>abort.abort();},[readinessAttempt]);
  useEffect(()=>{if(hasStarted)setSaveProblem(!saveCanvasSession(session));},[session,hasStarted]);
  useEffect(()=>()=>{run.current++;controller.current?.abort();inFlight.current=false;afterNavigation.current=null;},[]);
  useEffect(()=>{run.current++;controller.current?.abort();controller.current=null;inFlight.current=false;setBusy('');
    if(location.hash.startsWith('#world=')){const candidate=decodeCanvasShare(location.hash);setShared(candidate);setDialog('import');setStatus(candidate?'':'This shared version is invalid or too long. Your local work has not changed.');}
    else {setDialog(null);setShared(null);setShareLink('');setShareStatus('');}
    const pending=afterNavigation.current;afterNavigation.current=null;if(pending&&pending.pathname===location.pathname&&pending.search===location.search&&pending.hash===location.hash&&pending.requestEpoch===run.current-1)pending.resume();
    // A URL change cancels pending work; incoming versions never silently overwrite local work.
  },[location.key,location.hash,location.pathname,location.search]);
  useEffect(()=>{setReplacement('');},[activeElement]);

  function persistSnapshot(concept:GeneratedConcept){const saved=saveCanvasSnapshot(concept);setSnapshotFailures(ids=>saved?ids.filter(id=>id!==concept.id):Array.from(new Set([...ids,concept.id])));}
  function update(change: Partial<CanvasSession> | ((previous:CanvasSession)=>CanvasSession)) {setHasStarted(true);setSession(s=>typeof change==='function'?change(s):{...s,...change});}
  function brief(field:keyof CanvasBrief,value:string) {update(s=>({...s,brief:{...s.brief,[field]:value}}));}
  function cancel() {run.current++;controller.current?.abort();controller.current=null;inFlight.current=false;afterNavigation.current=null;setBusy('');setStatus('Cancelled. Your direction is still here. A provider request already started may still use credits.');}
  function startRequest(kind:typeof busy) {inFlight.current=true;controller.current?.abort();const abort=new AbortController();controller.current=abort;const token=++run.current;setBusy(kind);setStatus('');return{abort,token};}
  const isLive=(token:number,abort:AbortController)=>run.current===token&&!abort.signal.aborted;
  async function readWebsite() {
    if(inFlight.current)return;
    const url=normalizeCompanyWebsite(session.brief.website);if(!url){setStatus('Enter a public company website, such as yourbrand.com.');return;}
    const {abort,token}=startRequest('website');const timer=window.setTimeout(()=>abort.abort(),35000);
    try{const result=await requestConcept({brand:url,context:'',edition:'icon',format:'miniature',inspectWebsite:true},abort.signal);if(!isLive(token,abort))return;
      if(result.website){setEvidence(result.website);brief('website',url);setStatus('Website text is ready to review. Choose what belongs in your story.');}
      else setStatus('This website couldn’t be read. Add a short business description to continue.');
    }catch(error){if(isLive(token,abort))setStatus(error instanceof Error?error.message:'Could not read this website. You can describe your business instead.');}
    finally{clearTimeout(timer);if(run.current===token){inFlight.current=false;controller.current=null;setBusy('');if(abort.signal.aborted)setStatus('Website reading timed out. Your answers are intact; try again or describe the business.');}}
  }
  async function generate(stage:'world'|'physical') {
    if(inFlight.current)return;
    if(stage==='world'&&!session.brief.business.trim()){setStatus('Tell us a little about the business before generating your world.');if(window.innerWidth<=900)setMobilePanel('story');return;}
    if(stage==='physical'&&(!world||!worldIsCurrent||!selectedCount||!session.hero)){setStatus('Generate your brand world, then select its elements and a main character first.');return;}
    const url=session.brief.website.trim()?normalizeCompanyWebsite(session.brief.website):'no-website';if(!url){setStatus('Check the website address, or leave it empty and use your description.');return;}
    const snapshot=session;const {abort,token}=startRequest(stage);const timer=window.setTimeout(()=>abort.abort(),220000);
    try{const result=await requestCanvasConcept({contractVersion:CANVAS_CONTRACT_VERSION,stage,brand:url,context:canvasContext(snapshot.brief),...(stage==='physical'?{sourceWorldId:world.id,selectedElementIds:snapshot.selected,heroElementId:snapshot.hero,replacements:snapshot.replacements}:{})},abort.signal);
      if(!isLive(token,abort))return;if(!result.concept)throw new Error('The generator needs a more specific business description. Your direction is still here.');
      const concept=result.concept;setImageErrors({});persistSnapshot(concept);
      if(stage==='world'){setWorld(concept);setPhysical(null);setActiveElement('');update(s=>({...s,worldId:concept.id,physicalId:'',sharedWorld:undefined,selected:concept.worldElements.map(e=>e.id),hero:concept.worldElements[0]?.id||'',replacements:[],worldFingerprint:worldFingerprint(snapshot),physicalFingerprint:''}));setStatus('Your brand world is ready. Choose the elements that should become physical.');setMobilePanel(null);}
      else{setPhysical(concept);update({physicalId:concept.id,physicalFingerprint:physicalFingerprint(snapshot)});setStatus('Your physical concept is ready, shaped by this world and your selected elements.');setConceptOpen(true);if(window.innerWidth<=900)setMobilePanel('physical');}
    }catch(error){if(isLive(token,abort))setStatus(error instanceof Error?error.message:'Generation didn’t finish. Your direction is still here.');}
    finally{clearTimeout(timer);if(run.current===token){inFlight.current=false;controller.current=null;setBusy('');if(abort.signal.aborted)setStatus('Generation took too long. Your direction is intact. Retrying an identical completed request can restore its cached result.');}}
  }
  async function restore(next:CanvasSession,branch=false) {
    const local=branch?branchCanvasSession(next):next;const cachedWorld=loadCanvasSnapshot(local.worldId);const cachedPhysical=loadCanvasSnapshot(local.physicalId);setSaved(null);setWorld(cachedWorld?.stage==='world'?cachedWorld:null);setPhysical(cachedPhysical?.stage==='physical'&&cachedPhysical.sourceWorldId===local.worldId?cachedPhysical:null);setActiveElement('');setEvidence(null);setHasStarted(true);setSession(local);setDialog(null);setShared(null);
    if(!local.worldId){setStatus(branch?'This is your own editable version. Changes stay on this device.':'Your saved direction is open.');if(location.hash)navigate(location.pathname,{replace:true});return;}
    const restoreImages=async()=>{const {abort,token}=startRequest('restore');const timer=window.setTimeout(()=>abort.abort(),35000);
      try {const result=await restoreCanvasConcept(local.worldId,abort.signal);if(!isLive(token,abort))return;if(!result.concept||result.concept.stage!=='world')throw new Error('The saved world could not be opened.');setWorld(result.concept);persistSnapshot(result.concept);
        const validIds=new Set(result.concept.worldElements.map(e=>e.id));const chosen=local.selected.filter(id=>validIds.has(id));const safeSession={...local,selected:chosen,hero:chosen.includes(local.hero)?local.hero:chosen[0]||'',replacements:local.replacements.filter(r=>chosen.includes(r.id))};
        // Imported links intentionally omit fingerprints. Reading the stored source gives the comparison basis.
        const restoredBrief={...safeSession.brief,...Object.fromEntries(Object.entries(result.concept.context||{}).filter(([key])=>key in safeSession.brief))};
        setSession(s=>({...safeSession,prototype:s.prototype,worldFingerprint:local.worldFingerprint||worldFingerprint({...safeSession,brief:restoredBrief})}));
        if(local.physicalId){const item=await restoreCanvasConcept(local.physicalId,abort.signal);if(!isLive(token,abort))return;if(item.concept?.stage==='physical'&&item.concept.sourceWorldId===local.worldId){setPhysical(item.concept);persistSnapshot(item.concept);if(!local.physicalFingerprint)setStatus('Version opened. Review the physical image against this branch’s current selections before using it.');}else setStatus('World restored. The saved physical concept is unavailable.');}
        else setStatus(branch?'Your own version is open. Changes won’t update anyone else’s copy.':'World restored. Image access refreshed without generation.');
      }catch(error){if(isLive(token,abort))setStatus(error instanceof Error?error.message:'Saved image couldn’t be restored. Your written direction is still here.');}
      finally{clearTimeout(timer);if(run.current===token){inFlight.current=false;controller.current=null;setBusy('');if(abort.signal.aborted)setStatus('Image restoration timed out. Your written direction is intact. Try restoring images again.');}}
    };
    if(location.hash){afterNavigation.current={pathname:location.pathname,search:'',hash:'',requestEpoch:run.current,resume:()=>{void restoreImages();}};navigate(location.pathname,{replace:true});}
    else void restoreImages();
  }
  function selectReference(id:CanvasSession['referenceId']) {
    if(locked)return;const next=worldReferences.find(r=>r.id===id)!;setWorld(null);setPhysical(null);setActiveElement('');setImageErrors({});update({referenceId:id,worldId:'',physicalId:'',sharedWorld:undefined,selected:next.elements.map(e=>e.id),hero:next.elements[0]?.id||'',replacements:[],worldFingerprint:'',physicalFingerprint:''});setStatus(`${next.name} is an unofficial reference study. Your business answers are still in the story panel.`);
  }
  function toggleElement(id:string) {update(s=>{const included=s.selected.includes(id);const selected=included?s.selected.filter(x=>x!==id):[...s.selected,id];return{...s,selected,hero:included&&s.hero===id?selected[0]||'':s.hero||id,replacements:included?s.replacements.filter(r=>r.id!==id):s.replacements};});}
  function applyReplacement() {if(!active||!replacement.trim())return;const label=replacement.trim();update(s=>({...s,selected:s.selected.includes(active.id)?s.selected:[...s.selected,active.id],hero:s.hero||active.id,replacements:[...s.replacements.filter(r=>r.id!==active.id),{id:active.id,label,description:`Proposed replacement for ${active.label}: ${label}`}]}));setReplacement('');setStatus('Replacement saved for your next physical concept. The brand-world illustration stays unchanged.');}
  function applyNote(){if(!note.trim())return;brief('notes',note);setNote('');setStatus('Direction note saved. It will be included in your next explicit generation.');}
  function downloadSessionBrief(target:CanvasSession){const targetReference=worldReferences.find(r=>r.id===target.referenceId)||worldReferences[0];const candidateWorld=target===session?world:loadCanvasSnapshot(target.worldId);const savedWorld=candidateWorld?.stage==='world'?candidateWorld:null;const targetWorld=savedWorld||target.sharedWorld||(target.worldId?{title:`Saved world ${target.worldId}`,story:'Saved generated world metadata is unavailable. Reopen this world to restore the complete narrative. No reference study is substituted.',worldElements:target.selected.map(id=>({id,label:id,description:'Description unavailable on this device; original element ID retained.',kind:'proposal'}))}:{title:targetReference.title,story:targetReference.story,worldElements:targetReference.elements});const candidatePhysical=target===session?physical:loadCanvasSnapshot(target.physicalId);const savedPhysical=candidatePhysical?.stage==='physical'&&candidatePhysical.sourceWorldId===target.worldId?candidatePhysical:null;const content=makeCanvasBrief(target,targetWorld,savedPhysical?.title);const url=URL.createObjectURL(new Blob([content],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`OFFKIN-${target.version.slice(0,8)}-prototype-brief.txt`;a.click();window.setTimeout(()=>URL.revokeObjectURL(url),1000);setStatus('Brief downloaded. It hasn’t been sent to anyone.');}
  function downloadBrief(){downloadSessionBrief(session);}
  function downloadCurrentBackup(){downloadSessionBrief(!hasStarted&&saved?saved:session);}
  function openShare(){setShareLink('');setShareStatus('');setIncludeGenerated(false);setDialog('share');}
  async function createLink(){try{const link=new URL(location.pathname,window.location.origin);const sharedWorld=hasOwnWorld?{title:displayedWorld.title,story:displayedWorld.story,worldElements:elements.filter(e=>session.selected.includes(e.id)).map(e=>{const r=session.replacements.find(r=>r.id===e.id);return{id:e.id,label:r?.label||e.label,description:r?.description||e.description,kind:r?'proposal' as const:e.kind};})}:undefined;link.hash=encodeCanvasShare(session,{includeGenerated,sharedWorld});const value=link.toString();setShareLink(value);try{await navigator.clipboard.writeText(value);setShareStatus('Link copied. Each person opens a separate editable version.');}catch{setShareStatus('Select and copy the link below.');}}catch(error){setShareStatus(error instanceof Error?error.message:'This link couldn’t be created. Download the brief instead.');}}
  function fresh(){controller.current?.abort();controller.current=null;inFlight.current=false;afterNavigation.current=null;run.current++;setBusy('');setSaved(null);setSnapshotFailures([]);setHasStarted(true);setWorld(null);setPhysical(null);setSession(emptyCanvasSession());setEvidence(null);setStatus('A fresh local direction is ready.');setActiveElement('');navigate(location.pathname,{replace:true});}
  const StoryPanel= <>
    <div className="cw-panel-heading"><span className="cw-step">01</span><h2>Your story, first.</h2><MessageCircle size={17}/></div>
    <p className="cw-panel-intro">A business has a whole world inside it. Let’s find yours.</p>
    <label className="cw-label" htmlFor="canvas-website">YOUR WEBSITE <span>optional</span></label>
    <div className="cw-url-row"><input id="canvas-website" value={session.brief.website} onChange={e=>brief('website',e.target.value)} placeholder="yourbrand.com" maxLength={300} disabled={locked}/><button aria-label="Read public website" onClick={readWebsite} disabled={locked||!session.brief.website.trim()}><ArrowRight size={18}/></button></div>
    <p className="cw-micro">Read-only lookup. No image is generated.</p>
    {evidence&&<details className="cw-evidence"><summary>Review website text <ExternalLink size={12}/></summary><a href={evidence.url} target="_blank" rel="noopener noreferrer">{evidence.title||evidence.url}</a><p>{evidence.excerpt}</p><button onClick={()=>{brief('business',evidence.excerpt.slice(0,1000));setStatus('Website excerpt copied as a starting point. Edit it to describe what matters.');}} disabled={locked}>Use excerpt as a starting point</button></details>}
    <label className="cw-label" htmlFor="canvas-business">WHAT SHOULD WE KNOW?</label><textarea id="canvas-business" maxLength={1000} rows={3} value={session.brief.business} placeholder="What you do, who you bring together, the little thing that makes you different…" onChange={e=>brief('business',e.target.value)} disabled={locked}/>
    <fieldset className="cw-choice-group" disabled={locked}><legend>WHERE DOES THE STORY BEGIN?</legend>{storyChoices.map((choice,i)=><button key={choice} aria-pressed={session.brief.angle===choice} onClick={()=>brief('angle',choice)}><span>{String(i+1).padStart(2,'0')}</span>{choice}{session.brief.angle===choice?<Check size={15}/>:<Plus size={15}/>}</button>)}</fieldset>
    <details className="cw-details"><summary>Brand cues & exact wording <Plus size={14}/></summary><label className="cw-label" htmlFor="canvas-cues">LOGO, COLOURS, PEOPLE, PLACES</label><textarea id="canvas-cues" value={session.brief.brandIdentifiers} onChange={e=>brief('brandIdentifiers',e.target.value)} maxLength={500} rows={3} disabled={locked} placeholder="Describe the identifiers that belong in your world"/><p className="cw-micro">Text references only. No brand artwork upload is implied.</p><label className="cw-label" htmlFor="canvas-words">EXACT WORDING</label><textarea id="canvas-words" value={session.brief.exactWording} onChange={e=>brief('exactWording',e.target.value)} maxLength={200} rows={2} disabled={locked} placeholder="Optional. Preserved verbatim for proofing."/><label className="cw-label" htmlFor="canvas-audience">WHO IS IT FOR?</label><select id="canvas-audience" value={session.brief.audience} onChange={e=>brief('audience',e.target.value)} disabled={locked}>{['Clients & partners','Our team','A community','Personal collection'].map(v=><option key={v}>{v}</option>)}</select><label className="cw-label" htmlFor="canvas-style">VISUAL ENERGY</label><select id="canvas-style" value={session.brief.style} onChange={e=>brief('style',e.target.value)} disabled={locked}>{['Rich illustrated world','Cinematic & strange','Bold graphic universe','Playful sculptural world'].map(v=><option key={v}>{v}</option>)}</select></details>
    <button className="cw-primary cw-generate" onClick={()=>generate('world')} disabled={locked||ready!==true}><Sparkles size={16}/>{busy==='world'?'Creating your world…':world?'Regenerate brand world':'Generate my brand world'}<ArrowRight size={16}/></button>
    <p className="cw-micro">Only this button starts world generation. Your edits stay local until then.{world&&' A new world resets its element choices; replacements apply to the physical concept.'}</p>
    {ready!==true&&<div className="cw-readiness"><span>{ready===null?'Checking generator…':'Image generation is not connected to this canvas yet. You can still explore, save and share a direction.'}</span>{ready===false&&<button onClick={()=>setReadinessAttempt(v=>v+1)}>Check again</button>}</div>}
    <div className="cw-guide"><span className="cw-guide-avatar">o.</span><div><strong>A little art. A little odd.</strong><p>Think big online. We’ll work out the physical details together after the story feels right.</p></div></div>
  </>;
  const PhysicalPanel=<>
    <div className="cw-panel-heading"><span className="cw-step">03</span><h2>Into the real world.</h2><button className="cw-icon-button cw-close-preview" onClick={()=>{setConceptOpen(false);setMobilePanel(null);}} aria-label="Collapse physical preview"><ChevronRight size={18}/></button></div>
    <div className="cw-physical-image">{physicalImage&&!imageErrors[physicalImage]?<img src={physicalImage} alt={physical?`${physical.brand}: ${physical.title}, unvalidated physical concept`:`${reference.name} original physical concept reference`} onError={()=>setImageErrors(s=>({...s,[physicalImage]:true}))}/>:<div className="cw-image-placeholder"><Layers3 size={35}/><strong>Your world, made tangible.</strong><p>{imageErrors[physicalImage]?'This image couldn’t load. The written direction is still available.':'Select the elements that matter, then generate a physical interpretation.'}</p></div>}<span className="cw-image-tag">{physical?'PHYSICAL CONCEPT':hasOwnWorld?'NEXT: PHYSICAL CONCEPT':'REFERENCE CONCEPT'}</span></div>
    <h3 className="cw-physical-title">{physical?.title||(!hasOwnWorld?reference.title:'A collectible only your story could make.')}</h3><p className="cw-small-copy">{physical?.story||(!hasOwnWorld?'One possible physical expression of the illustrated world. Explore its story elements on the canvas.':'Your selected hero, supporting elements and direction will shape a new physical concept image.')}</p>
    {physical&&!physicalIsCurrent&&<p className="cw-pending">Your selections have changed. This preview is the previous version; generate again to apply them.</p>}
    <fieldset className="cw-interactions" disabled={locked}><legend>A MEANINGFUL LITTLE ACTION</legend>{interactionChoices.map((v,i)=><button aria-pressed={session.brief.interaction===v} onClick={()=>brief('interaction',v)} key={v}><span>{['↻','↓','↔','◌'][i]}</span>{v}{session.brief.interaction===v&&<Check size={13}/>}</button>)}</fieldset>
    <button className="cw-primary" onClick={()=>generate('physical')} disabled={locked||ready!==true||!worldIsCurrent||!selectedCount||!session.hero}><Sparkles size={16}/>{busy==='physical'?'Creating physical concept…':physical?'Regenerate physical concept':'Generate physical concept'}<ArrowRight size={16}/></button>
    <p className="cw-micro">{!world?'Start by generating your own brand world.':!worldIsCurrent?'Your business story changed. Regenerate the world first.':`${selectedCount} selected elements · ${elements.find(e=>e.id===session.hero)?.label||'Choose a hero'}`}<br/>One explicit generation. No changes are made automatically.</p>
    <button className="cw-prototype-link" onClick={()=>setDialog('prototype')}>Plan a real prototype <ArrowRight size={16}/></button>
    <p className="cw-micro">A paid offline design and sample phase turns the chosen direction into a production plan. This image is a proposal, not a product for sale.</p>
  </>;
  const ElementEditor=active&&<div className="cw-element-editor"><div className="cw-element-heading"><span className="cw-step">{String(elements.indexOf(active)+1).padStart(2,'0')}</span><div><p>{active.kind==='fact'?'SOURCE-BASED ELEMENT':'PROPOSED STORY ELEMENT'}</p><h3>{session.replacements.find(r=>r.id===active.id)?.label||active.label}</h3></div><button className="cw-icon-button" onClick={()=>setActiveElement('')} aria-label="Close element details"><X size={17}/></button></div><p>{active.description}</p><div className="cw-element-actions"><button onClick={()=>toggleElement(active.id)} disabled={locked}>{session.selected.includes(active.id)?<Check size={14}/>:<Plus size={14}/>} {session.selected.includes(active.id)?'Included · remove':'Include element'}</button><button aria-pressed={session.hero===active.id} onClick={()=>update(s=>({...s,hero:active.id,selected:s.selected.includes(active.id)?s.selected:[...s.selected,active.id]}))} disabled={locked}><Star size={14}/>{session.hero===active.id?'Main character':'Make main character'}</button></div><label className="cw-label" htmlFor="replace-element">OR REPLACE WITH ANOTHER IDEA</label><div className="cw-url-row"><input id="replace-element" maxLength={80} placeholder="e.g. our neighbourhood bakery" value={replacement} onChange={e=>setReplacement(e.target.value)} disabled={locked}/><button onClick={applyReplacement} disabled={locked||!replacement.trim()} aria-label="Apply element replacement"><ArrowRight size={16}/></button></div><p className="cw-micro">Changes update the brief for your next physical concept. They do not edit pixels in this illustration.</p></div>;
  return <div className="cw-app"><a className="cw-skip" href="#canvas-main">Skip to brand-world canvas</a>
    <header className="cw-header"><a className="cw-logo" href={settings.link} aria-label={`${settings.title} home`}>{settings.logo?<img src={settings.logo} alt={settings.title}/>:<><span className="cw-logo-mark"><i/><i/></span><span>{settings.title}<small lang="zh-Hans">异趣伙伴</small></span></>}</a><div className="cw-header-center"><span>ART × TECHNOLOGY × COMMERCE</span><span className="cw-live-dot"/>INDEPENDENT BY NATURE</div><button onClick={()=>setDialog('prototype')} className="cw-header-link">FROM IDEA TO OBJECT <ArrowRight size={15}/></button></header>
    <section className="cw-intro"><div><p className="cw-eyebrow">AN OPEN CANVAS FOR UNCOMMON BRANDS</p><h1>Your business DNA.<br/><span>Made collectible.</span></h1></div><div className="cw-intro-copy"><p>A whole world of stories.<br/>A physical thing worth keeping.</p><span>Explore it. Make it yours. Bring it to life.</span><a href="#canvas-main" aria-label="Explore canvas"><ArrowDown size={18}/></a></div></section>
    {saved&&!hasStarted&&<div className="cw-resume"><span><RotateCcw size={16}/>A direction is saved on this device.</span><button onClick={()=>restore(saved)}>Resume my direction</button><button onClick={fresh}>Start fresh</button></div>}
    <div className="cw-workspace-top"><div className="cw-workspace-title"><span className="cw-step">02</span><strong>The world-building table</strong><span className="cw-workspace-note">Play with the parts. Keep the story.</span></div><div className="cw-tools"><span className="cw-private"><LockKeyhole size={12}/> {hasStarted?(storageProblem?'Not saved on this device':'Saved on this device'):'Private until you share'}</span><button onClick={downloadBrief} aria-label="Download current brief"><Download size={16}/><span>Save brief</span></button><button onClick={openShare} disabled={locked}><Share2 size={15}/><span>Share a version</span></button></div></div>
    <main id="canvas-main" className={`cw-workspace ${conceptOpen?'':'cw-preview-collapsed'}`}>
      <aside className="cw-story-panel" aria-label="Business story choices">{StoryPanel}</aside>
      <section className="cw-canvas-column" aria-label="Brand world canvas">
        <div className="cw-canvas-toolbar"><div className="cw-reference-tabs" aria-label="Explore original concept studies">{worldReferences.map(r=><button key={r.id} onClick={()=>selectReference(r.id)} disabled={locked} aria-pressed={!hasOwnWorld&&session.referenceId===r.id}>{r.name}<span>↗</span></button>)}{world&&<span className="cw-your-world">Your world <Sparkles size={12}/></span>}</div><div className="cw-canvas-controls"><button onClick={()=>setDialog('board')} className="cw-icon-button" aria-label={world?'Enlarge generated world':'View complete original reference board'}><Maximize2 size={16}/></button>{!conceptOpen&&<button onClick={()=>setConceptOpen(true)} className="cw-icon-button" aria-label="Show physical preview"><Layers3 size={17}/></button>}</div></div>
        <div className="cw-art-heading"><div><p>{world?'YOUR GENERATED BRAND WORLD':hasOwnWorld?'YOUR SHARED STORY DIRECTION':'UNOFFICIAL CONCEPT STUDY / ORIGINAL WORLD'}</p><h2>{displayedWorld.title}</h2></div><span className="cw-sketch-note">a world, not just a logo.</span></div>
        <div className={`cw-canvas ${busy==='world'?'cw-canvas-busy':''}`}><div className="cw-art-area">{worldImage&&!imageErrors[worldImage]?<img className="cw-world-art" src={worldImage} alt={world?`${world.brand}: ${world.title}, illustrated brand world`:`${reference.name} original rich illustrated brand world`} onError={()=>setImageErrors(s=>({...s,[worldImage]:true}))}/>:<div className="cw-image-placeholder"><Layers3 size={35}/><h3>{session.sharedWorld&&!session.worldId?'A shared direction, ready to explore':'The illustration couldn’t load'}</h3><p>{session.sharedWorld&&!session.worldId?'This text-only version has no image access. Generate your own world from the reviewed story.':'Your element choices and written direction are still available.'}</p>{worldImage&&<button onClick={()=>setImageErrors(s=>({...s,[worldImage]:false}))}>Try image again</button>}</div>}
          {!hasOwnWorld&&!imageErrors[worldImage]&&elements.map((e,i)=><button key={e.id} className={`cw-hotspot ${activeElement===e.id?'active':''} ${session.selected.includes(e.id)?'included':'excluded'}`} style={{left:`${e.x}%`,top:`${e.y}%`}} aria-label={`Explore ${e.label}`} aria-pressed={activeElement===e.id} onClick={()=>{setActiveElement(e.id);if(window.innerWidth<=900)setMobilePanel('elements');}} disabled={locked}>{i+1}{session.hero===e.id&&<Star size={9} fill="currentColor"/>}</button>)}
          {busy==='world'&&<div className="cw-generating-overlay"><LoaderCircle className="cw-spin" size={29}/><strong>Finding your world…</strong><span>Building connections, characters and unexpected details.</span><button onClick={cancel}>Cancel generation</button></div>}
        </div></div>
        <div className="cw-canvas-caption"><span><span className="cw-caption-dot"/>{world?'Choose story elements below. These are proposed components, not image segmentation.':'Click a numbered story element to shape your direction.'}</span><span>{selectedCount} selected</span></div>
        {!hasOwnWorld&&<p className="cw-reference-note">{reference.name} reference artwork is an independent, uncommissioned concept. {reference.id==='tesla'?'The rocket is a speculative horizon motif, not an official Tesla business claim.':reference.id==='a24'?'Film-inspired imagery is a creative proposal; licensing is not established.':'This is a proposed story world, not an official brand collaboration.'}</p>}
        {world&&!worldIsCurrent&&<p className="cw-pending cw-canvas-pending">Your story has changed. Generate the world again when you’re ready; this image stays as the previous version.</p>}
        <div className="cw-element-tray" aria-label="World story elements">{elements.map((e,i)=><button key={e.id} className={`cw-element-card ${session.selected.includes(e.id)?'selected':''} ${activeElement===e.id?'active':''}`} onClick={()=>{setActiveElement(e.id);if(window.innerWidth<=900)setMobilePanel('elements');}} aria-pressed={activeElement===e.id} disabled={locked}><div className="cw-element-art">{e.thumbnailImage?<img src={e.thumbnailImage} alt=""/>:<span>{String(i+1).padStart(2,'0')}</span>}<span className="cw-inclusion">{session.selected.includes(e.id)?<Check size={10}/>:<Plus size={10}/>}</span>{session.hero===e.id&&<span className="cw-hero-tag"><Star size={10} fill="currentColor"/>HERO</span>}</div><span className="cw-element-name">{session.replacements.find(r=>r.id===e.id)?.label||e.label}</span></button>)}</div>
        <div className="cw-inline-editor">{ElementEditor}</div>
        <div className="cw-direction-note"><span className="cw-guide-avatar">o.</span><div><label htmlFor="canvas-note">Tell the next image where to go.</label><div className="cw-note-input"><input id="canvas-note" maxLength={1000} value={note} onChange={e=>setNote(e.target.value)} placeholder="More neighbourhood. A weirder main character. Keep the yellow road…" disabled={locked}/><button onClick={applyNote} disabled={locked||!note.trim()} aria-label="Save direction note"><ArrowRight size={17}/></button></div>{session.brief.notes&&<p className="cw-saved-note">Saved direction: {session.brief.notes}<button onClick={()=>{setNote(session.brief.notes);}} disabled={locked}>Edit</button><button onClick={()=>brief('notes','')} disabled={locked}>Remove</button></p>}<p className="cw-micro">A guided direction field. Saving a note does not call AI or regenerate the image.</p></div></div>
      </section>
      {conceptOpen&&<aside className="cw-physical-panel" aria-label="Physical concept preview">{PhysicalPanel}</aside>}
    </main>
    {(status||busy||storageProblem||Object.values(imageErrors).some(Boolean))&&<div className="cw-status" role="status" aria-live="polite">{busy&&<LoaderCircle className="cw-spin" size={16}/>}<span>{busy==='website'?'Reading the public website…':busy==='restore'?'Restoring private image links…':busy==='physical'?'Interpreting your selected world as a physical concept…':busy==='world'?'Generating your brand world…':status}{Object.values(imageErrors).some(Boolean)&&' An image could not load. Restore images to refresh access.'}{storageProblem&&' Device storage is unavailable. Download your brief before leaving.'}</span>{busy&&<button onClick={cancel}>Cancel</button>}{!busy&&session.worldId&&(!world?.image||Object.values(imageErrors).some(Boolean))&&<button onClick={()=>{setImageErrors({});restore(session);}}>Restore images again</button>}</div>}
    <section className="cw-process"><div><span>01 / EXPLORE ONLINE</span><h2>Let it get wonderfully strange.</h2><p>Build the full story world. Try unexpected connections, choose your characters, and find the thing that feels unmistakably you.</p></div><div><span>02 / DESIGN TOGETHER</span><h2>Then make the important bits real.</h2><p>A paid offline design and prototype phase works through scale, budget, materials and manufacturing. Production follows an approved sample and quote.</p></div><button onClick={()=>setDialog('prototype')}>Keep a prototype brief <ArrowRight size={18}/></button></section>
    <footer className="cw-footer"><strong>OFFKIN<span lang="zh-Hans">｜异趣伙伴</span></strong><span>CURIOUS BY DESIGN. COLLECTIBLE BY NATURE.</span><span>Concepts, not products for sale.</span></footer>
    <nav className="cw-mobile-nav" aria-label="Canvas tools"><button onClick={()=>setMobilePanel('story')}><MessageCircle size={17}/>Your story</button><button onClick={()=>{if(!activeElement)setActiveElement(elements[0]?.id||'');if(window.innerWidth<=900)setMobilePanel('elements');}}><Layers3 size={17}/>Elements <span>{selectedCount}</span></button><button onClick={()=>setMobilePanel('physical')}><Eye size={17}/>Physical concept</button></nav>
    <Dialog open={Boolean(mobilePanel)} onOpenChange={open=>{if(!open)setMobilePanel(null);}}><DialogContent className="cw-mobile-sheet"><DialogHeader><DialogTitle>{mobilePanel==='story'?'Your business story':mobilePanel==='physical'?'Physical concept':'Shape the story elements'}</DialogTitle><DialogDescription>Changes stay in your direction until you explicitly generate.</DialogDescription></DialogHeader>{mobilePanel==='story'?StoryPanel:mobilePanel==='physical'?PhysicalPanel:ElementEditor||<p>Choose a numbered element on the canvas.</p>}</DialogContent></Dialog>
    <Dialog open={dialog!==null} onOpenChange={open=>{if(!open){setDialog(null);if(dialog==='import')navigate(location.pathname,{replace:true});}}}><DialogContent className={`cw-dialog ${dialog==='board'?'cw-board-dialog':''}`}><DialogHeader><DialogTitle>{dialog==='share'?'Share this version':dialog==='prototype'?'From world to working prototype':dialog==='import'?'Open a shared direction':world?'Your illustrated brand world':'The complete original concept board'}</DialogTitle><DialogDescription>{dialog==='share'?'Review exactly what will be included before creating a link.':dialog==='prototype'?'A planning brief for an offline paid design and sample conversation.':dialog==='import'?'Review this snapshot before creating your own editable branch.':world?'An AI-assisted illustrated concept, not a production specification.':'Original reference artwork. Independent, uncommissioned and not production-validated.'}</DialogDescription></DialogHeader>
      {dialog==='board'&&<>{hasOwnWorld&&!world?.image?<p>Restore this world’s image to open the full illustration.</p>:<img src={world?world.image:reference.boardImage} alt={world?`${world.title}, full illustration`:`${reference.name}, complete original concept board`}/>} {!hasOwnWorld&&<p className="cw-micro">The original board may contain speculative mechanisms, dimensional assumptions or other unsupported claims. It is a visual reference. Final scope, rights and construction need review.</p>}</>}
      {dialog==='share'&&<><div className="cw-share-summary"><p><strong>Included:</strong> website, business description, story choices, brand cues, exact wording, direction notes, selected elements, replacements and prototype planning fields.</p><p><strong>Default sharing:</strong> current direction text only. Generated image IDs and original generation briefs are excluded.</p><p><strong>Collaboration:</strong> each coworker creates a separate version. There is no live shared editing or automatic sync.</p></div>{session.worldId&&<div className="cw-image-sharing"><label><input type="checkbox" checked={includeGenerated} disabled={!world?.image||Boolean(session.physicalId&&!physical?.image)} onChange={e=>{setIncludeGenerated(e.target.checked);setShareLink('');setShareStatus('');}}/>Include generated images and their original briefs</label><p className="cw-micro">Anyone with the link can open the original stored business text, wording, design and story metadata for these images, including details you later removed. {(!world?.image||Boolean(session.physicalId&&!physical?.image))&&'Restore all images before choosing this option.'}</p>{includeGenerated&&<details className="cw-details" open><summary>Review original generated data shared through image access</summary><pre className="cw-share-review">{JSON.stringify([world,physical].filter(Boolean).map(({image,...metadata})=>metadata),null,2)}</pre></details>}</div>}<details className="cw-details" open><summary>Review the data in this link</summary><pre className="cw-share-review">{makeCanvasBrief(session,displayedWorld,includeGenerated?physical?.title:undefined)}</pre></details><p className="cw-micro">The link itself contains the text. Anyone you give it to can read and forward it. Include only information you’re comfortable sharing.</p><div className="cw-dialog-actions"><button className="cw-secondary" onClick={()=>setDialog(null)}>Cancel</button><button className="cw-primary" onClick={createLink}><Copy size={15}/>Create & copy this version link</button></div>{shareLink&&<label className="cw-label">VERSION LINK<input value={shareLink} readOnly onFocus={e=>e.target.select()}/></label>}<p role="status">{shareStatus}</p></>}
      {dialog==='prototype'&&<><p className="cw-small-copy">Keep the creative world rich. Final design, simplifying it for manufacture and testing one or two meaningful motions happen in the paid offline phase.</p><label className="cw-label" htmlFor="prototype-quantity">PLANNING QUANTITY</label><input id="prototype-quantity" value={session.prototype.quantity} maxLength={40} onChange={e=>update(s=>({...s,prototype:{...s.prototype,quantity:e.target.value}}))} placeholder="e.g. 100 pieces, or still exploring"/><label className="cw-label" htmlFor="prototype-budget">EXPLORATORY BUDGET</label><input id="prototype-budget" maxLength={80} value={session.prototype.budget} onChange={e=>update(s=>({...s,prototype:{...s.prototype,budget:e.target.value}}))} placeholder="Your target range, if you have one"/><label className="cw-label" htmlFor="prototype-purpose">WHAT SHOULD THIS DO FOR THE BRAND?</label><textarea id="prototype-purpose" maxLength={300} value={session.prototype.purpose} onChange={e=>update(s=>({...s,prototype:{...s.prototype,purpose:e.target.value}}))} rows={3} placeholder="A launch gift, partner thank-you, personal collectible…"/><p className="cw-micro">RM100–500 is an exploratory range, not a promised unit price. Design, prototyping and production require separate scope and quotes. No size is fixed online.</p><div className="cw-offline-steps"><span>Final design</span><ArrowRight size={14}/><span>Paid sample</span><ArrowRight size={14}/><span>Production quote</span></div><button className="cw-primary" onClick={downloadBrief}><Download size={16}/>Download prototype brief</button><p className="cw-micro">The destination is not set. This downloads a file only; it does not submit a request, take payment or place an order.</p></>}
      {dialog==='import'&&<>{shared?<><div className="cw-share-summary"><p><strong>Business:</strong> {shared.brief.business||'Reference study'}</p><p><strong>Story:</strong> {shared.brief.angle}</p><p><strong>Version:</strong> {shared.version.slice(0,12)}</p><p>{shared.selected.length} selected elements. {shared.worldId?'Includes access to generated images and their original stored briefs.':shared.sharedWorld?'Text-only shared direction, no image access.':'Uses an original reference world.'}</p></div><p>Your current local work stays unchanged until you choose to open this version. Download your current brief first if you want to keep both.</p><div className="cw-dialog-actions"><button className="cw-secondary" onClick={downloadCurrentBackup}>Save current brief</button><button className="cw-primary" onClick={()=>restore(shared,true)}>Create my own version <ArrowRight size={16}/></button></div></>:<p>This version link is invalid or too long. Your local work is unchanged.</p>}</>}
    </DialogContent></Dialog>
  </div>;
}
