import { useEffect, useRef, useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { ArrowRight, ArrowUp, Check, Circle, Copy, Download, ExternalLink, LoaderCircle, LockKeyhole, MousePointerClick, MoveHorizontal, Plus, RotateCcw, RotateCw, Share2, Sparkles, Star, X } from 'lucide-react';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { supabase } from '@/integrations/supabase/client';
import { studioBrand } from '@/lib/studio-brand';
import { normalizeCompanyWebsite } from '@/lib/company-website';
import { requestConcept, type WebsiteEvidence } from '@/lib/concept-api';
import { CANVAS_CONTRACT_VERSION, requestCanvasConcept, restoreCanvasConcept, supportsCanvasGeneration } from '@/lib/canvas-api';
import { worldReferences } from '@/lib/world-references';
import { branchCanvasSession, canvasContext, decodeCanvasShare, emptyCanvasSession, encodeCanvasShare, loadCanvasSession, makeCanvasBrief, physicalFingerprint, saveCanvasSession, saveCanvasSnapshot, loadCanvasSnapshot, worldFingerprint, type CanvasBrief, type CanvasSession } from '@/lib/canvas-session';
import ConversationBoard from './ConversationBoard';
import { interpretConversationEntry, appendDirectionNote } from '@/lib/conversation-input';
import './canvas-studio.css';
import './conversation-studio.css';

type GeneratedConcept = NonNullable<Awaited<ReturnType<typeof requestCanvasConcept>>['concept']>;
type Element = { id: string; label: string; description: string; kind: 'fact'|'proposal'; x?: number; y?: number; thumbnailImage?: string };
type SiteSettings = { title:string;logo:string;link:string };
const storyChoices = ['The world we bring together', 'A signature ritual', 'An unexpected side of us'];
const interactionChoices = ['Turn to reveal','A meaningful click','Slide to discover','Display only'];
const safeLink = (value: string) => value.startsWith('/') && !value.startsWith('//') || /^https?:\/\//i.test(value) ? value : '/';

export default function CanvasStudio() {
  const location = useLocation(); const navigate = useNavigate();
  const [session,setSession] = useState<CanvasSession>(emptyCanvasSession);
  const [saved,setSaved] = useState<CanvasSession|null>(loadCanvasSession);
  const [hasStarted,setHasStarted] = useState(false);
  const [world,setWorld] = useState<GeneratedConcept|null>(null);
  const [physical,setPhysical] = useState<GeneratedConcept|null>(null);
  const [activeElement,setActiveElement] = useState('');
  const [replacement,setReplacement] = useState('');
  const [note,setNote] = useState('');
  const [status,setStatus] = useState('');
  const [saveProblem,setSaveProblem] = useState(false);
  const [snapshotFailures,setSnapshotFailures] = useState<string[]>([]);
  const [busy,setBusy] = useState<''|'website'|'world'|'physical'|'restore'>('');
  const [ready,setReady] = useState<boolean|null>(null);
  const [readinessAttempt,setReadinessAttempt] = useState(0);
  const [evidence,setEvidence] = useState<WebsiteEvidence|null>(null);
  const [entry,setEntry] = useState('');
  const [question,setQuestion] = useState<'start'|'business'|'audience'|'ready'>('start');
  const [detailsOpen,setDetailsOpen] = useState(false);
  const [exampleId,setExampleId] = useState<CanvasSession['referenceId']|null>(null);
  const detailRef = useRef<HTMLDetailsElement>(null);
  const elementsRef = useRef<HTMLElement>(null);
  const [dialog,setDialog] = useState<'share'|'prototype'|'board'|'import'|null>(null);
  const [shared,setShared] = useState<CanvasSession|null>(null);
  const [shareLink,setShareLink] = useState('');
  const [shareStatus,setShareStatus] = useState('');
  const [includeGenerated,setIncludeGenerated] = useState(false);
  const [settings,setSettings] = useState<SiteSettings>({title:studioBrand.name,logo:'',link:'/'});
  const [imageErrors,setImageErrors] = useState<Record<string,boolean>>({});
  const controller = useRef<AbortController|null>(null);
  const run = useRef(0);
  const inFlight = useRef(false);
  const afterNavigation = useRef<null|{pathname:string;search:string;hash:string;requestEpoch:number;resume:()=>void}>(null);
  const reference = worldReferences.find(r=>r.id===session.referenceId) || worldReferences[0];
  const displayedWorld = world || session.sharedWorld || (session.worldId ? {title:'Your saved brand world',story:'Image metadata could not be restored. The original concept remains identified below; no reference artwork has been substituted.',worldElements:session.selected.map(id=>({id,label:id,description:'Saved element metadata unavailable. Restore this world to retrieve its description.',kind:'proposal' as const}))} : {title:reference.title,story:reference.story,worldElements:reference.elements});
  const elements: Element[] = displayedWorld.worldElements;
  const active = elements.find(e=>e.id===activeElement);
  const selectedCount = elements.filter(e=>session.selected.includes(e.id)).length;
  const worldIsCurrent = Boolean(world && (!session.worldFingerprint || session.worldFingerprint===worldFingerprint(session)));
  const physicalIsCurrent = Boolean(physical && session.physicalFingerprint===physicalFingerprint(session));
  const hasOwnWorld=Boolean(world||session.worldId||session.sharedWorld);
  const locked = Boolean(busy);
  const storageProblem = saveProblem || snapshotFailures.some(id=>id===session.worldId||id===session.physicalId);

  useEffect(()=>{let live=true; supabase.from('site_settings').select('key,value').then(({data})=>{
    if(!live||!data)return; const next={title:studioBrand.name,logo:'',link:'/'};
    data.forEach(s=>{ if(s.key==='site_title'&&s.value&&!['dioramini','briq2.0','briq','form.','brandkin','stive','the absurd marshmallow test'].includes(s.value.trim().toLowerCase()))next.title=s.value;
      if(s.key==='logo_url'&&/^https?:\/\//i.test(s.value||''))next.logo=s.value;
      if(s.key==='logo_link'&&s.value&&s.value!=='https://example.com')next.link=safeLink(s.value); }); setSettings(next);
  });return()=>{live=false;};},[]);
  useEffect(()=>{document.title=`${settings.title}｜异趣伙伴 — ${studioBrand.pageTitleSuffix}`;},[settings.title]);
  useEffect(()=>{const abort=new AbortController();setReady(null);supportsCanvasGeneration(abort.signal).then(value=>{if(!abort.signal.aborted)setReady(value);});return()=>abort.abort();},[readinessAttempt]);
  useEffect(()=>{if(hasStarted)setSaveProblem(!saveCanvasSession(session));},[session,hasStarted]);
  useEffect(()=>()=>{run.current++;controller.current?.abort();inFlight.current=false;afterNavigation.current=null;},[]);
  useEffect(()=>{run.current++;controller.current?.abort();controller.current=null;inFlight.current=false;setBusy('');
    if(location.hash.startsWith('#world=')){const candidate=decodeCanvasShare(location.hash);setShared(candidate);setDialog('import');setStatus(candidate?'':'This shared version is invalid or too long. Your local work has not changed.');}
    else {setDialog(null);setShared(null);setShareLink('');setShareStatus('');}
    const pending=afterNavigation.current;afterNavigation.current=null;if(pending&&pending.pathname===location.pathname&&pending.search===location.search&&pending.hash===location.hash&&pending.requestEpoch===run.current-1)pending.resume();
    // A URL change cancels pending work; incoming versions never silently overwrite local work.
  },[location.key,location.hash,location.pathname,location.search]);
  useEffect(()=>{setReplacement('');},[activeElement]);

  function persistSnapshot(concept:GeneratedConcept){const saved=saveCanvasSnapshot(concept);setSnapshotFailures(ids=>saved?ids.filter(id=>id!==concept.id):Array.from(new Set([...ids,concept.id])));}
  function update(change: Partial<CanvasSession> | ((previous:CanvasSession)=>CanvasSession)) {setHasStarted(true);setSession(s=>typeof change==='function'?change(s):{...s,...change});}
  function brief(field:keyof CanvasBrief,value:string) {update(s=>({...s,brief:{...s.brief,[field]:value}}));}
  function cancel() {run.current++;controller.current?.abort();controller.current=null;inFlight.current=false;afterNavigation.current=null;setBusy('');setStatus('Cancelled. Your direction is still here. A provider request already started may still use credits.');}
  function startRequest(kind:typeof busy) {inFlight.current=true;controller.current?.abort();const abort=new AbortController();controller.current=abort;const token=++run.current;setBusy(kind);setStatus('');return{abort,token};}
  const isLive=(token:number,abort:AbortController)=>run.current===token&&!abort.signal.aborted;
  async function readWebsite() {
    if(inFlight.current)return;
    const url=normalizeCompanyWebsite(session.brief.website);if(!url){setStatus('Enter a public company website, such as yourbrand.com.');return;}
    const {abort,token}=startRequest('website');const timer=window.setTimeout(()=>abort.abort(),35000);
    try{const result=await requestConcept({brand:url,context:'',edition:'icon',format:'miniature',inspectWebsite:true},abort.signal);if(!isLive(token,abort))return;
      if(result.website){setEvidence(result.website);brief('website',url);setStatus('Website text is ready to review. Choose what belongs in your story.');}
      else setStatus('This website couldn’t be read. Add a short business description to continue.');
    }catch(error){if(isLive(token,abort))setStatus(error instanceof Error?error.message:'Could not read this website. You can describe your business instead.');}
    finally{clearTimeout(timer);if(run.current===token){inFlight.current=false;controller.current=null;setBusy('');if(abort.signal.aborted)setStatus('Website reading timed out. Your answers are intact; try again or describe the business.');}}
  }
  async function generate(stage:'world'|'physical') {
    if(inFlight.current)return;
    if(stage==='world'&&!session.brief.business.trim()){setStatus('Tell us a little about the business before generating your world.');setDetailsOpen(true);return;}
    if(stage==='physical'&&(!world||!worldIsCurrent||!selectedCount||!session.hero)){setStatus('Generate your brand world, then select its elements and a main character first.');return;}
    const url=session.brief.website.trim()?normalizeCompanyWebsite(session.brief.website):'no-website';if(!url){setStatus('Check the website address, or leave it empty and use your description.');return;}
    const notes=appendDirectionNote(session.brief.notes,note);if(notes===null){setStatus('This direction is full. Open Edit details to shorten the notes before generating.');return;}
    const snapshot=note.trim()?{...session,brief:{...session.brief,notes}}:session;if(note.trim()){update(snapshot);setNote('');}const {abort,token}=startRequest(stage);const timer=window.setTimeout(()=>abort.abort(),220000);
    try{const result=await requestCanvasConcept({contractVersion:CANVAS_CONTRACT_VERSION,stage,brand:url,context:canvasContext(snapshot.brief),...(stage==='physical'?{sourceWorldId:world.id,selectedElementIds:snapshot.selected,heroElementId:snapshot.hero,replacements:snapshot.replacements}:{})},abort.signal);
      if(!isLive(token,abort))return;if(!result.concept)throw new Error('The generator needs a more specific business description. Your direction is still here.');
      const concept=result.concept;setImageErrors({});persistSnapshot(concept);
      if(stage==='world'){setWorld(concept);setPhysical(null);setActiveElement('');update(s=>({...s,worldId:concept.id,physicalId:'',sharedWorld:undefined,selected:concept.worldElements.map(e=>e.id),hero:concept.worldElements[0]?.id||'',replacements:[],worldFingerprint:worldFingerprint(snapshot),physicalFingerprint:''}));setQuestion('ready');setStatus('Your world is ready. Next, turn it into a physical concept.');}
      else{setPhysical(concept);update({physicalId:concept.id,physicalFingerprint:physicalFingerprint(snapshot)});setStatus('Your physical concept is ready, shaped by this world and your selected elements.');}
    }catch(error){if(isLive(token,abort))setStatus(error instanceof Error?error.message:'Generation didn’t finish. Your direction is still here.');}
    finally{clearTimeout(timer);if(run.current===token){inFlight.current=false;controller.current=null;setBusy('');if(abort.signal.aborted)setStatus('Generation took too long. Your direction is intact. Retrying an identical completed request can restore its cached result.');}}
  }
  async function restore(next:CanvasSession,branch=false) {
    if(branch||next.version!==session.version)setNote('');
    const local=branch?branchCanvasSession(next):next;const cachedWorld=loadCanvasSnapshot(local.worldId);const cachedPhysical=loadCanvasSnapshot(local.physicalId);setSaved(null);setQuestion(local.brief.business?'ready':local.brief.website?'business':'start');setEntry('');setWorld(cachedWorld?.stage==='world'?cachedWorld:null);setPhysical(cachedPhysical?.stage==='physical'&&cachedPhysical.sourceWorldId===local.worldId?cachedPhysical:null);setActiveElement('');setEvidence(null);setHasStarted(true);setSession(local);setDialog(null);setShared(null);
    if(!local.worldId){setStatus(branch?'This is your own editable version. Changes stay on this device.':'Your saved direction is open.');if(location.hash)navigate(location.pathname,{replace:true});return;}
    const restoreImages=async()=>{const {abort,token}=startRequest('restore');const timer=window.setTimeout(()=>abort.abort(),35000);
      try {const result=await restoreCanvasConcept(local.worldId,abort.signal);if(!isLive(token,abort))return;if(!result.concept||result.concept.stage!=='world')throw new Error('The saved world could not be opened.');setWorld(result.concept);persistSnapshot(result.concept);
        const validIds=new Set(result.concept.worldElements.map(e=>e.id));const chosen=local.selected.filter(id=>validIds.has(id));const safeSession={...local,selected:chosen,hero:chosen.includes(local.hero)?local.hero:chosen[0]||'',replacements:local.replacements.filter(r=>chosen.includes(r.id))};
        // Imported links intentionally omit fingerprints. Reading the stored source gives the comparison basis.
        const restoredBrief={...safeSession.brief,...Object.fromEntries(Object.entries(result.concept.context||{}).filter(([key])=>key in safeSession.brief))};
        setSession(s=>({...safeSession,prototype:s.prototype,worldFingerprint:local.worldFingerprint||worldFingerprint({...safeSession,brief:restoredBrief})}));
        if(local.physicalId){const item=await restoreCanvasConcept(local.physicalId,abort.signal);if(!isLive(token,abort))return;if(item.concept?.stage==='physical'&&item.concept.sourceWorldId===local.worldId){setPhysical(item.concept);persistSnapshot(item.concept);if(!local.physicalFingerprint)setStatus('Version opened. Review the physical image against this branch’s current selections before using it.');}else setStatus('World restored. The saved physical concept is unavailable.');}
        else setStatus(branch?'Your own version is open. Changes won’t update anyone else’s copy.':'World restored. Image access refreshed without generation.');
      }catch(error){if(isLive(token,abort))setStatus(error instanceof Error?error.message:'Saved image couldn’t be restored. Your written direction is still here.');}
      finally{clearTimeout(timer);if(run.current===token){inFlight.current=false;controller.current=null;setBusy('');if(abort.signal.aborted)setStatus('Image restoration timed out. Your written direction is intact. Try restoring images again.');}}
    };
    if(location.hash){afterNavigation.current={pathname:location.pathname,search:'',hash:'',requestEpoch:run.current,resume:()=>{void restoreImages();}};navigate(location.pathname,{replace:true});}
    else void restoreImages();
  }
  function openReference(id:CanvasSession['referenceId']) { setExampleId(id);setDialog('board'); }
  function toggleElement(id:string) {update(s=>{const included=s.selected.includes(id);const selected=included?s.selected.filter(x=>x!==id):[...s.selected,id];return{...s,selected,hero:included&&s.hero===id?selected[0]||'':s.hero||id,replacements:included?s.replacements.filter(r=>r.id!==id):s.replacements};});}
  function applyReplacement() {if(!active||!replacement.trim())return;const label=replacement.trim();update(s=>({...s,selected:s.selected.includes(active.id)?s.selected:[...s.selected,active.id],hero:s.hero||active.id,replacements:[...s.replacements.filter(r=>r.id!==active.id),{id:active.id,label,description:`Proposed replacement for ${active.label}: ${label}`}]}));setReplacement('');setStatus('Replacement saved for your next physical concept. The brand-world illustration stays unchanged.');}
  function applyNote(){if(!note.trim()||locked)return;const next=appendDirectionNote(session.brief.notes,note);if(next===null){setStatus('This direction is full. Open Edit details to shorten the notes before adding more.');return;}brief('notes',next);setNote('');setStatus('Added to your direction. Generate again when you’re ready to apply it.');}
  function submitEntry(){if(locked||!entry.trim())return;if(question==='audience'){if(entry.length>120){setStatus('Keep the audience answer under 120 characters, or add the detail later.');return;}brief('audience',entry);setQuestion('ready');setEntry('');setStatus('');return;}const parsed=interpretConversationEntry(entry);if(parsed.kind==='error'){setStatus(parsed.message);return;}if(parsed.kind==='website'){brief('website',parsed.value);setQuestion('business');}else{brief('business',parsed.value);setQuestion('audience');}setEntry('');setStatus('');}
  function openDetails(target:'story'|'elements'='story'){setDetailsOpen(true);window.setTimeout(()=>{const section=target==='elements'?elementsRef.current:detailRef.current;section?.scrollIntoView?.({behavior:window.matchMedia?.('(prefers-reduced-motion: reduce)')?.matches?'auto':'smooth',block:'start'});if(target==='elements')section?.focus({preventScroll:true});},0);}
  function downloadSessionBrief(target:CanvasSession){const targetReference=worldReferences.find(r=>r.id===target.referenceId)||worldReferences[0];const candidateWorld=target===session?world:loadCanvasSnapshot(target.worldId);const savedWorld=candidateWorld?.stage==='world'?candidateWorld:null;const targetWorld=savedWorld||target.sharedWorld||(target.worldId?{title:`Saved world ${target.worldId}`,story:'Saved generated world metadata is unavailable. Reopen this world to restore the complete narrative. No reference study is substituted.',worldElements:target.selected.map(id=>({id,label:id,description:'Description unavailable on this device; original element ID retained.',kind:'proposal'}))}:{title:targetReference.title,story:targetReference.story,worldElements:targetReference.elements});const candidatePhysical=target===session?physical:loadCanvasSnapshot(target.physicalId);const savedPhysical=candidatePhysical?.stage==='physical'&&candidatePhysical.sourceWorldId===target.worldId?candidatePhysical:null;const content=makeCanvasBrief(target,targetWorld,savedPhysical?.title);const url=URL.createObjectURL(new Blob([content],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`OFFKIN-${target.version.slice(0,8)}-prototype-brief.txt`;a.click();window.setTimeout(()=>URL.revokeObjectURL(url),1000);setStatus('Brief downloaded. It hasn’t been sent to anyone.');}
  function downloadBrief(){downloadSessionBrief(session);}
  function downloadCurrentBackup(){downloadSessionBrief(!hasStarted&&saved?saved:session);}
  function openShare(){setShareLink('');setShareStatus('');setIncludeGenerated(false);setDialog('share');}
  async function createLink(){try{const link=new URL(location.pathname,window.location.origin);const sharedWorld=hasOwnWorld?{title:displayedWorld.title,story:displayedWorld.story,worldElements:elements.filter(e=>session.selected.includes(e.id)).map(e=>{const r=session.replacements.find(r=>r.id===e.id);return{id:e.id,label:r?.label||e.label,description:r?.description||e.description,kind:r?'proposal' as const:e.kind};})}:undefined;link.hash=encodeCanvasShare(session,{includeGenerated,sharedWorld});const value=link.toString();setShareLink(value);try{await navigator.clipboard.writeText(value);setShareStatus('Link copied. Each person opens a separate editable version.');}catch{setShareStatus('Select and copy the link below.');}}catch(error){setShareStatus(error instanceof Error?error.message:'This link couldn’t be created. Download the brief instead.');}}
  function fresh(){controller.current?.abort();controller.current=null;inFlight.current=false;afterNavigation.current=null;run.current++;setBusy('');setSaved(null);setEntry('');setQuestion('start');setDetailsOpen(false);setExampleId(null);setNote('');setSnapshotFailures([]);setHasStarted(true);setWorld(null);setPhysical(null);setSession(emptyCanvasSession());setEvidence(null);setStatus('A fresh local direction is ready.');setActiveElement('');navigate(location.pathname,{replace:true});}
  const StoryPanel= <>
    <label className="cw-label" htmlFor="canvas-website">YOUR WEBSITE <span>optional</span></label>
    <div className="cw-url-row"><input id="canvas-website" value={session.brief.website} onChange={e=>brief('website',e.target.value)} placeholder="yourbrand.com" maxLength={300} disabled={locked}/><button aria-label="Read public website" onClick={readWebsite} disabled={locked||!session.brief.website.trim()}><ArrowRight size={18}/></button></div>
    <p className="cw-micro">Read-only lookup. No image is generated.</p>
    {evidence&&<details className="cw-evidence"><summary>Review website text <ExternalLink size={12}/></summary><a href={evidence.url} target="_blank" rel="noopener noreferrer">{evidence.title||evidence.url}</a><p>{evidence.excerpt}</p><button onClick={()=>{brief('business',evidence.excerpt.slice(0,1000));setQuestion('audience');setStatus('Website excerpt copied as a starting point. Edit it to describe what matters.');}} disabled={locked}>Use excerpt as a starting point</button></details>}
    <label className="cw-label" htmlFor="canvas-business">WHAT SHOULD WE KNOW?</label><textarea id="canvas-business" maxLength={1000} rows={3} value={session.brief.business} placeholder="What makes your business yours?" onChange={e=>brief('business',e.target.value)} disabled={locked}/>
    <label className="cw-label" htmlFor="canvas-angle">STORY DIRECTION</label><input id="canvas-angle" value={session.brief.angle} onChange={e=>brief('angle',e.target.value)} maxLength={120} disabled={locked}/>
    <div className="oc-chips">{storyChoices.map(choice=><button key={choice} aria-pressed={session.brief.angle===choice} onClick={()=>brief('angle',choice)} disabled={locked}>{choice}</button>)}</div>
    <label className="cw-label" htmlFor="canvas-cues">LOGO, COLOURS, PEOPLE, PLACES</label><textarea id="canvas-cues" value={session.brief.brandIdentifiers} onChange={e=>brief('brandIdentifiers',e.target.value)} maxLength={500} rows={3} disabled={locked} placeholder="Text references for the next generation"/>
    <label className="cw-label" htmlFor="canvas-words">EXACT WORDING</label><textarea id="canvas-words" value={session.brief.exactWording} onChange={e=>brief('exactWording',e.target.value)} maxLength={200} rows={2} disabled={locked} placeholder="Preserved verbatim for proofing"/>
    <label className="cw-label" htmlFor="canvas-audience">WHO IS IT FOR?</label><input id="canvas-audience" value={session.brief.audience} onChange={e=>brief('audience',e.target.value)} maxLength={120} disabled={locked}/>
    <label className="cw-label" htmlFor="canvas-style">VISUAL ENERGY</label><input id="canvas-style" value={session.brief.style} onChange={e=>brief('style',e.target.value)} maxLength={120} disabled={locked}/>
    <label className="cw-label" htmlFor="canvas-notes">DIRECTION NOTES</label><textarea id="canvas-notes" value={session.brief.notes} onChange={e=>brief('notes',e.target.value)} maxLength={1000} rows={3} disabled={locked}/>
  </>;
  const InteractionChoices=<fieldset className="cw-interactions" disabled={locked}><legend>A MEANINGFUL LITTLE ACTION</legend>{interactionChoices.map((v,i)=><button aria-pressed={session.brief.interaction===v} onClick={()=>brief('interaction',v)} key={v}><span aria-hidden="true">{i===0?<RotateCw size={19}/>:i===1?<MousePointerClick size={19}/>:i===2?<MoveHorizontal size={19}/>:<Circle size={19}/>}</span>{v}{session.brief.interaction===v&&<Check size={13}/>}</button>)}</fieldset>;
  const WorldAction=<button className="cw-primary" onClick={()=>generate('world')} disabled={locked||ready!==true}><Sparkles size={16}/>{busy==='world'?'Creating your world…':world?'Regenerate brand world':'Generate my brand world'}<ArrowRight size={16}/></button>;
  const PhysicalAction=<button className="cw-primary" onClick={()=>generate('physical')} disabled={locked||ready!==true||!worldIsCurrent||!selectedCount||!session.hero}><Sparkles size={16}/>{busy==='physical'?'Creating physical concept…':physical?'Regenerate physical concept':'Generate physical concept'}<ArrowRight size={16}/></button>;
  const ElementEditor=active&&<div className="cw-element-editor"><div className="cw-element-heading"><span className="cw-step">{String(elements.indexOf(active)+1).padStart(2,'0')}</span><div><p>{active.kind==='fact'?'SOURCE-BASED ELEMENT':'PROPOSED STORY ELEMENT'}</p><h3>{session.replacements.find(r=>r.id===active.id)?.label||active.label}</h3></div><button className="cw-icon-button" onClick={()=>setActiveElement('')} aria-label="Close element details"><X size={17}/></button></div><p>{active.description}</p><div className="cw-element-actions"><button onClick={()=>toggleElement(active.id)} disabled={locked}>{session.selected.includes(active.id)?<Check size={14}/>:<Plus size={14}/>} {session.selected.includes(active.id)?'Included · remove':'Include element'}</button><button aria-pressed={session.hero===active.id} onClick={()=>update(s=>({...s,hero:active.id,selected:s.selected.includes(active.id)?s.selected:[...s.selected,active.id]}))} disabled={locked}><Star size={14}/>{session.hero===active.id?'Main character':'Make main character'}</button></div><label className="cw-label" htmlFor="replace-element">OR REPLACE WITH ANOTHER IDEA</label><div className="cw-url-row"><input id="replace-element" maxLength={80} placeholder="e.g. our neighbourhood bakery" value={replacement} onChange={e=>setReplacement(e.target.value)} disabled={locked}/><button onClick={applyReplacement} disabled={locked||!replacement.trim()} aria-label="Apply element replacement"><ArrowRight size={16}/></button></div><p className="cw-micro">Changes update the brief for your next physical concept. They do not edit pixels in this illustration.</p></div>;
  const hasConversation=Boolean(session.brief.business||session.brief.website||hasOwnWorld);
  const previewReference=worldReferences.find(item=>item.id===exampleId)||reference;
  return <div className={`cw-app oc-app ${hasConversation?'oc-started':''}`}><a className="cw-skip" href="#conversation-main">Skip to conversation</a>
    <header className="cw-header"><a className="cw-logo" href={settings.link} aria-label={`${settings.title} home`}>{settings.logo?<img src={settings.logo} alt={settings.title}/>:<><span className="cw-logo-mark"><i/><i/></span><span>{settings.title}<small lang="zh-Hans">异趣伙伴</small></span></>}</a><span className="oc-header-note">ART × TECHNOLOGY × COMMERCE</span>{hasConversation&&<button className="oc-text-button" onClick={fresh} disabled={locked}>New conversation <Plus size={14}/></button>}</header>
    <main id="conversation-main">
      <section className="oc-intro"><h1>Your business DNA.<br/>{' '}<span>Made collectible.</span></h1>{!hasConversation&&<p>Tell us what makes your brand yours.</p>}</section>
      {saved&&!hasStarted&&<div className="cw-resume oc-resume"><span><RotateCcw size={16}/>A direction is saved on this device.</span><button onClick={()=>restore(saved)}>Resume my direction</button><button onClick={fresh}>Start fresh</button></div>}
      {!hasOwnWorld&&<section className="oc-conversation" aria-label="Brand conversation">
        {session.brief.website&&<p className="oc-answer">{session.brief.website}</p>}
        {session.brief.business&&<p className="oc-answer">{session.brief.business}</p>}
        {question==='business'&&!session.brief.business&&<p className="oc-question">What makes this brand special?</p>}
        {question==='audience'&&session.brief.business&&<><p className="oc-question">Who would you like to make this for?</p><div className="oc-chips">{['Clients & partners','Our team','A community','Personal collection'].map(value=><button key={value} onClick={()=>{brief('audience',value);setQuestion('ready');setEntry('');}} disabled={locked}>{value}</button>)}<button onClick={()=>{setQuestion('ready');setEntry('');}} disabled={locked}>You choose</button></div></>}
        {(!session.brief.business||question==='audience')&&<form className="oc-composer" onSubmit={event=>{event.preventDefault();submitEntry();}}><label className="oc-sr-only" htmlFor="conversation-entry">{question==='audience'?'Your audience':'Your brand, website or story'}</label><textarea id="conversation-entry" value={entry} onChange={e=>setEntry(e.target.value)} disabled={locked} rows={2} maxLength={question==='audience'?120:1000} placeholder={question==='audience'?'Or tell us in your own words…':question==='business'?'A sentence or two is enough…':'A brand, a website, or a story…'} onKeyDown={event=>{if(event.key==='Enter'&&!event.shiftKey&&!event.nativeEvent.isComposing){event.preventDefault();submitEntry();}}}/><button type="submit" disabled={locked||!entry.trim()} aria-label="Continue conversation"><ArrowUp size={20}/></button></form>}
        {session.brief.business&&question!=='audience'&&<div className="oc-ready"><p className="oc-question">Let’s make a world for {session.brief.audience.toLowerCase()}.</p>{WorldAction}<p className="oc-generation-note">One AI illustration · brief sent on Generate · credits may apply.</p></div>}
        {question==='business'&&!session.brief.business&&<button className="oc-text-button" onClick={()=>{openDetails();void readWebsite();}} disabled={locked}>Read this public website instead <ArrowRight size={13}/></button>}
        {!hasConversation&&<p className="oc-entry-note"><LockKeyhole size={11}/>Private on this device until you choose to generate or share</p>}
      </section>}
      {!hasConversation&&<section className="oc-examples" aria-label="Example concept boards"><span>Or take a look</span><div>{worldReferences.map(item=><button key={item.id} onClick={()=>openReference(item.id)}><img src={item.boardImage} alt="" loading="lazy"/><span>{item.name} <ArrowRight size={13}/></span></button>)}</div><p>Independent concept studies</p></section>}
      {hasOwnWorld&&<>
        <div className="oc-result-toolbar"><span>Your concept</span><div><button onClick={downloadBrief} aria-label="Download current brief"><Download size={15}/>Save brief</button><button onClick={openShare} disabled={locked}><Share2 size={15}/>Share a version</button></div></div>
        <ConversationBoard world={world} physical={physical} session={session} hasOwnWorld={hasOwnWorld} reference={reference} imageErrors={imageErrors} onImageError={src=>setImageErrors(values=>({...values,[src]:true}))} onRetryImage={src=>setImageErrors(values=>({...values,[src]:false}))} onEnlarge={()=>{setExampleId(null);setDialog('board');}} onEditElements={()=>openDetails('elements')} worldIsCurrent={worldIsCurrent} physicalIsCurrent={physicalIsCurrent}/>
        <section className="oc-refine" aria-label="Refine your concept">
          {world&&!worldIsCurrent&&<p className="cw-pending">Your story has changed. Generate the world again when you’re ready; this image stays as the previous version.</p>}
          {physical&&!physicalIsCurrent&&<p className="cw-pending">Your selections have changed. This preview is the previous version; generate again to apply them.</p>}
          <p className="oc-question">{!physical?'Shall we make it tangible?':'What would you change?'}</p>
          {worldIsCurrent&&!physical&&<p className="oc-subtle">The world’s story elements are ready. You can keep them all or edit the details.</p>}
          <form className="oc-composer" onSubmit={event=>{event.preventDefault();applyNote();}}><label className="oc-sr-only" htmlFor="canvas-note">Tell the next image where to go.</label><textarea id="canvas-note" rows={2} maxLength={1000} value={note} onChange={e=>setNote(e.target.value)} placeholder="More playful. Keep the yellow road. Add a neighbourhood café…" disabled={locked}/><button type="submit" aria-label="Save direction note" disabled={locked||!note.trim()}><ArrowUp size={20}/></button></form>
          {session.brief.notes&&<p className="oc-answer oc-note-answer">{session.brief.notes}</p>}
          <div className="oc-refine-action">{worldIsCurrent?PhysicalAction:WorldAction}<p className="oc-generation-note">{worldIsCurrent?'Creates one physical concept image.':'Creates a new brand-world illustration.'} Credits may apply.</p></div>
        </section>
      </>}
      {(hasConversation||hasStarted)&&<div className="oc-direction-tools"><span className="cw-private"><LockKeyhole size={12}/>{storageProblem?'Not saved on this device':'Saved on this device'}</span>{!hasOwnWorld&&<><button onClick={downloadBrief} aria-label="Download current brief"><Download size={14}/>Save brief</button><button onClick={openShare} disabled={locked}><Share2 size={14}/>Share a version</button></>}<button onClick={()=>setDialog('prototype')}>Plan a real prototype <ArrowRight size={14}/></button></div>}
      <details className="oc-edit-details" ref={detailRef} open={detailsOpen} onToggle={e=>setDetailsOpen(e.currentTarget.open)}><summary>Edit details <Plus size={14}/></summary><p className="oc-detail-intro">This guided conversation saves your answers and passes them to AI only when you generate. Website reads are separate. Changes to the brief do not edit existing image pixels.</p><div className="oc-detail-grid"><section aria-label="Business story choices">{StoryPanel}<div className="oc-advanced-action">{(!session.brief.business||question==='audience'||hasOwnWorld&&worldIsCurrent)&&WorldAction}</div></section><section aria-label="Concept details" tabIndex={-1} ref={elementsRef}><h2>Story elements</h2><p className="oc-subtle">{selectedCount} selected · These choices shape the next physical concept.</p><div className="cw-element-tray" aria-label="World story elements">{elements.map((element,i)=><button key={element.id} className={`cw-element-card ${session.selected.includes(element.id)?'selected':''} ${activeElement===element.id?'active':''}`} onClick={()=>setActiveElement(element.id)} aria-pressed={activeElement===element.id} disabled={locked}><div className="cw-element-art">{!hasOwnWorld&&element.thumbnailImage?<img src={element.thumbnailImage} alt=""/>:<span>{String(i+1).padStart(2,'0')}</span>}<span className="cw-inclusion">{session.selected.includes(element.id)?<Check size={10}/>:<Plus size={10}/>}</span>{session.hero===element.id&&<span className="cw-hero-tag"><Star size={10} fill="currentColor"/>HERO</span>}</div><span className="cw-element-name">{session.replacements.find(r=>r.id===element.id)?.label||element.label}</span></button>)}</div>{ElementEditor}{InteractionChoices}{!hasOwnWorld&&PhysicalAction}<p className="cw-micro">Selections and replacements update the next physical brief, not pixels in the world illustration.</p></section></div></details>
      {ready!==true&&<div className="cw-readiness oc-service-status"><span>{ready===null?'Checking generator…':'Image generation is not connected to this canvas yet. Your direction can still be saved and shared.'}</span>{ready===false&&<button onClick={()=>setReadinessAttempt(v=>v+1)}>Check again</button>}</div>}
      {(status||busy||storageProblem||Object.values(imageErrors).some(Boolean))&&<div className="cw-status oc-status" role="status" aria-live="polite">{busy&&<LoaderCircle className="cw-spin" size={16}/>}<span>{busy==='website'?'Reading the public website…':busy==='restore'?'Restoring private image links…':busy==='physical'?'Creating your physical concept…':busy==='world'?'Generating your brand world…':status}{Object.values(imageErrors).some(Boolean)&&' An image could not load. Restore images to refresh access.'}{storageProblem&&' Device storage is unavailable. Download your brief before leaving.'}</span>{busy&&<button onClick={cancel} aria-label={busy==='world'?'Cancel generation':'Cancel'}>Cancel</button>}{!busy&&session.worldId&&(!world?.image||Object.values(imageErrors).some(Boolean))&&<button onClick={()=>{setImageErrors({});restore(session);}}>Restore images again</button>}</div>}
    </main>
    <footer className="oc-footer"><span>OFFKIN · 异趣伙伴</span><button onClick={()=>setDialog('prototype')}>From idea to object <ArrowRight size={13}/></button></footer>
    <Dialog open={dialog!==null} onOpenChange={open=>{if(!open){setDialog(null);if(dialog==='import')navigate(location.pathname,{replace:true});}}}><DialogContent className={`cw-dialog ${dialog==='board'?'cw-board-dialog':''}`}><DialogHeader><DialogTitle>{dialog==='share'?'Share this version':dialog==='prototype'?'From world to working prototype':dialog==='import'?'Open a shared direction':exampleId?'The complete original concept board':world?'Your illustrated brand world':'The complete original concept board'}</DialogTitle><DialogDescription>{dialog==='share'?'Review exactly what will be included before creating a link.':dialog==='prototype'?'A planning brief for an offline paid design and sample conversation.':dialog==='import'?'Review this snapshot before creating your own editable branch.':world&&!exampleId?'An AI-assisted illustrated concept, not a production specification.':'Original reference artwork. Independent, uncommissioned and not production-validated.'}</DialogDescription></DialogHeader>
      {dialog==='board'&&<>{!exampleId&&hasOwnWorld&&!world?.image?<p>Restore this world’s image to open the full illustration.</p>:<img src={!exampleId&&world?world.image:previewReference.boardImage} alt={!exampleId&&world?`${world.title}, full illustration`:`${previewReference.name}, complete original concept board`}/>} {(exampleId||!hasOwnWorld)&&<p className="cw-micro">The original board may contain speculative mechanisms, dimensional assumptions or other unsupported claims. It is a visual reference. Final scope, rights and construction need review.</p>}</>}
      {dialog==='share'&&<><div className="cw-share-summary"><p><strong>Included:</strong> website, business description, story choices, brand cues, exact wording, direction notes, selected elements, replacements and prototype planning fields.</p><p><strong>Default sharing:</strong> current direction text only. Generated image IDs and original generation briefs are excluded.</p><p><strong>Collaboration:</strong> each coworker creates a separate version. There is no live shared editing or automatic sync.</p></div>{session.worldId&&<div className="cw-image-sharing"><label><input type="checkbox" checked={includeGenerated} disabled={!world?.image||Boolean(session.physicalId&&!physical?.image)} onChange={e=>{setIncludeGenerated(e.target.checked);setShareLink('');setShareStatus('');}}/>Include generated images and their original briefs</label><p className="cw-micro">Anyone with the link can open the original stored business text, wording, design and story metadata for these images, including details you later removed. {(!world?.image||Boolean(session.physicalId&&!physical?.image))&&'Restore all images before choosing this option.'}</p>{includeGenerated&&<details className="cw-details" open><summary>Review original generated data shared through image access</summary><pre className="cw-share-review">{JSON.stringify([world,physical].filter(Boolean).map(({image,...metadata})=>metadata),null,2)}</pre></details>}</div>}<details className="cw-details" open><summary>Review the data in this link</summary><pre className="cw-share-review">{makeCanvasBrief(session,displayedWorld,includeGenerated?physical?.title:undefined)}</pre></details><p className="cw-micro">The link itself contains the text. Anyone you give it to can read and forward it. Include only information you’re comfortable sharing.</p><div className="cw-dialog-actions"><button className="cw-secondary" onClick={()=>setDialog(null)}>Cancel</button><button className="cw-primary" onClick={createLink}><Copy size={15}/>Create & copy this version link</button></div>{shareLink&&<label className="cw-label">VERSION LINK<input value={shareLink} readOnly onFocus={e=>e.target.select()}/></label>}<p role="status">{shareStatus}</p></>}
      {dialog==='prototype'&&<><p className="cw-small-copy">Keep the creative world rich. Final design, simplifying it for manufacture and testing one or two meaningful motions happen in the paid offline phase.</p><label className="cw-label" htmlFor="prototype-quantity">PLANNING QUANTITY</label><input id="prototype-quantity" value={session.prototype.quantity} maxLength={40} onChange={e=>update(s=>({...s,prototype:{...s.prototype,quantity:e.target.value}}))} placeholder="e.g. 100 pieces, or still exploring"/><label className="cw-label" htmlFor="prototype-budget">EXPLORATORY BUDGET</label><input id="prototype-budget" maxLength={80} value={session.prototype.budget} onChange={e=>update(s=>({...s,prototype:{...s.prototype,budget:e.target.value}}))} placeholder="Your target range, if you have one"/><label className="cw-label" htmlFor="prototype-purpose">WHAT SHOULD THIS DO FOR THE BRAND?</label><textarea id="prototype-purpose" maxLength={300} value={session.prototype.purpose} onChange={e=>update(s=>({...s,prototype:{...s.prototype,purpose:e.target.value}}))} rows={3} placeholder="A launch gift, partner thank-you, personal collectible…"/><p className="cw-micro">RM100–500 is an exploratory range, not a promised unit price. Design, prototyping and production require separate scope and quotes. No size is fixed online.</p><div className="cw-offline-steps"><span>Final design</span><ArrowRight size={14}/><span>Paid sample</span><ArrowRight size={14}/><span>Production quote</span></div><button className="cw-primary" onClick={downloadBrief}><Download size={16}/>Download prototype brief</button><p className="cw-micro">The destination is not set. This downloads a file only; it does not submit a request, take payment or place an order.</p></>}
      {dialog==='import'&&<>{shared?<><div className="cw-share-summary"><p><strong>Business:</strong> {shared.brief.business||'Reference study'}</p><p><strong>Story:</strong> {shared.brief.angle}</p><p><strong>Version:</strong> {shared.version.slice(0,12)}</p><p>{shared.selected.length} selected elements. {shared.worldId?'Includes access to generated images and their original stored briefs.':shared.sharedWorld?'Text-only shared direction, no image access.':'Uses an original reference world.'}</p></div><p>Your current local work stays unchanged until you choose to open this version. Download your current brief first if you want to keep both.</p><div className="cw-dialog-actions"><button className="cw-secondary" onClick={downloadCurrentBackup}>Save current brief</button><button className="cw-primary" onClick={()=>restore(shared,true)}>Create my own version <ArrowRight size={16}/></button></div></>:<p>This version link is invalid or too long. Your local work is unchanged.</p>}</>}
    </DialogContent></Dialog>
  </div>;
}
