import { useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, Download, LockKeyhole } from 'lucide-react';
import { Button } from './ui/button';
import { buildPairedArtifacts, editorialWarnings, freezePairedDesign, refinePairedDesign, STORY_LENSES, REFINEMENT_TARGETS, type FrozenPairedDesign, type PairedArtifact, type PairedDesignInput, type PairedProductPlan, type RefinementTarget, type StoryLens } from '../../supabase/functions/generate-concept/paired-design';
import './paired-concept-review.css';

const labels: Record<StoryLens,string>={'signature-product':'Signature product / service','signature-action':'Signature action','brand-belief':'Brand belief'};
const targets: Record<RefinementTarget,string>={'silhouette':'Silhouette','brand-symbolism':'Brand symbolism','mechanism':'Mechanism','story-card-composition':'Story-card composition'};
const blankPlan: PairedProductPlan={status:'unverified-concept',object:'',silhouette:'',components:[],purchasedParts:[],mechanic:null,process:'undecided',caveats:['Concept only. Print orientation, supports, materials, fit, tolerances and safety require CAD and physical prototype review.']};
/** Explicit offline review branch. No API imports, saved capability IDs or automatic generation. */
export default function PairedConceptReview() {
  const [step,setStep]=useState(0);const [brand,setBrand]=useState('');const [quote,setQuote]=useState('');const [url,setUrl]=useState('');const [confirmed,setConfirmed]=useState(false);
  const [lens,setLens]=useState<StoryLens>('signature-product');const [plan,setPlan]=useState(JSON.stringify(blankPlan,null,2));const [symbolism,setSymbolism]=useState('');const [headline,setHeadline]=useState('');const [narrative,setNarrative]=useState('');const [exactText,setExactText]=useState('');
  const [frozen,setFrozen]=useState<FrozenPairedDesign|null>(null);const [artifacts,setArtifacts]=useState<readonly PairedArtifact[]>([]);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const busyRef=useRef(false);
  const [target,setTarget]=useState<RefinementTarget>('story-card-composition');const [replacement,setReplacement]=useState('3');const [approve,setApprove]=useState(false);
  async function lock() {
    if(busyRef.current)return;busyRef.current=true;setBusy(true);setError('');
    try {
      const input: PairedDesignInput={brand,exactText,evidence:[{id:'confirmed-story',kind:url?'public-source':'owner-statement',text:quote,sourceUrl:url,sourceTitle:url?'User-confirmed source excerpt':'Owner statement — no website research implied'}],evidenceConfirmed:confirmed,lens,truth:{evidenceId:'confirmed-story',quote},symbolism,plan:JSON.parse(plan),card:{headline,narrative,frames:2},localizedBrandAccents:[]};
      const next=await freezePairedDesign(input);const outputs=await buildPairedArtifacts(next);setFrozen(next);setArtifacts(outputs);setStep(3);
    } catch(e){setError(e instanceof Error?e.message:'Check the structured design fields.');} finally{busyRef.current=false;setBusy(false);}
  }
  async function refine() {
    if(!frozen||busyRef.current)return;busyRef.current=true;setBusy(true);setError('');
    try {const value=target==='story-card-composition'?Number(replacement):target==='mechanism'?JSON.parse(replacement):replacement;const next=await refinePairedDesign(frozen,target,value,approve);const outputs=await buildPairedArtifacts(next);setFrozen(next);setArtifacts(outputs);setApprove(false);}catch(e){setError(e instanceof Error?e.message:'Check the target replacement.');}finally{busyRef.current=false;setBusy(false);}
  }
  function download(){if(!frozen)return;const blob=new Blob([JSON.stringify({status:'offline-review-not-rendered',manifest:frozen,artifacts},null,2)],{type:'application/json'});const address=URL.createObjectURL(blob);const a=document.createElement('a');a.href=address;a.download='OFFKIN-paired-design-draft.json';a.click();URL.revokeObjectURL(address);}
  return <main className="paired-review">
    <header className="paired-review-header"><Link to="/">OFFKIN｜异趣伙伴</Link><span>Offline design review · no generation</span></header>
    <h1>Your business DNA. Made collectible.</h1>
    <ol className="paired-review-steps" aria-label="Review stages">{['Brand','Confirm evidence','Story lens & lock','Paired artifacts'].map((name,i)=><li key={name} aria-current={step===i?'step':undefined}>{name}</li>)}</ol>
    {step===0&&<form onSubmit={e=>{e.preventDefault();if(brand.trim())setStep(1);}}><h2>Which brand?</h2><label>Exact brand name<input value={brand} onChange={e=>setBrand(e.target.value)} maxLength={120} required autoComplete="organization"/></label><Button type="submit">Continue<ArrowRight/></Button></form>}
    {step===1&&<form onSubmit={e=>{e.preventDefault();if(quote.trim()&&confirmed)setStep(2);}}><h2>One truth to build from.</h2><label>Source excerpt or your own statement<textarea required value={quote} onChange={e=>{setQuote(e.target.value);setConfirmed(false);}} maxLength={700}/></label><label>Source URL (optional)<input type="url" value={url} onChange={e=>{setUrl(e.target.value);setConfirmed(false);}} maxLength={300}/></label><p>{url?'A URL is a citation, not proof that this page was read or verified.':'Without a source, this is labelled as your own statement—not a researched brand fact.'}</p><label className="paired-check"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I confirm this excerpt or owner statement.</label><Button type="submit" disabled={!confirmed||!quote.trim()}>Choose a story lens<ArrowRight/></Button></form>}
    {step===2&&<section><h2>Choose one story lens.</h2><div className="paired-lenses" role="radiogroup" aria-label="Story lens">{STORY_LENSES.map(value=><label key={value}><input type="radio" name="story-lens" checked={lens===value} onChange={()=>setLens(value)}/>{labels[value]}</label>)}</div><label>Brand truth → signature object<textarea value={symbolism} onChange={e=>setSymbolism(e.target.value)} maxLength={700}/></label><label>Story-card headline<input value={headline} onChange={e=>setHeadline(e.target.value)} maxLength={120}/></label><label>One-sentence story<textarea value={narrative} onChange={e=>setNarrative(e.target.value)} maxLength={500}/></label><p>Link the exact brand truth to the named object and proposed action using “because”, “so” or “therefore”.</p><details open><summary>Structured product plan</summary><p>Review draft: 3–5 major printed components is an editorial target, not a manufacturing limit. At most one proposed mechanic.</p><label>Product plan JSON<textarea className="paired-json" value={plan} onChange={e=>setPlan(e.target.value)} spellCheck={false}/></label></details><details><summary>Exact wording for separate artwork proof</summary><label>Exact supplied text<textarea value={exactText} onChange={e=>setExactText(e.target.value)} maxLength={300}/></label></details><Button disabled={busy} onClick={()=>void lock()}><LockKeyhole/>{busy?'Validating the shared design…':'Lock paired design'}</Button></section>}
    {step===3&&frozen&&<section><h2>{frozen.brand}: one object, one story.</h2><p className="paired-draft-note">Specifications only. No images have been generated; the paired renderer is not activated.</p><div className="paired-artifacts"><section aria-label="Collectible specification"><span>01 / Physical collectible</span><h3>{frozen.plan.object}</h3><p>{frozen.plan.silhouette}</p><p>{frozen.plan.mechanic?`Proposed ${frozen.plan.mechanic.kind}: ${frozen.plan.mechanic.effect}`:'Static display concept'}</p></section><section aria-label="Story-card specification"><span>02 / Illustrated story card</span><h3>{frozen.card.headline}</h3><p>{frozen.card.narrative}</p><small>{frozen.card.frames} editorial frames · matching signature object</small></section></div><details><summary>Confirmed evidence and shared identity</summary><blockquote>{frozen.truth.quote}</blockquote>{frozen.evidence.map(e=><p key={e.id}>{e.kind==='public-source'?<a href={e.sourceUrl} target="_blank" rel="noreferrer">{e.sourceUrl}</a>:e.sourceTitle}</p>)}<code>{frozen.identityId}</code>{editorialWarnings(frozen).map(w=><p key={w}>{w}</p>)}<pre>{JSON.stringify(frozen,null,2)}</pre></details><details><summary>Review deterministic output prompts</summary>{artifacts.map(a=><section key={a.role}><h3>{a.role}</h3><pre>{a.prompt}</pre></section>)}</details><details><summary>Refine one target</summary><label>Refinement target<select value={target} onChange={e=>{const value=e.target.value as RefinementTarget;setTarget(value);setReplacement(value==='story-card-composition'?'3':'');setApprove(false);}}>{REFINEMENT_TARGETS.map(t=><option key={t} value={t}>{targets[t]}</option>)}</select></label><label>Target replacement<textarea value={replacement} onChange={e=>setReplacement(e.target.value)}/></label>{target!=='story-card-composition'&&<label className="paired-check"><input type="checkbox" checked={approve} onChange={e=>setApprove(e.target.checked)}/>Approve a separate product identity; keep the previous export as its own version.</label>}<Button disabled={busy} onClick={()=>void refine()}>Review new locked version</Button></details><Button variant="outline" onClick={download}><Download/>Download review draft</Button></section>}
    {error&&<p role="alert">{error}</p>}
    {step>0&&step<3&&<Button variant="ghost" onClick={()=>setStep(s=>s-1)}>Back</Button>}
    <footer>Concept preview. Final design, functionality and pricing confirmed during the build proposal.</footer>
  </main>;
}