import { useEffect, useRef, useState } from 'react';
import { ArrowRight, LoaderCircle, Square, Sparkles } from 'lucide-react';
import { Button } from './ui/button';
import BuildProposalRequest from './BuildProposalRequest';
import { findBrand, type BrandCandidate } from '@/lib/proposal-api';
import { planPairedDesign, renderPairedAsset, restorePairedAsset } from '@/lib/paired-api';
import { loadPairedSession, savePairedSession, savePairedSnapshot, type PairedSession } from '@/lib/paired-session';
import { STORY_LENSES, type PairedConcept, type StoryLens } from '../../supabase/functions/generate-concept/paired-design';
import './paired-live-studio.css';

const lensCopy:Record<StoryLens,{title:string;copy:string}>={
 'signature-product':{title:'What they’re known for',copy:'Turn the defining product or service into one memorable object.'},
 'signature-action':{title:'What they do differently',copy:'Make a distinctive ritual or action tangible.'},
 'brand-belief':{title:'What they stand for',copy:'Translate one supported belief into a collectible story.'},
};
export default function PairedLiveStudio(){
 const saved=loadPairedSession();const[session,setSession]=useState<PairedSession>(saved||{schema:1,brand:'',website:'',business:'',lens:'signature-product'});const[entry,setEntry]=useState('');const[candidates,setCandidates]=useState<BrandCandidate[]>([]);const[step,setStep]=useState(saved?.manifest?3:saved?.website?1:0);const[collectible,setCollectible]=useState<PairedConcept>();const[storyCard,setStoryCard]=useState<PairedConcept>();const[busy,setBusy]=useState('');const[status,setStatus]=useState('');const controller=useRef<AbortController>();
 const update=(next:PairedSession)=>{setSession(next);savePairedSession(next);};
 useEffect(()=>{if(!saved?.collectibleId)return;const abort=new AbortController();void(async()=>{try{const first=await restorePairedAsset(saved.collectibleId!,abort.signal);setCollectible(first);if(saved.storyCardId)setStoryCard(await restorePairedAsset(saved.storyCardId,abort.signal));}catch{setStatus('Your direction is saved, but one or more images need to be restored.');}})();return()=>abort.abort();},[]);
 function stop(){controller.current?.abort();setBusy('');setStatus('Stopped. Finished artifacts remain saved; a request already started may still use credits.');}
 async function search(){if(!entry.trim()||busy)return;const abort=new AbortController();controller.current=abort;setBusy('Finding the right brand');setStatus('');try{const found=await findBrand(entry,abort.signal);if(found.length)setCandidates(found);else setStatus('No public match was found. Try the brand’s website address.');}catch(e){setStatus(e instanceof Error?e.message:'Brand lookup failed.');}finally{setBusy('');}}
 function choose(candidate:BrandCandidate){const next={...session,brand:candidate.name,website:candidate.url,business:candidate.description};update(next);setCandidates([]);setStep(1);}
 async function lock(){if(busy)return;const abort=new AbortController();controller.current=abort;setBusy('Reading the public source and testing the story lens');setStatus('');try{const result=await planPairedDesign({brand:session.brand,website:session.website,lens:session.lens,exactText:'',context:{business:session.business}},abort.signal);update({...session,manifest:result.manifest});setStep(3);setStatus(`Direction locked from ${result.evidence.title}. Review it before rendering.`);}catch(e){setStatus(e instanceof Error?e.message:'The direction did not pass validation.');}finally{setBusy('');}}
 async function generate(){if(!session.manifest||busy)return;const abort=new AbortController();controller.current=abort;setBusy(collectible?'Creating the linked story card':'Creating the collectible hero');setStatus('');try{let first=collectible;if(!first){first=await renderPairedAsset(session.manifest,'collectible',undefined,abort.signal);setCollectible(first);savePairedSnapshot(first);update({...session,collectibleId:first.id});setStatus('Collectible saved. Continuing with its linked story card…');setBusy('Creating the linked story card');}if(!storyCard){const second=await renderPairedAsset(session.manifest,'story-card',first.id,abort.signal);setStoryCard(second);savePairedSnapshot(second);update({...session,collectibleId:first.id,storyCardId:second.id});setStatus('Your linked concept pair is ready.');}}catch(e){setStatus(e instanceof Error?e.message:'The next artifact could not be completed.');}finally{setBusy('');}}
 const complete=Boolean(collectible&&storyCard);return <div className="pl-app"><header className="pl-header"><a href="/">OFFKIN｜异趣伙伴</a><span>Linked concept studio</span></header><main>
 {!complete&&<section className="pl-intro"><p>From IP to “I Want That”</p><h1>Your business DNA.<br/><em>Made collectible.</em></h1><ol>{['Brand','Evidence','Story lens','Linked pair'].map((name,index)=><li key={name} className={step===index?'is-current':''}><span>{index+1}</span>{name}</li>)}</ol></section>}
 {step===0&&<section className="pl-panel"><h2>Which brand should become collectible?</h2><form onSubmit={e=>{e.preventDefault();void search();}}><input value={entry} onChange={e=>setEntry(e.target.value)} placeholder="Enter a brand name" maxLength={80}/><Button disabled={Boolean(busy)||!entry.trim()}>Find brand<ArrowRight/></Button></form>{candidates.map(candidate=><button className="pl-match" key={candidate.url} onClick={()=>choose(candidate)}><span><strong>{candidate.name}</strong><small>{candidate.url}</small><p>{candidate.description}</p></span><ArrowRight/></button>)}</section>}
 {step===1&&<section className="pl-panel"><h2>Confirm the public starting point.</h2><label>Exact brand name<input value={session.brand} onChange={e=>update({...session,brand:e.target.value})} maxLength={120}/></label><label>Public website<input value={session.website} onChange={e=>update({...session,website:e.target.value})} maxLength={300}/></label><label>What does the brand do?<textarea value={session.business} onChange={e=>update({...session,business:e.target.value})} maxLength={2000}/></label><Button onClick={()=>setStep(2)} disabled={!session.brand.trim()||!session.website.trim()||!session.business.trim()}>Choose a story lens<ArrowRight/></Button></section>}
 {step===2&&<section className="pl-panel"><h2>Choose one story lens.</h2><div className="pl-lenses">{STORY_LENSES.map(lens=><button key={lens} className={session.lens===lens?'is-selected':''} onClick={()=>update({...session,lens})}><strong>{lensCopy[lens].title}</strong><span>{lensCopy[lens].copy}</span></button>)}</div><Button onClick={()=>void lock()} disabled={Boolean(busy)}>Research and lock direction<Sparkles/></Button></section>}
 {step===3&&session.manifest&&<><section className="pl-lock"><div><p>LOCKED DIRECTION / {lensCopy[session.manifest.lens].title}</p><h2>{session.manifest.plan.object}</h2><p>{session.manifest.card.narrative}</p><a href={session.manifest.evidence[0].sourceUrl} target="_blank" rel="noreferrer">Source: {session.manifest.evidence[0].sourceTitle}</a></div><details><summary>Advanced concept plan</summary><pre>{JSON.stringify({silhouette:session.manifest.plan.silhouette,components:session.manifest.plan.components,mechanic:session.manifest.plan.mechanic,caveats:session.manifest.plan.caveats},null,2)}</pre></details>{!complete&&<Button onClick={()=>void generate()} disabled={Boolean(busy)}>{collectible?'Continue story card':'Generate linked concept'}<Sparkles/></Button>}</section>{(collectible||storyCard)&&<section className="pl-results"><article><span>01 / COLLECTIBLE HERO</span>{collectible?<img src={collectible.image} alt={`${collectible.brand} collectible concept`}/>:<div/>}<h2>{collectible?.title||'Creating the collectible'}</h2></article><article><span>02 / ILLUSTRATED STORY CARD</span>{storyCard?<img src={storyCard.image} alt={`${storyCard.brand} illustrated story card`}/>:<div/>}<h2>{storyCard?.title||'Waiting for the approved collectible'}</h2></article><p>Concept preview. Final design, functionality and pricing confirmed during the build proposal.</p></section>}</>}
 {complete&&<BuildProposalRequest brief={session.manifest?.card.narrative||''} pairedAssets={[collectible!,storyCard!]}/>} {(busy||status)&&<div className="pl-status" role="status">{busy&&<LoaderCircle className="op-spin"/>}<span>{busy||status}</span>{busy&&<button onClick={stop}><Square/>Stop</button>}</div>}
 </main><footer>Give People Something To Talk About. <strong>Make It LIVE.</strong></footer></div>;
}
