import { act, cleanup, fireEvent, render, screen, waitFor, within } from '@testing-library/react';
import { MemoryRouter, Link, useNavigate } from 'react-router-dom';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import Index from '@/pages/Index';
import { PROPOSAL_SESSION_KEY, decodeProposalShare, emptyProposalSession, encodeProposalShare, loadProposalSession, pendingProposal, saveProposalSession, type ProposalSession } from '@/lib/proposal-session';
import { ProposalConstructionNeededError, ProposalContextNeededError } from '@/lib/proposal-api';
import type { ProposalConcept, ProposalRequest, ProposalStage } from '@/lib/proposal-api';
const mocks=vi.hoisted(()=>({generate:vi.fn(),restore:vi.fn(),plan:vi.fn(),ready:vi.fn(),website:vi.fn(),paused:false}));
vi.mock('@/lib/proposal-availability',async original=>({...await original<object>(),get PROPOSAL_GENERATION_PAUSED(){return mocks.paused;}}));
vi.mock('@/lib/proposal-api',async original=>({...await original<object>(),requestProposalAsset:mocks.generate,restoreProposalAsset:mocks.restore,planProposalRevision:mocks.plan,supportsProposalGeneration:mocks.ready}));
vi.mock('@/lib/concept-api',()=>({requestConcept:mocks.website}));
vi.mock('@/integrations/supabase/client',()=>({supabase:{from:()=>({select:async()=>({data:[{key:'site_title',value:'OFFKIN'}]})})}}));
const ids:Record<ProposalStage,string>={world:'00000000-0000-4000-8000-000000000001',physical:'00000000-0000-4000-8000-000000000002',details:'00000000-0000-4000-8000-000000000003',packaging:'00000000-0000-4000-8000-000000000004'};
const elements=[{id:'house',label:'Paper house',description:'A proposed paper neighbourhood.',kind:'proposal' as const},{id:'path',label:'Ribbon path',description:'A proposed connecting path.',kind:'proposal' as const}];
function fixture(body:ProposalRequest,overrides:Partial<ProposalConcept>={}):ProposalConcept{const {previousAssetId:_previous,...publicBody}=body;return {...publicBody,stageVersion:'proposal-assets-v1',id:ids[body.stage],brand:'Paper Studio',title:`Paper ${body.stage}`,story:`A new ${body.stage} made for this customer.`,design:'Rich connected paper design.',interaction:'Turn to reveal another story.',image:`https://images.example/${body.stage}.png`,sourceUrl:'',sourceTitle:'',worldElements:elements,sourceImageIds:[...(body.stage==='physical'?[body.sourceWorldId!]:body.stage==='details'?[body.sourcePhysicalId!]:body.stage==='packaging'?[body.sourcePhysicalId!,body.sourceWorldId!]:[])],...(body.stage==='details'||body.stage==='packaging'?{selectedElementIds:['house','path'],heroElementId:'house',replacements:[]}:{}),...overrides};}
function saved():ProposalSession{const s=emptyProposalSession();s.context.business='We create personalised paper gifts';s.accepted={id:'accepted',context:s.context,website:'',assets:{...ids},selected:['house','path'],hero:'house',replacements:[]};return s;}
function deferred<T>(){let resolve!:(v:T)=>void;const promise=new Promise<T>(done=>{resolve=done;});return {resolve,promise};}
function Navigation(){const navigate=useNavigate();return <nav><Link to="/?next=1">Newer route</Link><button onClick={()=>navigate(-1)}>Back</button></nav>;}
function mount(path='/?proposal=1',nav=false){return render(<MemoryRouter initialEntries={[path]}>{nav&&<Navigation/>}<Index/></MemoryRouter>);}
async function introduction(select=true){fireEvent.change(screen.getByLabelText('Your brand, website or story'),{target:{value:'We create personalised paper gifts'}});fireEvent.click(screen.getByRole('button',{name:/Explore my brand|Continue conversation/}));fireEvent.click(screen.getByRole('button',{name:'Clients & partners'}));if(select){fireEvent.click(screen.getByRole('button',{name:'Static display'}));await waitFor(()=>expect(screen.getByRole('button',{name:'Generate my proposal'})).toBeEnabled());}}
async function reconfirmConstruction(label='Static display'){await screen.findByText('Choose the construction action again for this revised direction.');expect(screen.getByRole('button',{name:'Continue proposal'})).toBeDisabled();const count=mocks.generate.mock.calls.length;fireEvent.click(screen.getByRole('button',{name:label}));expect(mocks.generate).toHaveBeenCalledTimes(count);fireEvent.click(screen.getByRole('button',{name:'Continue proposal'}));}
async function complete(){await introduction();fireEvent.click(screen.getByRole('button',{name:'Generate my proposal'}));await screen.findByRole('heading',{name:'Paper packaging'});await waitFor(()=>expect(screen.getByRole('button',{name:'Update proposal'})).toBeInTheDocument());}
beforeEach(()=>{mocks.paused=false;localStorage.clear();vi.clearAllMocks();mocks.ready.mockResolvedValue(true);mocks.generate.mockImplementation(async(body:ProposalRequest)=>fixture(body));mocks.restore.mockImplementation(async(id:string)=>{const stage=Object.keys(ids).find(stage=>ids[stage]===id) as ProposalStage;const s=saved();return fixture({contractVersion:'offkin-proposal-v10',stage,brand:'no-website',context:s.context,...(stage!=='world'?{sourceWorldId:ids.world,selectedElementIds:['house','path'],heroElementId:'house',replacements:[]}:{}),...(['details','packaging'].includes(stage)?{sourcePhysicalId:ids.physical}:{})});});mocks.plan.mockImplementation(async body=>({plan:{scope:'packaging',context:{...body.context,revisionNotes:'Packaging deep blue; object unchanged'},summary:'Keep your world and object. Make only the packaging deep blue.'}}));});
afterEach(async()=>{await act(async()=>{});cleanup();vi.useRealTimers();vi.restoreAllMocks();});
describe('Complete proposal journey',()=>{
  it('asks for one explicit unverified action without selecting a default or generating',async()=>{
    mount();await introduction(false);
    expect(screen.getByText('What should your collectible do?')).toBeInTheDocument();
    for(const name of ['Static display','Proposed press/reveal with manual lift reset'])expect(screen.getByRole('button',{name})).toHaveAttribute('aria-pressed','false');
    expect(screen.getByText(/Construction is unverified and requires CAD/)).toBeInTheDocument();
    expect(screen.getByRole('button',{name:'Generate my proposal'})).toBeDisabled();
    fireEvent.click(screen.getByRole('button',{name:'Generate my proposal'}));
    expect(loadProposalSession()?.constructionIntent).toBeUndefined();expect(mocks.generate).not.toHaveBeenCalled();
  });
  it.each([
    ['Static display','static','Display only'],
    ['Proposed press/reveal with manual lift reset','press-reveal-manual-reset','Press the hero to reveal a marker; lift manually to reset.'],
  ])('records %s as a user instruction and sends exact intent only on world and physical',async(label,action,interaction)=>{
    mount();await introduction(false);
    fireEvent.change(screen.getByLabelText('Business story'),{target:{value:'Fable Finch is a fictional paper-gift studio.'}});
    fireEvent.change(screen.getByLabelText('Exact wording'),{target:{value:'  字\nCafé 🪁 EXACT!  '}});
    const before=loadProposalSession()!.context;
    fireEvent.click(screen.getByRole('button',{name:label}));
    expect(loadProposalSession()?.context).toEqual({...before,interaction,mode:'mechanical'});
    expect(loadProposalSession()?.turns.at(-1)).toEqual({role:'user',text:label});
    expect(mocks.generate).not.toHaveBeenCalled();
    fireEvent.click(screen.getByRole('button',{name:'Generate my proposal'}));await screen.findByRole('button',{name:'Update proposal'});
    const requests=mocks.generate.mock.calls.map(([body])=>body);
    for(const request of requests.slice(0,2))expect(request.constructionIntent).toEqual({version:'construction-intent-v1',action});
    for(const request of requests.slice(2))expect(request).not.toHaveProperty('constructionIntent');
    expect(JSON.stringify(requests)).not.toMatch(/tesla|sun|reviewed/i);
    expect(loadProposalSession()?.accepted?.constructionIntent).toEqual({version:'construction-intent-v1',action});
  });
  it.each(['Business story','Audience','Story direction','Brand identifiers & colours','Visual style','Exact wording','Interaction','Public website'])('invalidates the active action after changing %s',async label=>{
    mount();await introduction();
    expect(loadProposalSession()?.constructionIntent?.action).toBe('static');
    fireEvent.change(screen.getByLabelText(label),{target:{value:label==='Public website'?'https://fable.example':'A changed direction'}});
    expect(loadProposalSession()?.constructionIntent).toBeUndefined();
    expect(screen.getByRole('button',{name:'Generate my proposal'})).toBeDisabled();
    expect(screen.getByRole('button',{name:'Static display'})).toHaveAttribute('aria-pressed','false');
    expect(mocks.generate).not.toHaveBeenCalled();
  });
  it('restores a legacy partial world and requires a choice before any missing product generation',async()=>{
    const s=emptyProposalSession();s.context.business='A saved partial story';s.pending={...pendingProposal(s,'world',s.context),assets:{world:ids.world},selected:['house','path'],hero:'house'};saveProposalSession(s);
    mount();fireEvent.click(screen.getByRole('button',{name:'Continue saved proposal'}));await screen.findByRole('heading',{name:'Paper world'});
    expect(screen.getByRole('button',{name:'Continue proposal'})).toBeDisabled();expect(mocks.generate).not.toHaveBeenCalled();
    fireEvent.click(screen.getByRole('button',{name:'Static display'}));expect(mocks.generate).not.toHaveBeenCalled();
    fireEvent.click(screen.getByRole('button',{name:'Continue proposal'}));await screen.findByRole('button',{name:'Update proposal'});
    expect(mocks.generate.mock.calls.map(([body])=>body.stage)).toEqual(['physical','details','packaging']);
  });


  it('keeps a saved partial world intact when its construction metadata cannot be restored',async()=>{
    const s=emptyProposalSession();s.context.business='A saved paper world';s.pending={...pendingProposal(s,'world',s.context),assets:{world:ids.world},selected:['house','path'],hero:'house'};saveProposalSession(s);mocks.restore.mockRejectedValueOnce(new Error('Saved metadata unavailable'));
    mount();fireEvent.click(screen.getByRole('button',{name:'Continue saved proposal'}));await screen.findByText(/Some saved images could not be restored/);
    fireEvent.click(screen.getByRole('button',{name:'Proposed press/reveal with manual lift reset'}));
    expect(screen.getByText(/Restore the saved world metadata before choosing/)).toBeInTheDocument();expect(loadProposalSession()?.pending).toEqual(s.pending);expect(screen.getByRole('button',{name:'Continue proposal'})).toBeDisabled();expect(mocks.generate).not.toHaveBeenCalled();
  });
  it('does not silently change the construction of a restored partial world',async()=>{
    const s=emptyProposalSession();s.context={...s.context,business:'A saved paper world',mode:'mechanical',interaction:'Display only'};s.pending={...pendingProposal(s,'world',s.context),assets:{world:ids.world},selected:['house','path'],hero:'house'};saveProposalSession(s);
    mocks.restore.mockResolvedValueOnce(fixture({contractVersion:'offkin-proposal-v10',stage:'world',brand:'no-website',context:s.context,constructionIntent:{version:'construction-intent-v1',action:'static'}}));
    mount();fireEvent.click(screen.getByRole('button',{name:'Continue saved proposal'}));await screen.findByRole('heading',{name:'Paper world'});
    fireEvent.click(screen.getByRole('button',{name:'Proposed press/reveal with manual lift reset'}));
    expect(screen.getByText(/This saved world uses a different construction action/)).toBeInTheDocument();expect(loadProposalSession()?.pending).toEqual(s.pending);expect(screen.getByRole('button',{name:'Continue proposal'})).toBeDisabled();expect(mocks.generate).not.toHaveBeenCalled();
    fireEvent.click(screen.getByRole('button',{name:'Static display'}));expect(screen.getByRole('button',{name:'Continue proposal'})).toBeEnabled();expect(mocks.generate).not.toHaveBeenCalled();
  });
  it('does not adopt the sender’s action as confirmation in a text-only branch',async()=>{
    const s=emptyProposalSession();s.context={...s.context,business:'A shared fictional paper brand',mode:'mechanical',interaction:'Display only'};s.constructionIntent={version:'construction-intent-v1',action:'static'};
    mount('/'+encodeProposalShare(s));fireEvent.click(screen.getByRole('button',{name:'Open my editable version'}));await screen.findByText('What should your collectible do?');
    expect(loadProposalSession()?.constructionIntent).toBeUndefined();expect(screen.getByRole('button',{name:'Generate my proposal'})).toBeDisabled();expect(mocks.generate).not.toHaveBeenCalled();
  });
  it('preserves the accepted version and changed selection until a revision is explicitly reconfirmed',async()=>{
    mount();await complete();const accepted=loadProposalSession()!.accepted;
    mocks.plan.mockImplementation(async body=>({plan:{scope:'physical',context:{...body.context,revisionNotes:'Use the path as hero'},summary:'Use the path as the product hero.',selectedElementIds:['path'],heroElementId:'path',replacements:[{id:'path',label:'Folded trail',description:'A folded trail replaces the ribbon.'}]}}));
    fireEvent.change(screen.getByLabelText('Change your proposal'),{target:{value:'Use the path as hero'}});fireEvent.click(screen.getByRole('button',{name:'Update proposal'}));
    await screen.findByText('Choose the construction action again for this revised direction.');
    expect(mocks.generate).toHaveBeenCalledTimes(4);expect(loadProposalSession()?.accepted).toEqual(accepted);expect(loadProposalSession()?.pending).toMatchObject({selected:['path'],hero:'path',replacements:[{id:'path',label:'Folded trail',description:'A folded trail replaces the ribbon.'}]});expect(loadProposalSession()?.pending?.constructionIntent).toBeUndefined();
    fireEvent.click(screen.getByRole('button',{name:'Proposed press/reveal with manual lift reset'}));expect(mocks.generate).toHaveBeenCalledTimes(4);
    expect(loadProposalSession()?.pending?.context.revisionNotes).toBe('Use the path as hero');
    fireEvent.click(screen.getByRole('button',{name:'Discard unfinished version'}));expect(loadProposalSession()?.accepted).toEqual(accepted);expect(mocks.generate).toHaveBeenCalledTimes(4);
  });

  it('keeps saved-resume UI outside the separate headline, form and artwork grid items',async()=>{saveProposalSession(saved());mount();await act(async()=>{});const opening=document.querySelector('.op-opening')!;for(const selector of ['.op-intro','.op-entry-panel','.op-hero-art'])expect(document.querySelector(selector)?.parentElement).toBe(opening);const resume=document.querySelector('.op-resume')!;expect(opening.contains(resume)).toBe(false);expect(resume.compareDocumentPosition(opening)&Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy();expect(screen.getByRole('button',{name:'Explore my brand'})).toBeInTheDocument();expect(mocks.generate).not.toHaveBeenCalled();});

  it('matches the entry button accessible name to its visible label',async()=>{mount();const button=screen.getByRole('button',{name:'Explore my brand'});expect(button).toHaveTextContent('Explore my brand');await act(async()=>{});});
  it.each(['Enlarge collectible','Open collectible image'])('returns image dialog focus to %s after Escape',async(name)=>{saveProposalSession(saved());mount();fireEvent.click(screen.getByRole('button',{name:'Continue saved proposal'}));await screen.findByRole('heading',{name:'Paper packaging'});const trigger=screen.getByRole('button',{name});fireEvent.click(trigger);const dialog=await screen.findByRole('dialog');fireEvent.keyDown(dialog,{key:'Escape',code:'Escape'});await waitFor(()=>expect(screen.queryByRole('dialog')).not.toBeInTheDocument());await waitFor(()=>expect(trigger).toHaveFocus());});
  it('returns share dialog focus to Share after Close',async()=>{saveProposalSession(saved());mount();fireEvent.click(screen.getByRole('button',{name:'Continue saved proposal'}));await screen.findByRole('heading',{name:'Paper packaging'});const trigger=screen.getByRole('button',{name:'Share'});fireEvent.click(trigger);const dialog=await screen.findByRole('dialog');fireEvent.click(within(dialog).getByRole('button',{name:'Close'}));await waitFor(()=>expect(screen.queryByRole('dialog')).not.toBeInTheDocument());await waitFor(()=>expect(trigger).toHaveFocus());});
  it('focuses the main content after completing a shared import',async()=>{const s=emptyProposalSession();s.context.business='Shared design direction';mount('/'+encodeProposalShare(s));fireEvent.click(screen.getByRole('button',{name:'Open my editable version'}));await waitFor(()=>expect(screen.queryByRole('dialog')).not.toBeInTheDocument());await waitFor(()=>expect(document.getElementById('proposal-main')).toHaveFocus());expect(mocks.generate).not.toHaveBeenCalled();});

  it('preserves an explicit display-only choice without inventing an interaction',async()=>{mount();await introduction();fireEvent.click(screen.getByRole('button',{name:'Static display'}));fireEvent.click(screen.getByRole('button',{name:'Generate my proposal'}));await waitFor(()=>expect(mocks.generate).toHaveBeenCalledTimes(4));for(const [request] of mocks.generate.mock.calls)expect(request.context.interaction).toBe('Display only');});

  it('keeps in-page navigation out of route history and does not abort an active proposal',async()=>{Element.prototype.scrollIntoView=vi.fn();mount();await introduction();const gate=deferred<ProposalConcept>();mocks.generate.mockImplementationOnce(()=>gate.promise);fireEvent.click(screen.getByRole('button',{name:'Generate my proposal'}));const signal=mocks.generate.mock.calls[0][1];expect(fireEvent.click(screen.getByRole('link',{name:'Skip to your proposal'}))).toBe(false);expect(fireEvent.click(within(screen.getByRole('banner')).getByRole('link',{name:'Start your world'}))).toBe(false);expect(signal.aborted).toBe(false);const body=mocks.generate.mock.calls[0][0];await act(async()=>gate.resolve(fixture(body)));await screen.findByRole('button',{name:'Update proposal'});expect(mocks.generate).toHaveBeenCalledTimes(4);});

  it('presents the reference-led marketing and accessible stages without seeding a proposal',async()=>{mount();expect(screen.getByRole('heading',{level:1})).toHaveTextContent('Your business DNA. Made collectible.');expect(screen.getByRole('link',{name:'Skip to your proposal'})).toHaveAttribute('href','#proposal-main');expect(within(screen.getByRole('banner')).getByRole('link',{name:'Start your world'})).toHaveAttribute('href','#proposal-conversation');const journey=screen.getByRole('region',{name:'Four connected proposal stages'});expect(within(journey).getAllByRole('listitem')).toHaveLength(4);expect(screen.getByRole('textbox',{name:'Your brand, website or story'})).toBeEnabled();expect(screen.queryAllByRole('img')).toHaveLength(0);expect(screen.getByRole('heading',{name:'Small objects. Bigger possibilities.'})).toBeInTheDocument();expect(document.querySelectorAll('[data-marketing-art]')).toHaveLength(9);expect(screen.getByText(/Illustrative concepts from our visual direction/)).toBeInTheDocument();expect(loadProposalSession()).toBeNull();expect(mocks.generate).not.toHaveBeenCalled();await act(async()=>{});});
  it('keeps all marketing navigation local and preserves the typed entry',async()=>{Element.prototype.scrollIntoView=vi.fn();mount();fireEvent.change(screen.getByLabelText('Your brand, website or story'),{target:{value:'Our solar community'}});const nav=within(screen.getByRole('navigation',{name:'Explore OFFKIN'}));for(const name of ['Worlds','Collectibles','The studio']){const link=nav.getByRole('link',{name});expect(fireEvent.click(link)).toBe(false);expect(document.querySelector(link.getAttribute('href')!)).toBeInTheDocument();}expect(screen.getByLabelText('Your brand, website or story')).toHaveValue('Our solar community');expect(mocks.generate).not.toHaveBeenCalled();await act(async()=>{});});
  it('removes marketing artwork from a restored customer result',async()=>{saveProposalSession(saved());mount();fireEvent.click(screen.getByRole('button',{name:'Continue saved proposal'}));await screen.findByRole('heading',{name:'Paper packaging'});expect(document.querySelectorAll('[data-marketing-art]')).toHaveLength(0);expect(screen.getAllByRole('img')).toHaveLength(4);expect(screen.queryByRole('heading',{name:'Collectible stories'})).not.toBeInTheDocument();expect(mocks.generate).not.toHaveBeenCalled();});

  it('requires an explicit action even when the story already mentions pressing a sun',async()=>{mount();const story='We connect a solar community. Press the sun to reveal the shared energy path.';fireEvent.change(screen.getByLabelText('Your brand, website or story'),{target:{value:story}});fireEvent.click(screen.getByRole('button',{name:/Explore my brand|Continue conversation/}));fireEvent.click(screen.getByRole('button',{name:'Clients & partners'}));expect(screen.getByRole('button',{name:'Generate my proposal'})).toBeDisabled();fireEvent.click(screen.getByRole('button',{name:'Proposed press/reveal with manual lift reset'}));await waitFor(()=>expect(screen.getByRole('button',{name:'Generate my proposal'})).toBeEnabled());fireEvent.click(screen.getByRole('button',{name:'Generate my proposal'}));await waitFor(()=>expect(mocks.generate).toHaveBeenCalledTimes(4));expect(mocks.generate.mock.calls[0][0].context.business).toBe(story);expect(mocks.generate.mock.calls[0][0].context.interaction).toBe('Press the hero to reveal a marker; lift manually to reset.');expect(JSON.stringify(mocks.generate.mock.calls[0][0].context)).not.toContain('Display only');});
  it('uses a result anchor after restore and keeps refinement editable while generation is paused',async()=>{saveProposalSession(saved());mocks.ready.mockResolvedValue(false);mount();fireEvent.click(screen.getByRole('button',{name:'Continue saved proposal'}));await screen.findByRole('heading',{name:'Paper packaging'});expect(screen.getByRole('link',{name:'Your proposal'})).toHaveAttribute('href','#proposal-results');expect(document.getElementById('proposal-results')).toBeInTheDocument();expect(screen.getByRole('textbox',{name:'Change your proposal'})).toBeEnabled();expect(screen.getByRole('button',{name:'Update proposal'})).toBeDisabled();});

  it('keeps ordinary visitors in a truthful saved-brief shell during the temporary hold',async()=>{mocks.paused=true;mocks.ready.mockResolvedValue(false);mount('/');await screen.findByText(/New complete-proposal generation is temporarily unavailable/);expect(screen.getByRole('link',{name:'Earlier workflow: visual studies only'})).toHaveAttribute('href','/?canvas=legacy');fireEvent.change(screen.getByLabelText('Your brand, website or story'),{target:{value:'A physical gift for our partners'}});fireEvent.click(screen.getByRole('button',{name:/Explore my brand|Continue conversation/}));fireEvent.click(screen.getByRole('button',{name:'Clients & partners'}));expect(screen.getByRole('button',{name:'Generate my proposal'})).toBeDisabled();expect(screen.getByRole('button',{name:'Download brief'})).toBeEnabled();expect(mocks.generate).not.toHaveBeenCalled();});
  it('starts empty and keeps reference brands out of customer state',async()=>{mount();await waitFor(()=>expect(mocks.ready).toHaveBeenCalled());expect(screen.getByRole('heading',{level:1})).toHaveTextContent('Your business DNA. Made collectible.');expect(screen.queryByRole('img')).not.toBeInTheDocument();expect(screen.queryByText(/Airbnb|Tesla|A24/)).not.toBeInTheDocument();expect(localStorage.getItem(PROPOSAL_SESSION_KEY)).toBeNull();expect(mocks.generate).not.toHaveBeenCalled();});
  it('generates all four genuine roles from one explicit action with actual saved lineage',async()=>{mount();await complete();expect(mocks.generate.mock.calls.map(([b])=>b.stage)).toEqual(['world','physical','details','packaging']);const bodies=mocks.generate.mock.calls.map(([b])=>b);expect(bodies[1]).toMatchObject({sourceWorldId:ids.world,selectedElementIds:['house','path'],heroElementId:'house'});expect(bodies[2]).toMatchObject({sourceWorldId:ids.world,sourcePhysicalId:ids.physical});expect(bodies[3]).toMatchObject({sourceWorldId:ids.world,sourcePhysicalId:ids.physical});expect(screen.getAllByRole('img')).toHaveLength(4);expect(loadProposalSession()?.accepted?.assets).toEqual(ids);expect(loadProposalSession()?.pending).toBeNull();});
  it('does not generate on typing, IME composition or audience selection',async()=>{mount();const input=screen.getByLabelText('Your brand, website or story');fireEvent.change(input,{target:{value:'纸世界 Café 🪁'}});fireEvent.keyDown(input,{key:'Enter',isComposing:true});expect(screen.getByText('What’s the business, brand or idea?')).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:/Explore my brand|Continue conversation/}));fireEvent.click(screen.getByRole('button',{name:'Let the story lead'}));expect(mocks.generate).not.toHaveBeenCalled();expect(loadProposalSession()?.context.business).toBe('纸世界 Café 🪁');});
  it('reads a URL only on the explicit website action',async()=>{mocks.website.mockResolvedValue({website:{url:'https://paper.example/',title:'Paper',excerpt:'We fold meaningful paper gifts.'}});mount();fireEvent.change(screen.getByLabelText('Your brand, website or story'),{target:{value:'https://paper.example'}});fireEvent.click(screen.getByRole('button',{name:/Explore my brand|Continue conversation/}));expect(mocks.website).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Read public website'}));await screen.findByText('We fold meaningful paper gifts.');expect(mocks.generate).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Use this business description'}));expect(loadProposalSession()?.context.business).toBe('We fold meaningful paper gifts.');});
  it('prevents duplicate generation clicks',async()=>{const gate=deferred<ProposalConcept>();mocks.generate.mockImplementationOnce(()=>gate.promise);mount();await introduction();const button=screen.getByRole('button',{name:'Generate my proposal'});fireEvent.click(button);fireEvent.click(button);expect(mocks.generate).toHaveBeenCalledOnce();await act(async()=>{gate.resolve(fixture(mocks.generate.mock.calls[0][0]));});await screen.findByRole('heading',{name:'Paper packaging'});expect(mocks.generate).toHaveBeenCalledTimes(4);});
  it('saves the first three sections and resumes only failed packaging',async()=>{let failed=false;mocks.generate.mockImplementation(async(body:ProposalRequest)=>{if(body.stage==='packaging'&&!failed){failed=true;throw new Error('Gateway paused');}return fixture(body);});mount();await introduction();fireEvent.click(screen.getByRole('button',{name:'Generate my proposal'}));await screen.findByText('Gateway paused');expect(loadProposalSession()?.pending?.assets).toEqual({world:ids.world,physical:ids.physical,details:ids.details});fireEvent.click(screen.getByRole('button',{name:'Continue proposal'}));await screen.findByRole('heading',{name:'Paper packaging'});expect(mocks.generate.mock.calls.map(([b])=>b.stage)).toEqual(['world','physical','details','packaging','packaging']);});
  it('ignores cancelled late output and never advances to another paid stage',async()=>{const gate=deferred<ProposalConcept>();mocks.generate.mockImplementationOnce(()=>gate.promise);mount();await introduction();fireEvent.click(screen.getByRole('button',{name:'Generate my proposal'}));const signal=mocks.generate.mock.calls[0][1];fireEvent.click(screen.getByRole('button',{name:'Stop'}));expect(signal.aborted).toBe(true);await act(async()=>{gate.resolve(fixture(mocks.generate.mock.calls[0][0]));});expect(mocks.generate).toHaveBeenCalledOnce();expect(loadProposalSession()?.pending?.assets).toEqual({});expect(screen.queryByRole('img')).not.toBeInTheDocument();});
  it('cancels on newer navigation and ignores the stale response',async()=>{const gate=deferred<ProposalConcept>();mocks.generate.mockImplementationOnce(()=>gate.promise);mount('/?proposal=1',true);await introduction();fireEvent.click(screen.getByRole('button',{name:'Generate my proposal'}));const signal=mocks.generate.mock.calls[0][1];fireEvent.click(screen.getByRole('link',{name:'Newer route'}));expect(signal.aborted).toBe(true);await act(async()=>{gate.resolve(fixture(mocks.generate.mock.calls[0][0]));});expect(mocks.generate).toHaveBeenCalledOnce();expect(loadProposalSession()?.pending?.assets).toEqual({});});
  it('actually generates packaging revision while preserving accepted world, hero and details IDs',async()=>{mount();await complete();const replacement='00000000-0000-4000-8000-000000000014';mocks.generate.mockImplementation(async(body:ProposalRequest)=>fixture(body,{id:replacement,image:'https://images.example/blue-packaging.png'}));fireEvent.change(screen.getByLabelText('Change your proposal'),{target:{value:'Keep the object. Make the packaging deep blue.'}});fireEvent.click(screen.getByRole('button',{name:'Update proposal'}));await waitFor(()=>expect(loadProposalSession()?.accepted?.assets.packaging).toBe(replacement));expect(mocks.plan).toHaveBeenCalledOnce();expect(mocks.generate).toHaveBeenCalledTimes(5);expect(mocks.generate.mock.calls[4][0]).toMatchObject({stage:'packaging',previousAssetId:ids.packaging,sourceWorldId:ids.world,sourcePhysicalId:ids.physical});expect(loadProposalSession()?.accepted?.assets).toEqual({...ids,packaging:replacement});});
  it('retains accepted images throughout a partial revision and swaps only when complete',async()=>{mount();await complete();const gate=deferred<ProposalConcept>();mocks.plan.mockImplementation(async body=>({plan:{scope:'physical',context:{...body.context,revisionNotes:'Make the object a cafe'},summary:'Revise the object and dependent sections.'}}));mocks.generate.mockImplementation((body:ProposalRequest)=>body.stage==='packaging'?gate.promise:Promise.resolve(fixture(body,{id:ids[body.stage].replace('00000000000','00000000001'),image:`https://images.example/new-${body.stage}.png`})));
    fireEvent.change(screen.getByLabelText('Change your proposal'),{target:{value:'Make the object a cafe'}});fireEvent.click(screen.getByRole('button',{name:'Update proposal'}));await reconfirmConstruction();await waitFor(()=>expect(mocks.generate).toHaveBeenCalledTimes(7));expect(screen.getAllByRole('img').map(i=>i.getAttribute('src'))).toContain('https://images.example/physical.png');expect(screen.queryByRole('img',{name:/new-physical/})).not.toBeInTheDocument();const body=mocks.generate.mock.calls[6][0];await act(async()=>{gate.resolve(fixture(body,{id:'00000000-0000-4000-8000-000000000014',image:'https://images.example/new-packaging.png'}));});await waitFor(()=>expect(loadProposalSession()?.pending).toBeNull());expect(screen.getAllByRole('img').map(i=>i.getAttribute('src'))).toContain('https://images.example/new-physical.png');});
  it('applies validated component replacements to the generated physical request',async()=>{mount();await complete();mocks.plan.mockImplementation(async body=>({plan:{scope:'physical',context:{...body.context,revisionNotes:'Replace house with a cafe'},summary:'Replace the house with a cafe.',selectedElementIds:['house','path'],heroElementId:'house',replacements:[{id:'house',label:'Paper cafe',description:'A welcoming cafe replaces the house.'}]}}));mocks.generate.mockImplementation(async(body:ProposalRequest)=>fixture(body,{id:ids[body.stage].replace('00000000000','00000000001')}));fireEvent.change(screen.getByLabelText('Change your proposal'),{target:{value:'Replace the house with a cafe'}});fireEvent.click(screen.getByRole('button',{name:'Update proposal'}));await reconfirmConstruction();await waitFor(()=>expect(mocks.generate).toHaveBeenCalledTimes(7));expect(mocks.generate.mock.calls[4][0]).toMatchObject({stage:'physical',selectedElementIds:['house','path'],replacements:[{id:'house',label:'Paper cafe',description:'A welcoming cafe replaces the house.'}]});expect(loadProposalSession()?.accepted?.assets.world).toBe(ids.world);});
  it('reopens one business question when the generator needs facts before any image exists',async()=>{mocks.generate.mockRejectedValueOnce(new ProposalContextNeededError('Tell us what the business does.'));mount();await introduction();fireEvent.click(screen.getByRole('button',{name:'Generate my proposal'}));await screen.findByText('Tell us what the business does.');expect(screen.getByText('What should this world say about your business?')).toBeInTheDocument();expect(screen.getByLabelText('Your brand, website or story')).toBeEnabled();expect(loadProposalSession()?.pending).toBeNull();expect(mocks.generate).toHaveBeenCalledOnce();});
  it('returns fresh construction clarification to editable details without changing the brief or retrying',async()=>{
    mocks.generate.mockRejectedValueOnce(new ProposalConstructionNeededError('Should pressing the sun lift the scene or slide a panel?'));
    mount();await introduction();
    fireEvent.change(screen.getByLabelText('Exact wording'),{target:{value:'  字\nCafé 🪁 '}});
    fireEvent.change(screen.getByLabelText('Interaction'),{target:{value:'Press the sun to reveal a scene'}});
    fireEvent.change(screen.getByLabelText('Public website'),{target:{value:'https://paper.example'}});
    expect(screen.getByRole('button',{name:'Generate my proposal'})).toBeDisabled();
    fireEvent.click(screen.getByRole('button',{name:'Proposed press/reveal with manual lift reset'}));
    const original=loadProposalSession();
    fireEvent.click(screen.getByRole('button',{name:'Generate my proposal'}));
    await screen.findByText(/Should pressing the sun lift the scene or slide a panel\? Review your direction under Edit details/);
    expect(loadProposalSession()).toEqual(original);
    expect(screen.getByRole('button',{name:'Generate my proposal'})).toBeEnabled();
    expect(screen.queryByText('What should this world say about your business?')).not.toBeInTheDocument();
    expect(screen.queryByLabelText('Your brand, website or story')).not.toBeInTheDocument();
    expect(screen.queryByRole('button',{name:'Continue proposal'})).not.toBeInTheDocument();
    expect(screen.getByLabelText('Business story')).toBeEnabled();expect(screen.getByLabelText('Interaction')).toBeEnabled();
    expect(screen.getByLabelText('Exact wording')).toHaveValue('  字\nCafé 🪁 ');
    expect(mocks.generate).toHaveBeenCalledOnce();
    fireEvent.change(screen.getByLabelText('Interaction'),{target:{value:'Press the sun to lift the scene'}});
    expect(loadProposalSession()?.context.interaction).toBe('Press the sun to lift the scene');
    expect(mocks.generate).toHaveBeenCalledOnce();
  });
  it('preserves a saved partial world and explicit recovery when later construction needs clarification',async()=>{
    mocks.generate.mockImplementation(async(body:ProposalRequest)=>{if(body.stage==='physical')throw new ProposalConstructionNeededError('Which part should the lever lift?');return fixture(body);});
    mount();await introduction();const original=loadProposalSession()!;
    fireEvent.click(screen.getByRole('button',{name:'Generate my proposal'}));await screen.findByText('Which part should the lever lift?');
    expect(loadProposalSession()?.context).toEqual(original.context);expect(loadProposalSession()?.turns).toEqual(original.turns);
    expect(loadProposalSession()?.pending?.assets).toEqual({world:ids.world});
    expect(localStorage.getItem(`offkin:proposal-asset:${ids.world}`)).not.toBeNull();
    expect(screen.getByRole('heading',{name:'Paper world'})).toBeInTheDocument();
    expect(screen.getByRole('button',{name:'Continue proposal'})).toBeEnabled();
    expect(screen.getByRole('button',{name:'Discard unfinished version'})).toBeEnabled();
    expect(screen.getByLabelText('Interaction')).toBeDisabled();
    expect(screen.queryByText('What should this world say about your business?')).not.toBeInTheDocument();
    expect(mocks.generate.mock.calls.map(([body])=>body.stage)).toEqual(['world','physical']);
  });
  it('preserves the accepted version and pending revision on construction clarification before a new world',async()=>{
    mount();await complete();const original=loadProposalSession()!;const originalImages=screen.getAllByRole('img').map(image=>image.getAttribute('src'));
    mocks.plan.mockImplementation(async body=>({plan:{scope:'world',context:{...body.context,revisionNotes:'Press a sun to open a scene'},summary:'Create a new sun world.'}}));
    mocks.generate.mockRejectedValueOnce(new ProposalConstructionNeededError('Should the scene hinge or slide open?'));
    fireEvent.change(screen.getByLabelText('Change your proposal'),{target:{value:'Press a sun to open a scene'}});
    fireEvent.click(screen.getByRole('button',{name:'Update proposal'}));await reconfirmConstruction('Proposed press/reveal with manual lift reset');await screen.findByText('Should the scene hinge or slide open?');
    expect(loadProposalSession()?.accepted).toEqual(original.accepted);expect(loadProposalSession()?.context).toEqual(original.context);
    expect(loadProposalSession()?.pending).toMatchObject({scope:'world',assets:{},previous:ids,instruction:'Press a sun to open a scene'});
    expect(screen.getAllByRole('img').map(image=>image.getAttribute('src'))).toEqual(originalImages);
    expect(screen.getByRole('button',{name:'Discard unfinished version'})).toBeEnabled();
    expect(screen.queryByText('What should this world say about your business?')).not.toBeInTheDocument();expect(mocks.generate).toHaveBeenCalledTimes(5);
  });
  it('ignores construction clarification arriving after Stop without discarding the pending request',async()=>{
    const gate=deferred<void>();mocks.generate.mockImplementationOnce(async()=>{await gate.promise;throw new ProposalConstructionNeededError('Should the panel slide?');});
    mount();await introduction();fireEvent.click(screen.getByRole('button',{name:'Generate my proposal'}));
    const pending=loadProposalSession()?.pending;fireEvent.click(screen.getByRole('button',{name:'Stop'}));
    await act(async()=>{gate.resolve();});
    expect(loadProposalSession()?.pending).toEqual(pending);expect(screen.queryByText(/Should the panel slide/)).not.toBeInTheDocument();
    expect(screen.getByText(/Stopped\. Finished sections are saved/)).toBeInTheDocument();expect(mocks.generate).toHaveBeenCalledOnce();
  });
  it('requires explicit packaging confirmation after protected-scope rejection and generates exactly one matching revision',async()=>{mount();await complete();const original=loadProposalSession()!.accepted!;const text='Keep the object and the world exactly as they are. Make only the packaging deep navy blue.';mocks.plan.mockRejectedValueOnce(new Error('The packaging revision also changed the physical concept. Your proposal is unchanged.'));fireEvent.change(screen.getByLabelText('Change your proposal'),{target:{value:text}});fireEvent.click(screen.getByRole('button',{name:'Update proposal'}));await screen.findByRole('region',{name:'Confirm packaging-only change'});expect(mocks.generate).toHaveBeenCalledTimes(4);expect(loadProposalSession()!.accepted).toEqual(original);mocks.generate.mockImplementation(async(body:ProposalRequest)=>fixture(body,{id:'00000000-0000-4000-8000-000000000024',image:'https://images.example/recovered-package.png'}));fireEvent.click(screen.getByRole('button',{name:'Update packaging only'}));await waitFor(()=>expect(loadProposalSession()?.accepted?.assets.packaging).toBe('00000000-0000-4000-8000-000000000024'));expect(mocks.generate).toHaveBeenCalledTimes(5);expect(mocks.generate.mock.calls[4][0]).toMatchObject({stage:'packaging',sourceWorldId:original.assets.world,sourcePhysicalId:original.assets.physical,previousAssetId:original.assets.packaging,context:{...original.context,revisionNotes:text}});expect(loadProposalSession()?.accepted?.assets).toEqual({...original.assets,packaging:'00000000-0000-4000-8000-000000000024'});expect(mocks.plan).toHaveBeenCalledOnce();});
  it('lets the user dismiss packaging recovery without generating or changing accepted data',async()=>{mount();await complete();const original=loadProposalSession()!.accepted;mocks.plan.mockRejectedValueOnce(new Error('The packaging revision also changed the physical concept. Your proposal is unchanged.'));fireEvent.change(screen.getByLabelText('Change your proposal'),{target:{value:'Keep the object; navy packaging only.'}});fireEvent.click(screen.getByRole('button',{name:'Update proposal'}));await screen.findByRole('button',{name:'Update packaging only'});fireEvent.click(screen.getByRole('button',{name:'Go back to my change'}));expect(screen.getByLabelText('Change your proposal')).toHaveValue('Keep the object; navy packaging only.');expect(loadProposalSession()!.accepted).toEqual(original);expect(mocks.generate).toHaveBeenCalledTimes(4);});
  it('clears the previous clarification when an explicitly confirmed packaging recovery completes',async()=>{mount();await complete();mocks.plan.mockResolvedValueOnce({clarification:'Do you mean the object or packaging?'}).mockRejectedValueOnce(new Error('The packaging revision also changed the physical concept. Your proposal is unchanged.'));fireEvent.change(screen.getByLabelText('Change your proposal'),{target:{value:'Make it blue'}});fireEvent.click(screen.getByRole('button',{name:'Update proposal'}));await screen.findAllByText('Do you mean the object or packaging?');fireEvent.change(screen.getByLabelText('Change your proposal'),{target:{value:'Only the packaging'}});fireEvent.click(screen.getByRole('button',{name:'Update proposal'}));await screen.findByRole('button',{name:'Update packaging only'});mocks.generate.mockImplementation(async(body:ProposalRequest)=>fixture(body,{id:'00000000-0000-4000-8000-000000000024'}));fireEvent.click(screen.getByRole('button',{name:'Update packaging only'}));await waitFor(()=>expect(loadProposalSession()?.accepted?.assets.packaging).toBe('00000000-0000-4000-8000-000000000024'));mocks.plan.mockResolvedValueOnce({clarification:'Which part of the world?'});fireEvent.change(screen.getByLabelText('Change your proposal'),{target:{value:'Make the world more open'}});fireEvent.click(screen.getByRole('button',{name:'Update proposal'}));await waitFor(()=>expect(mocks.plan).toHaveBeenCalledTimes(3));expect(mocks.plan.mock.calls[2][0].instruction).toBe('Make the world more open');});
  it('prevents duplicate packaging confirmation and ignores a stopped late image',async()=>{mount();await complete();const original=loadProposalSession()!.accepted;mocks.plan.mockRejectedValueOnce(new Error('The packaging revision also changed the physical concept. Your proposal is unchanged.'));fireEvent.change(screen.getByLabelText('Change your proposal'),{target:{value:'Navy packaging only'}});fireEvent.click(screen.getByRole('button',{name:'Update proposal'}));const confirm=await screen.findByRole('button',{name:'Update packaging only'});const gate=deferred<ProposalConcept>();mocks.generate.mockImplementationOnce(()=>gate.promise);fireEvent.click(confirm);fireEvent.click(confirm);expect(mocks.generate).toHaveBeenCalledTimes(5);const body=mocks.generate.mock.calls[4][0];const signal=mocks.generate.mock.calls[4][1];fireEvent.click(screen.getByRole('button',{name:'Stop'}));expect(signal.aborted).toBe(true);await act(async()=>{gate.resolve(fixture(body,{id:'00000000-0000-4000-8000-000000000024'}));});expect(loadProposalSession()!.accepted).toEqual(original);expect(mocks.generate).toHaveBeenCalledTimes(5);});
  it('clears an unconfirmed packaging recovery on newer navigation',async()=>{mount('/?proposal=1',true);await complete();mocks.plan.mockRejectedValueOnce(new Error('The packaging revision also changed the physical concept. Your proposal is unchanged.'));fireEvent.change(screen.getByLabelText('Change your proposal'),{target:{value:'Navy packaging only'}});fireEvent.click(screen.getByRole('button',{name:'Update proposal'}));await screen.findByRole('button',{name:'Update packaging only'});fireEvent.click(screen.getByRole('link',{name:'Newer route'}));await waitFor(()=>expect(screen.queryByRole('button',{name:'Update packaging only'})).not.toBeInTheDocument());expect(mocks.generate).toHaveBeenCalledTimes(4);});
  it('asks a single clarification and does not generate an ambiguous change',async()=>{mount();await complete();mocks.plan.mockResolvedValue({clarification:'Do you mean the box or the object?'});fireEvent.change(screen.getByLabelText('Change your proposal'),{target:{value:'Make it blue'}});fireEvent.click(screen.getByRole('button',{name:'Update proposal'}));await screen.findAllByText('Do you mean the box or the object?');expect(mocks.generate).toHaveBeenCalledTimes(4);expect(loadProposalSession()?.accepted?.assets).toEqual(ids);});
  it('restores saved images without generation even when generation is unavailable',async()=>{saveProposalSession(saved());mocks.ready.mockResolvedValue(false);mount();fireEvent.click(screen.getByRole('button',{name:'Continue saved proposal'}));await screen.findByRole('heading',{name:'Paper packaging'});expect(mocks.restore).toHaveBeenCalledTimes(4);expect(mocks.generate).not.toHaveBeenCalled();expect(screen.getAllByRole('img')).toHaveLength(4);});
  it('defaults sharing to text-only and requires separate original-metadata opt-in',async()=>{mount();await complete();fireEvent.click(screen.getByRole('button',{name:'Share'}));const d=within(screen.getByRole('dialog'));expect(d.getByRole('checkbox')).not.toBeChecked();fireEvent.click(d.getByRole('button',{name:'Create reviewed link'}));const link=d.getByRole('textbox',{name:'Share link'}) as HTMLInputElement;expect(decodeProposalShare(new URL(link.value).hash)?.accepted).toBeNull();fireEvent.click(d.getByRole('checkbox'));expect(d.getByText(/including details removed/)).toBeInTheDocument();expect(d.getAllByText(/Review original/)).toHaveLength(4);fireEvent.click(d.getByRole('button',{name:'Create reviewed link'}));const imageLink=d.getByRole('textbox',{name:'Share link'}) as HTMLInputElement;expect(decodeProposalShare(new URL(imageLink.value).hash)?.accepted?.assets).toEqual(ids);expect(imageLink.value).not.toContain('images.example');});
  it('imports reviewed text as an independent branch without generating',async()=>{const s=emptyProposalSession();s.context.business='A shared personal paper story';const hash=encodeProposalShare(s);mount('/'+hash);expect(screen.getByRole('dialog')).toBeInTheDocument();expect(loadProposalSession()).toBeNull();fireEvent.click(screen.getByRole('button',{name:'Open my editable version'}));await waitFor(()=>expect(screen.queryByRole('dialog')).not.toBeInTheDocument());expect(loadProposalSession()?.context.business).toBe(s.context.business);expect(loadProposalSession()?.id).not.toBe(s.id);expect(mocks.generate).not.toHaveBeenCalled();});
  it('switches the ordinary public root only when the full capability is ready',async()=>{mount('/');await screen.findByLabelText('Your brand, website or story');expect(screen.queryByRole('button',{name:'Generate my brand world'})).not.toBeInTheDocument();});
  it('keeps the earlier working root with a truthful notice until backend verification',async()=>{mocks.ready.mockResolvedValue(false);mount('/');await screen.findByText(/This earlier canvas creates world and physical studies only/);expect(screen.getByRole('button',{name:'Generate my brand world'})).toBeInTheDocument();expect(screen.getByRole('link',{name:'Open a saved complete proposal'})).toHaveAttribute('href','/?proposal=1');});
  it('bounds a hung root capability check and ignores its late reply',async()=>{vi.useFakeTimers();const gate=deferred<boolean>();mocks.ready.mockImplementationOnce(()=>gate.promise);mount('/');expect(screen.getByText('Opening your creative studio…')).toBeInTheDocument();await act(async()=>{vi.advanceTimersByTime(6000);});expect(screen.getByText(/This earlier canvas creates world and physical studies only/)).toBeInTheDocument();await act(async()=>{gate.resolve(true);});expect(screen.getByRole('button',{name:'Generate my brand world'})).toBeInTheDocument();});
  it('imports a reviewed proposal even when generation readiness is disabled',async()=>{mocks.ready.mockResolvedValue(false);const s=emptyProposalSession();s.context.business='Offline shared direction';mount('/'+encodeProposalShare(s));fireEvent.click(screen.getByRole('button',{name:'Open my editable version'}));await waitFor(()=>expect(loadProposalSession()?.context.business).toBe('Offline shared direction'));expect(screen.queryByRole('dialog')).not.toBeInTheDocument();expect(screen.queryByText(/This earlier canvas creates/)).not.toBeInTheDocument();expect(mocks.generate).not.toHaveBeenCalled();});
  it('keeps the v9 canvas route available separately',()=>{mount('/?canvas=legacy');expect(screen.getByRole('button',{name:'Generate my brand world'})).toBeInTheDocument();expect(screen.queryByRole('button',{name:'Generate my proposal'})).not.toBeInTheDocument();});
});
