import { act, cleanup, fireEvent, render, screen, waitFor, within } from '@testing-library/react';
import { MemoryRouter, Link, useNavigate } from 'react-router-dom';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import Index from '@/pages/Index';
import { forgetPilotInvite, rememberPilotAccess, setPilotInvite } from '@/lib/pilot-access';
import { PROPOSAL_SESSION_KEY, decodeProposalShare, emptyProposalSession, encodeProposalShare, loadProposalSession, pendingProposal, saveProposalSession, type ProposalSession } from '@/lib/proposal-session';
import { ProposalConstructionNeededError, ProposalContextNeededError } from '@/lib/proposal-api';
import type { ProposalConcept, ProposalRequest, ProposalStage } from '@/lib/proposal-api';
const mocks=vi.hoisted(()=>({generate:vi.fn(),restore:vi.fn(),plan:vi.fn(),ready:vi.fn(),website:vi.fn(),discovery:vi.fn(),paused:false,simple:false}));
vi.mock('@/lib/proposal-availability',async original=>({...await original<object>(),get PROPOSAL_GENERATION_PAUSED(){return mocks.paused;},get PROPOSAL_SIMPLE_MODE(){return mocks.simple;}}));
vi.mock('@/lib/proposal-api',async original=>({...await original<object>(),requestProposalAsset:mocks.generate,restoreProposalAsset:mocks.restore,planProposalRevision:mocks.plan,supportsProposalGeneration:mocks.ready}));
vi.mock('@/lib/brand-discovery',async original=>({...await original<object>(),requestBrandDiscovery:mocks.discovery}));
vi.mock('@/lib/concept-api',()=>({requestConcept:mocks.website}));
vi.mock('@/integrations/supabase/client',()=>({supabase:{from:()=>({select:async()=>({data:[{key:'site_title',value:'OFFKIN'}]})})}}));
const ids:Record<ProposalStage,string>={world:'00000000-0000-4000-8000-000000000001',physical:'00000000-0000-4000-8000-000000000002',details:'00000000-0000-4000-8000-000000000003',packaging:'00000000-0000-4000-8000-000000000004'};
const elements=[{id:'house',label:'Paper house',description:'A proposed paper neighbourhood.',kind:'proposal' as const},{id:'path',label:'Ribbon path',description:'A proposed connecting path.',kind:'proposal' as const}];
function fixture(body:ProposalRequest,overrides:Partial<ProposalConcept>={}):ProposalConcept{const {previousAssetId:_previous,...publicBody}=body;return {...publicBody,stageVersion:'proposal-assets-v1',id:ids[body.stage],brand:body.customerIdentity?.name||'Paper Studio',title:`Paper ${body.stage}`,story:`A new ${body.stage} made for this customer.`,design:'Rich connected paper design.',interaction:'Turn to reveal another story.',image:`https://images.example/${body.stage}.png`,sourceUrl:'',sourceTitle:'',worldElements:elements,sourceImageIds:[...(body.stage==='physical'?[body.sourceWorldId!]:body.stage==='details'?[body.sourcePhysicalId!]:body.stage==='packaging'?[body.sourcePhysicalId!,body.sourceWorldId!]:[])],...(body.stage==='details'||body.stage==='packaging'?{selectedElementIds:['house','path'],heroElementId:'house',replacements:[]}:{}),...overrides};}
function saved():ProposalSession{const s=emptyProposalSession();s.context.business='We create personalised paper gifts';s.accepted={id:'accepted',context:s.context,website:'',assets:{...ids},selected:['house','path'],hero:'house',replacements:[]};return s;}
function deferred<T>(){let resolve!:(v:T)=>void;const promise=new Promise<T>(done=>{resolve=done;});return {resolve,promise};}
function Navigation(){const navigate=useNavigate();return <nav><Link to="/?next=1">Newer route</Link><button onClick={()=>navigate(-1)}>Back</button></nav>;}
function mount(path='/?proposal=1',nav=false){return render(<MemoryRouter initialEntries={[path]}>{nav&&<Navigation/>}<Index/></MemoryRouter>);}
async function introduction(){if(mocks.simple){fireEvent.click(screen.getByText('Prefer to describe your idea?'));fireEvent.change(screen.getByLabelText('Brand or project name'),{target:{value:'Fable Finch'}});fireEvent.change(screen.getByLabelText('Your story'),{target:{value:'We create personalised paper gifts'}});await waitFor(()=>expect(screen.getByRole('button',{name:'Create from my story'})).toBeEnabled());return;}fireEvent.change(screen.getByLabelText('Your brand, website or story'),{target:{value:'We create personalised paper gifts'}});fireEvent.click(screen.getByRole('button',{name:/Explore my brand|Continue conversation/}));fireEvent.click(screen.getByRole('button',{name:'Clients & partners'}));fireEvent.change(screen.getByLabelText('Exact brand name'),{target:{value:'Fable Finch'}});await waitFor(()=>expect(screen.getByRole('button',{name:'Generate my proposal'})).toBeEnabled());}
async function complete(){await introduction();fireEvent.click(screen.getByRole('button',{name:mocks.simple?'Create from my story':'Generate my proposal'}));await screen.findByRole('heading',{name:'Paper packaging'});await waitFor(()=>expect(screen.getByRole('button',{name:'Update proposal'})).toBeInTheDocument());}
beforeEach(()=>{forgetPilotInvite();mocks.paused=false;mocks.simple=false;localStorage.clear();vi.clearAllMocks();mocks.ready.mockResolvedValue(true);mocks.generate.mockImplementation(async(body:ProposalRequest)=>fixture(body));mocks.restore.mockImplementation(async(id:string)=>{const stage=Object.keys(ids).find(stage=>ids[stage]===id) as ProposalStage;const s=saved();return fixture({contractVersion:'offkin-proposal-v10',stage,brand:'no-website',context:s.context,...(stage!=='world'?{sourceWorldId:ids.world,selectedElementIds:['house','path'],heroElementId:'house',replacements:[]}:{}),...(['details','packaging'].includes(stage)?{sourcePhysicalId:ids.physical}:{})});});mocks.plan.mockImplementation(async body=>({plan:{scope:'packaging',context:{...body.context,revisionNotes:'Packaging deep blue; object unchanged'},summary:'Keep your world and object. Make only the packaging deep blue.'}}));});
afterEach(async()=>{await act(async()=>{});cleanup();forgetPilotInvite();vi.useRealTimers();vi.restoreAllMocks();});
describe('Complete proposal journey',()=>{
  it('asks for an exact name without deriving it from business prose, motifs or website evidence',async()=>{
    mount();fireEvent.change(screen.getByLabelText('Your brand, website or story'),{target:{value:'Fable Finch brings the Sunbeam community together'}});fireEvent.click(screen.getByRole('button',{name:'Explore my brand'}));fireEvent.click(screen.getByRole('button',{name:'Clients & partners'}));fireEvent.change(screen.getByLabelText('Brand identifiers & colours'),{target:{value:'Sunbeam nameplate and orange rays'}});
    const name=screen.getByRole('textbox',{name:'Exact brand name'});expect(name).toHaveValue('');expect(name.closest('details')).toBeNull();expect(name).toHaveAttribute('maxlength','120');expect(loadProposalSession()?.customerIdentity).toBeUndefined();expect(screen.getByRole('button',{name:'Generate my proposal'})).toBeDisabled();expect(mocks.generate).not.toHaveBeenCalled();
    fireEvent.change(name,{target:{value:'   '}});expect(name).toHaveValue('   ');expect(screen.getByRole('button',{name:'Generate my proposal'})).toBeDisabled();
    fireEvent.change(name,{target:{value:'  Fable Finch 字 Café 🪁  '}});await waitFor(()=>expect(screen.getByRole('button',{name:'Generate my proposal'})).toBeEnabled());expect(mocks.generate).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Generate my proposal'}));await screen.findByRole('button',{name:'Update proposal'});
    const identity={version:'customer-brand-v1',name:'  Fable Finch 字 Café 🪁  '};for(const [body] of mocks.generate.mock.calls)expect(body).toMatchObject({brand:'no-website',customerIdentity:identity});expect(loadProposalSession()?.customerIdentity).toEqual(identity);expect(loadProposalSession()?.accepted?.customerIdentity).toEqual(identity);
  });
  it('shows the reviewed exact identity in shares and preserves it in an independent text branch',async()=>{
    const s=emptyProposalSession();s.customerIdentity={version:'customer-brand-v1',name:'  Fable Finch 字 Café 🪁  '};s.context.business='A fictional paper-gift studio';
    mount('/'+encodeProposalShare(s));expect(within(screen.getByRole('dialog')).getByText(/Exact brand name:/)).toHaveTextContent('Fable Finch 字 Café 🪁');fireEvent.click(screen.getByRole('button',{name:'Open my editable version'}));await waitFor(()=>expect(screen.queryByRole('dialog')).not.toBeInTheDocument());expect(screen.getByLabelText('Exact brand name')).toHaveValue(s.customerIdentity.name);expect(loadProposalSession()?.customerIdentity).toEqual(s.customerIdentity);expect(mocks.generate).not.toHaveBeenCalled();
  });
  it('requires an exact name for a legacy saved world revision and preserves the old complete version',async()=>{
    const s=saved();saveProposalSession(s);mount();fireEvent.click(screen.getByRole('button',{name:'Continue saved proposal'}));await screen.findByRole('button',{name:'Update proposal'});const old=loadProposalSession()!.accepted;
    mocks.plan.mockImplementationOnce(async body=>({plan:{scope:'world',context:{...body.context,business:'A new paper community story'},summary:'Build a new story world.'}}));fireEvent.change(screen.getByLabelText('Change your proposal'),{target:{value:'Tell a new story'}});fireEvent.click(screen.getByRole('button',{name:'Update proposal'}));await screen.findByRole('button',{name:'Continue proposal'});
    expect(screen.getByLabelText('Exact brand name')).toHaveValue('');expect(screen.getByRole('button',{name:'Continue proposal'})).toBeDisabled();expect(mocks.generate).not.toHaveBeenCalled();fireEvent.change(screen.getByLabelText('Exact brand name'),{target:{value:'Fable Finch'}});expect(loadProposalSession()?.accepted).toEqual(old);expect(loadProposalSession()?.customerIdentity).toBeUndefined();fireEvent.click(screen.getByRole('button',{name:'Continue proposal'}));await screen.findByRole('button',{name:'Update proposal'});expect(mocks.generate.mock.calls.map(([body])=>body.stage)).toEqual(['world','physical','details','packaging']);expect(loadProposalSession()?.accepted?.customerIdentity?.name).toBe('Fable Finch');
  });
  it('changes a completed brand name only through a new full world closure, with explicit generation confirmation',async()=>{
    mount();await complete();const old=loadProposalSession()!.accepted;
    fireEvent.change(screen.getByLabelText('Exact brand name'),{target:{value:'  Orchard Lantern 字  '}});expect(loadProposalSession()?.accepted).toEqual(old);expect(loadProposalSession()?.customerIdentity?.name).toBe('Fable Finch');expect(mocks.generate).toHaveBeenCalledTimes(4);
    fireEvent.click(screen.getByRole('button',{name:'Start new brand direction'}));await screen.findByRole('button',{name:'Continue proposal'});expect(mocks.plan).not.toHaveBeenCalled();expect(loadProposalSession()?.pending).toMatchObject({scope:'world',assets:{},customerIdentity:{version:'customer-brand-v1',name:'  Orchard Lantern 字  '}});expect(loadProposalSession()?.accepted).toEqual(old);expect(screen.getByRole('button',{name:'Continue proposal'})).toBeEnabled();
    const changedIds={world:'00000000-0000-4000-8000-000000000011',physical:'00000000-0000-4000-8000-000000000012',details:'00000000-0000-4000-8000-000000000013',packaging:'00000000-0000-4000-8000-000000000014'};mocks.generate.mockImplementation(async(body:ProposalRequest)=>fixture(body,{id:changedIds[body.stage]}));const gate=deferred<ProposalConcept>();mocks.generate.mockImplementationOnce(()=>gate.promise);fireEvent.click(screen.getByRole('button',{name:'Continue proposal'}));expect(mocks.generate).toHaveBeenCalledTimes(5);expect(loadProposalSession()?.accepted).toEqual(old);const world=mocks.generate.mock.calls[4][0];expect(world).toMatchObject({stage:'world',previousAssetId:ids.world,customerIdentity:{version:'customer-brand-v1',name:'  Orchard Lantern 字  '}});
    await act(async()=>{gate.resolve(fixture(world,{id:changedIds.world}));});await screen.findByRole('button',{name:'Update proposal'});expect(mocks.generate.mock.calls.slice(4).map(([body])=>body.stage)).toEqual(['world','physical','details','packaging']);for(const [body] of mocks.generate.mock.calls.slice(4))expect(body.customerIdentity).toEqual(world.customerIdentity);expect(loadProposalSession()?.accepted?.customerIdentity).toEqual(world.customerIdentity);expect(loadProposalSession()?.customerIdentity).toEqual(world.customerIdentity);
  });

  it('previews without forcing a construction grammar or part-count choice',async()=>{
    mount();await introduction();
    expect(screen.queryByRole('group',{name:'Choose construction action'})).not.toBeInTheDocument();
    expect(screen.queryByRole('button',{name:'Static display'})).not.toBeInTheDocument();
    fireEvent.change(screen.getByLabelText('Interaction'),{target:{value:'Explore a playful spiral discovery with lights'}});
    fireEvent.change(screen.getByLabelText('Exact wording'),{target:{value:'  Keep every detail  '}});
    expect(screen.getByRole('button',{name:'Generate my proposal'})).toBeEnabled();
    expect(mocks.generate).not.toHaveBeenCalled();
    fireEvent.click(screen.getByRole('button',{name:'Generate my proposal'}));await screen.findByRole('button',{name:'Update proposal'});
    expect(mocks.generate).toHaveBeenCalledTimes(4);
    for(const [request] of mocks.generate.mock.calls){expect(request).not.toHaveProperty('constructionIntent');expect(request.context.interaction).toBe('Explore a playful spiral discovery with lights');expect(request.context.exactWording).toBe('  Keep every detail  ');}
  });
  it.each(['Business story','Audience','Story direction','Brand identifiers & colours','Visual style','Exact wording','Interaction','Public website'])('keeps %s edits creative without silently generating',async label=>{
    mount();await introduction();fireEvent.change(screen.getByLabelText(label),{target:{value:label==='Public website'?'https://fable.example':'A changed rich direction'}});
    expect(screen.getByRole('button',{name:'Generate my proposal'})).toBeEnabled();expect(mocks.generate).not.toHaveBeenCalled();
  });
  it('preserves partial legacy assets and offers explicit continuation without inventing new assembly intent',async()=>{
    const s=emptyProposalSession();s.context.business='A saved partial story';s.pending={...pendingProposal(s,'world',s.context),assets:{world:ids.world},selected:['house','path'],hero:'house'};saveProposalSession(s);
    mount();fireEvent.click(screen.getByRole('button',{name:'Continue saved proposal'}));await screen.findByRole('heading',{name:'Paper world'});
    expect(screen.getByRole('button',{name:'Continue proposal'})).toBeEnabled();expect(mocks.generate).not.toHaveBeenCalled();
    fireEvent.click(screen.getByRole('button',{name:'Continue proposal'}));await screen.findByRole('button',{name:'Update proposal'});
    expect(mocks.generate.mock.calls.map(([body])=>body.stage)).toEqual(['physical','details','packaging']);
    for(const [request] of mocks.generate.mock.calls)expect(request).not.toHaveProperty('constructionIntent');
  });
  it('preserves accepted imagery and selection while a requested physical revision is pending',async()=>{
    mount();await complete();const accepted=loadProposalSession()!.accepted;const gate=deferred<ProposalConcept>();mocks.generate.mockImplementationOnce(()=>gate.promise);
    mocks.plan.mockImplementation(async body=>({plan:{scope:'physical',context:{...body.context,revisionNotes:'Use the path as hero'},summary:'Use the path as the product hero.',selectedElementIds:['path'],heroElementId:'path',replacements:[{id:'path',label:'Folded trail',description:'A folded trail replaces the ribbon.'}]}}));
    fireEvent.change(screen.getByLabelText('Change your proposal'),{target:{value:'Use the path as hero'}});fireEvent.click(screen.getByRole('button',{name:'Update proposal'}));
    await waitFor(()=>expect(mocks.generate).toHaveBeenCalledTimes(5));expect(loadProposalSession()?.accepted).toEqual(accepted);expect(loadProposalSession()?.pending).toMatchObject({selected:['path'],hero:'path',replacements:[{id:'path',label:'Folded trail',description:'A folded trail replaces the ribbon.'}]});
    expect(mocks.generate.mock.calls[4][0]).not.toHaveProperty('constructionIntent');fireEvent.click(screen.getByRole('button',{name:'Stop'}));fireEvent.click(screen.getByRole('button',{name:'Discard unfinished version'}));expect(loadProposalSession()?.accepted).toEqual(accepted);
  });

  it('keeps saved-resume UI outside the separate headline, form and artwork grid items',async()=>{saveProposalSession(saved());mount();await act(async()=>{});const opening=document.querySelector('.op-opening')!;for(const selector of ['.op-intro','.op-entry-panel','.op-hero-art'])expect(document.querySelector(selector)?.parentElement).toBe(opening);const resume=document.querySelector('.op-resume')!;expect(opening.contains(resume)).toBe(false);expect(resume.compareDocumentPosition(opening)&Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy();expect(screen.getByRole('button',{name:'Explore my brand'})).toBeInTheDocument();expect(mocks.generate).not.toHaveBeenCalled();});

  it('matches the entry button accessible name to its visible label',async()=>{mount();const button=screen.getByRole('button',{name:'Explore my brand'});expect(button).toHaveTextContent('Explore my brand');await act(async()=>{});});
  it.each(['Enlarge collectible','Open collectible image'])('returns image dialog focus to %s after Escape',async(name)=>{saveProposalSession(saved());mount();fireEvent.click(screen.getByRole('button',{name:'Continue saved proposal'}));await screen.findByRole('heading',{name:'Paper packaging'});const trigger=screen.getByRole('button',{name});fireEvent.click(trigger);const dialog=await screen.findByRole('dialog');fireEvent.keyDown(dialog,{key:'Escape',code:'Escape'});await waitFor(()=>expect(screen.queryByRole('dialog')).not.toBeInTheDocument());await waitFor(()=>expect(trigger).toHaveFocus());});
  it('returns share dialog focus to Share after Close',async()=>{saveProposalSession(saved());mount();fireEvent.click(screen.getByRole('button',{name:'Continue saved proposal'}));await screen.findByRole('heading',{name:'Paper packaging'});const trigger=screen.getByRole('button',{name:'Share'});fireEvent.click(trigger);const dialog=await screen.findByRole('dialog');fireEvent.click(within(dialog).getByRole('button',{name:'Close'}));await waitFor(()=>expect(screen.queryByRole('dialog')).not.toBeInTheDocument());await waitFor(()=>expect(trigger).toHaveFocus());});
  it('focuses the main content after completing a shared import',async()=>{const s=emptyProposalSession();s.context.business='Shared design direction';mount('/'+encodeProposalShare(s));fireEvent.click(screen.getByRole('button',{name:'Open my editable version'}));await waitFor(()=>expect(screen.queryByRole('dialog')).not.toBeInTheDocument());await waitFor(()=>expect(document.getElementById('proposal-main')).toHaveFocus());expect(mocks.generate).not.toHaveBeenCalled();});

  it('preserves an explicit display-only choice without inventing an interaction',async()=>{mount();await introduction();fireEvent.change(screen.getByLabelText('Interaction'),{target:{value:'Display only'}});fireEvent.click(screen.getByRole('button',{name:'Generate my proposal'}));await waitFor(()=>expect(mocks.generate).toHaveBeenCalledTimes(4));for(const [request] of mocks.generate.mock.calls)expect(request.context.interaction).toBe('Display only');});

  it('keeps in-page navigation out of route history and does not abort an active proposal',async()=>{Element.prototype.scrollIntoView=vi.fn();mount();await introduction();const gate=deferred<ProposalConcept>();mocks.generate.mockImplementationOnce(()=>gate.promise);fireEvent.click(screen.getByRole('button',{name:'Generate my proposal'}));const signal=mocks.generate.mock.calls[0][1];expect(fireEvent.click(screen.getByRole('link',{name:'Skip to your proposal'}))).toBe(false);expect(fireEvent.click(within(screen.getByRole('banner')).getByRole('link',{name:'Start your world'}))).toBe(false);expect(signal.aborted).toBe(false);const body=mocks.generate.mock.calls[0][0];await act(async()=>gate.resolve(fixture(body)));await screen.findByRole('button',{name:'Update proposal'});expect(mocks.generate).toHaveBeenCalledTimes(4);});

  it('presents nearby concept studies without seeding the customer state',async()=>{mount();expect(screen.getByRole('heading',{level:1})).toHaveTextContent('Your business DNA. Made collectible.');expect(screen.getByRole('region',{name:'A little inspiration.'})).toBeInTheDocument();expect(screen.getByRole('textbox',{name:'Your brand, website or story'})).toBeEnabled();expect(screen.getAllByRole('img')).toHaveLength(3);expect(loadProposalSession()).toBeNull();expect(mocks.generate).not.toHaveBeenCalled();await act(async()=>{});});
  it('keeps all marketing navigation local and preserves the typed entry',async()=>{Element.prototype.scrollIntoView=vi.fn();mount();fireEvent.change(screen.getByLabelText('Your brand, website or story'),{target:{value:'Our solar community'}});const nav=within(screen.getByRole('navigation',{name:'Explore OFFKIN'}));for(const name of ['Worlds','Collectibles','How it works']){const link=nav.getByRole('link',{name});expect(fireEvent.click(link)).toBe(false);expect(document.querySelector(link.getAttribute('href')!)).toBeInTheDocument();}expect(screen.getByLabelText('Your brand, website or story')).toHaveValue('Our solar community');expect(mocks.generate).not.toHaveBeenCalled();await act(async()=>{});});
  it('removes marketing artwork from a restored customer result',async()=>{saveProposalSession(saved());mount();fireEvent.click(screen.getByRole('button',{name:'Continue saved proposal'}));await screen.findByRole('heading',{name:'Paper packaging'});expect(document.querySelectorAll('[data-marketing-art]')).toHaveLength(0);expect(screen.getAllByRole('img')).toHaveLength(4);expect(screen.queryByRole('heading',{name:'Collectible stories'})).not.toBeInTheDocument();expect(mocks.generate).not.toHaveBeenCalled();});

  it('preserves story-authored interaction without forcing a press-reveal template',async()=>{mount();const story='We connect a solar community. Press the sun to reveal the shared energy path.';fireEvent.change(screen.getByLabelText('Your brand, website or story'),{target:{value:story}});fireEvent.click(screen.getByRole('button',{name:/Explore my brand|Continue conversation/}));fireEvent.click(screen.getByRole('button',{name:'Clients & partners'}));expect(screen.getByRole('button',{name:'Generate my proposal'})).toBeDisabled();fireEvent.change(screen.getByLabelText('Exact brand name'),{target:{value:'Fable Finch'}});await waitFor(()=>expect(screen.getByRole('button',{name:'Generate my proposal'})).toBeEnabled());fireEvent.click(screen.getByRole('button',{name:'Generate my proposal'}));await waitFor(()=>expect(mocks.generate).toHaveBeenCalledTimes(4));expect(mocks.generate.mock.calls[0][0].context.business).toBe(story);expect(mocks.generate.mock.calls[0][0].context.interaction).toBe('');expect(mocks.generate.mock.calls[0][0]).not.toHaveProperty('constructionIntent');expect(JSON.stringify(mocks.generate.mock.calls[0][0].context)).not.toContain('Display only');});
  it('uses a result anchor after restore and keeps refinement editable while generation is paused',async()=>{saveProposalSession(saved());mocks.ready.mockResolvedValue(false);mount();fireEvent.click(screen.getByRole('button',{name:'Continue saved proposal'}));await screen.findByRole('heading',{name:'Paper packaging'});expect(screen.getByRole('link',{name:'Your preview'})).toHaveAttribute('href','#proposal-results');expect(document.getElementById('proposal-results')).toBeInTheDocument();expect(screen.getByRole('textbox',{name:'Change your proposal'})).toBeEnabled();expect(screen.getByRole('button',{name:'Update proposal'})).toBeDisabled();});

  it('keeps ordinary visitors in a truthful saved-brief shell during the temporary hold',async()=>{mocks.paused=true;mocks.ready.mockResolvedValue(false);mount('/');await screen.findByText(/New complete-proposal generation is temporarily unavailable/);expect(screen.getByRole('link',{name:'Earlier workflow: visual studies only'})).toHaveAttribute('href','/?canvas=legacy');fireEvent.change(screen.getByLabelText('Your brand, website or story'),{target:{value:'A physical gift for our partners'}});fireEvent.click(screen.getByRole('button',{name:/Explore my brand|Continue conversation/}));fireEvent.click(screen.getByRole('button',{name:'Clients & partners'}));expect(screen.getByRole('button',{name:'Generate my proposal'})).toBeDisabled();expect(screen.getByRole('button',{name:'Download brief'})).toBeEnabled();expect(mocks.generate).not.toHaveBeenCalled();});
  it('starts empty and keeps reference brands out of customer state',async()=>{mount();await waitFor(()=>expect(mocks.ready).toHaveBeenCalled());expect(screen.getByRole('heading',{level:1})).toHaveTextContent('Your business DNA. Made collectible.');expect(screen.getAllByRole('img')).toHaveLength(3);expect(screen.queryByRole('article',{name:/proposal/i})).not.toBeInTheDocument();expect(localStorage.getItem(PROPOSAL_SESSION_KEY)).toBeNull();expect(mocks.generate).not.toHaveBeenCalled();});
  it('generates all four genuine roles from one explicit action with actual saved lineage',async()=>{mount();await complete();expect(mocks.generate.mock.calls.map(([b])=>b.stage)).toEqual(['world','physical','details','packaging']);const bodies=mocks.generate.mock.calls.map(([b])=>b);expect(bodies[1]).toMatchObject({sourceWorldId:ids.world,selectedElementIds:['house','path'],heroElementId:'house'});expect(bodies[2]).toMatchObject({sourceWorldId:ids.world,sourcePhysicalId:ids.physical});expect(bodies[3]).toMatchObject({sourceWorldId:ids.world,sourcePhysicalId:ids.physical});expect(screen.getAllByRole('img')).toHaveLength(4);expect(loadProposalSession()?.accepted?.assets).toEqual(ids);expect(loadProposalSession()?.pending).toBeNull();});
  it('does not generate on typing, IME composition or audience selection',async()=>{mount();const input=screen.getByLabelText('Your brand, website or story');fireEvent.change(input,{target:{value:'纸世界 Café 🪁'}});fireEvent.keyDown(input,{key:'Enter',isComposing:true});expect(screen.getByText('What’s the business, brand or idea?')).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:/Explore my brand|Continue conversation/}));fireEvent.click(screen.getByRole('button',{name:'Let the story lead'}));expect(mocks.generate).not.toHaveBeenCalled();expect(loadProposalSession()?.context.business).toBe('纸世界 Café 🪁');});
  it('reads a URL only on the explicit website action',async()=>{mocks.website.mockResolvedValue({website:{url:'https://paper.example/',title:'Paper',excerpt:'We fold meaningful paper gifts.'}});mount();fireEvent.change(screen.getByLabelText('Your brand, website or story'),{target:{value:'https://paper.example'}});fireEvent.click(screen.getByRole('button',{name:/Explore my brand|Continue conversation/}));expect(mocks.website).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Read public website'}));await screen.findByText('We fold meaningful paper gifts.');expect(mocks.generate).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Use this business description'}));expect(loadProposalSession()?.context.business).toBe('We fold meaningful paper gifts.');});
  it('prevents duplicate generation clicks',async()=>{const gate=deferred<ProposalConcept>();mocks.generate.mockImplementationOnce(()=>gate.promise);mount();await introduction();const button=screen.getByRole('button',{name:'Generate my proposal'});fireEvent.click(button);fireEvent.click(button);expect(mocks.generate).toHaveBeenCalledOnce();await act(async()=>{gate.resolve(fixture(mocks.generate.mock.calls[0][0]));});await screen.findByRole('heading',{name:'Paper packaging'});expect(mocks.generate).toHaveBeenCalledTimes(4);});
  it('saves the first three sections and resumes only failed packaging',async()=>{let failed=false;mocks.generate.mockImplementation(async(body:ProposalRequest)=>{if(body.stage==='packaging'&&!failed){failed=true;throw new Error('Gateway paused');}return fixture(body);});mount();await introduction();fireEvent.click(screen.getByRole('button',{name:'Generate my proposal'}));await screen.findByText('Gateway paused');expect(loadProposalSession()?.pending?.assets).toEqual({world:ids.world,physical:ids.physical,details:ids.details});fireEvent.click(screen.getByRole('button',{name:'Continue proposal'}));await screen.findByRole('heading',{name:'Paper packaging'});expect(mocks.generate.mock.calls.map(([b])=>b.stage)).toEqual(['world','physical','details','packaging','packaging']);});
  it('ignores cancelled late output and never advances to another paid stage',async()=>{const gate=deferred<ProposalConcept>();mocks.generate.mockImplementationOnce(()=>gate.promise);mount();await introduction();fireEvent.click(screen.getByRole('button',{name:'Generate my proposal'}));const signal=mocks.generate.mock.calls[0][1];fireEvent.click(screen.getByRole('button',{name:'Stop'}));expect(signal.aborted).toBe(true);await act(async()=>{gate.resolve(fixture(mocks.generate.mock.calls[0][0]));});expect(mocks.generate).toHaveBeenCalledOnce();expect(loadProposalSession()?.pending?.assets).toEqual({});expect(screen.queryByRole('img',{name:/generated .* study/})).not.toBeInTheDocument();});
  it('cancels on newer navigation and ignores the stale response',async()=>{const gate=deferred<ProposalConcept>();mocks.generate.mockImplementationOnce(()=>gate.promise);mount('/?proposal=1',true);await introduction();fireEvent.click(screen.getByRole('button',{name:'Generate my proposal'}));const signal=mocks.generate.mock.calls[0][1];fireEvent.click(screen.getByRole('link',{name:'Newer route'}));expect(signal.aborted).toBe(true);await act(async()=>{gate.resolve(fixture(mocks.generate.mock.calls[0][0]));});expect(mocks.generate).toHaveBeenCalledOnce();expect(loadProposalSession()?.pending?.assets).toEqual({});});
  it('actually generates packaging revision while preserving accepted world, hero and details IDs',async()=>{mount();await complete();const replacement='00000000-0000-4000-8000-000000000014';mocks.generate.mockImplementation(async(body:ProposalRequest)=>fixture(body,{id:replacement,image:'https://images.example/blue-packaging.png'}));fireEvent.change(screen.getByLabelText('Change your proposal'),{target:{value:'Keep the object. Make the packaging deep blue.'}});fireEvent.click(screen.getByRole('button',{name:'Update proposal'}));await waitFor(()=>expect(loadProposalSession()?.accepted?.assets.packaging).toBe(replacement));expect(mocks.plan).toHaveBeenCalledOnce();expect(mocks.generate).toHaveBeenCalledTimes(5);expect(mocks.generate.mock.calls[4][0]).toMatchObject({stage:'packaging',previousAssetId:ids.packaging,sourceWorldId:ids.world,sourcePhysicalId:ids.physical});expect(loadProposalSession()?.accepted?.assets).toEqual({...ids,packaging:replacement});});
  it('retains accepted images throughout a partial revision and swaps only when complete',async()=>{mount();await complete();const gate=deferred<ProposalConcept>();mocks.plan.mockImplementation(async body=>({plan:{scope:'physical',context:{...body.context,revisionNotes:'Make the object a cafe'},summary:'Revise the object and dependent sections.'}}));mocks.generate.mockImplementation((body:ProposalRequest)=>body.stage==='packaging'?gate.promise:Promise.resolve(fixture(body,{id:ids[body.stage].replace('00000000000','00000000001'),image:`https://images.example/new-${body.stage}.png`})));
    fireEvent.change(screen.getByLabelText('Change your proposal'),{target:{value:'Make the object a cafe'}});fireEvent.click(screen.getByRole('button',{name:'Update proposal'}));await waitFor(()=>expect(mocks.generate).toHaveBeenCalledTimes(7));expect(screen.getAllByRole('img').map(i=>i.getAttribute('src'))).toContain('https://images.example/physical.png');expect(screen.queryByRole('img',{name:/new-physical/})).not.toBeInTheDocument();const body=mocks.generate.mock.calls[6][0];await act(async()=>{gate.resolve(fixture(body,{id:'00000000-0000-4000-8000-000000000014',image:'https://images.example/new-packaging.png'}));});await waitFor(()=>expect(loadProposalSession()?.pending).toBeNull());expect(screen.getAllByRole('img').map(i=>i.getAttribute('src'))).toContain('https://images.example/new-physical.png');});
  it('applies validated component replacements to the generated physical request',async()=>{mount();await complete();mocks.plan.mockImplementation(async body=>({plan:{scope:'physical',context:{...body.context,revisionNotes:'Replace house with a cafe'},summary:'Replace the house with a cafe.',selectedElementIds:['house','path'],heroElementId:'house',replacements:[{id:'house',label:'Paper cafe',description:'A welcoming cafe replaces the house.'}]}}));mocks.generate.mockImplementation(async(body:ProposalRequest)=>fixture(body,{id:ids[body.stage].replace('00000000000','00000000001')}));fireEvent.change(screen.getByLabelText('Change your proposal'),{target:{value:'Replace the house with a cafe'}});fireEvent.click(screen.getByRole('button',{name:'Update proposal'}));await waitFor(()=>expect(mocks.generate).toHaveBeenCalledTimes(7));expect(mocks.generate.mock.calls[4][0]).toMatchObject({stage:'physical',selectedElementIds:['house','path'],replacements:[{id:'house',label:'Paper cafe',description:'A welcoming cafe replaces the house.'}]});expect(loadProposalSession()?.accepted?.assets.world).toBe(ids.world);});
  it('reopens one business question when the generator needs facts before any image exists',async()=>{mocks.generate.mockRejectedValueOnce(new ProposalContextNeededError('Tell us what the business does.'));mount();await introduction();fireEvent.click(screen.getByRole('button',{name:'Generate my proposal'}));await screen.findByText('Tell us what the business does.');expect(screen.getByText('What should this world say about your business?')).toBeInTheDocument();expect(screen.getByLabelText('Your brand, website or story')).toBeEnabled();expect(loadProposalSession()?.pending).toBeNull();expect(mocks.generate).toHaveBeenCalledOnce();});
  it('returns fresh construction clarification to editable details without changing the brief or retrying',async()=>{
    mocks.generate.mockRejectedValueOnce(new ProposalConstructionNeededError('Should pressing the sun lift the scene or slide a panel?'));
    mount();await introduction();
    fireEvent.change(screen.getByLabelText('Exact wording'),{target:{value:'  字\nCafé 🪁 '}});
    fireEvent.change(screen.getByLabelText('Interaction'),{target:{value:'Press the sun to reveal a scene'}});
    fireEvent.change(screen.getByLabelText('Public website'),{target:{value:'https://paper.example'}});
    expect(screen.getByRole('button',{name:'Generate my proposal'})).toBeEnabled();
    const original=loadProposalSession();
    fireEvent.click(screen.getByRole('button',{name:'Generate my proposal'}));
    await screen.findByText(/Should pressing the sun lift the scene or slide a panel\? Review your direction under Edit details/);
    expect(loadProposalSession()).toEqual(original);
    expect(screen.getByRole('button',{name:'Generate my proposal'})).toBeEnabled();
    expect(screen.queryByText('What should this world say about your business?')).not.toBeInTheDocument();
    expect(screen.queryByLabelText('Your brand, website or story')).not.toBeInTheDocument();
    expect(screen.queryByRole('button',{name:'Continue proposal'})).not.toBeInTheDocument();
    expect(screen.getByLabelText('Business story')).toBeEnabled();expect(screen.getByLabelText('Interaction')).toBeEnabled();
    expect(screen.getByLabelText('Exact wording')).toHaveValue('  字\nCafé 🪁 ');
    expect(mocks.generate).toHaveBeenCalledOnce();
    fireEvent.change(screen.getByLabelText('Interaction'),{target:{value:'Press the sun to lift the scene'}});
    expect(loadProposalSession()?.context.interaction).toBe('Press the sun to lift the scene');
    expect(mocks.generate).toHaveBeenCalledOnce();
  });
  it('preserves a saved partial world and explicit recovery when later construction needs clarification',async()=>{
    mocks.generate.mockImplementation(async(body:ProposalRequest)=>{if(body.stage==='physical')throw new ProposalConstructionNeededError('Which part should the lever lift?');return fixture(body);});
    mount();await introduction();const original=loadProposalSession()!;
    fireEvent.click(screen.getByRole('button',{name:'Generate my proposal'}));await screen.findByText('Which part should the lever lift?');
    expect(loadProposalSession()?.context).toEqual(original.context);expect(loadProposalSession()?.turns).toEqual(original.turns);
    expect(loadProposalSession()?.pending?.assets).toEqual({world:ids.world});
    expect(localStorage.getItem(`offkin:proposal-asset:${ids.world}`)).not.toBeNull();
    expect(screen.getByRole('heading',{name:'Paper world'})).toBeInTheDocument();
    expect(screen.getByRole('button',{name:'Continue proposal'})).toBeEnabled();
    expect(screen.getByRole('button',{name:'Discard unfinished version'})).toBeEnabled();
    expect(screen.getByLabelText('Interaction')).toBeDisabled();
    expect(screen.queryByText('What should this world say about your business?')).not.toBeInTheDocument();
    expect(mocks.generate.mock.calls.map(([body])=>body.stage)).toEqual(['world','physical']);
  });
  it('preserves the accepted version and pending revision on construction clarification before a new world',async()=>{
    mount();await complete();const original=loadProposalSession()!;const originalImages=screen.getAllByRole('img').map(image=>image.getAttribute('src'));
    mocks.plan.mockImplementation(async body=>({plan:{scope:'world',context:{...body.context,revisionNotes:'Press a sun to open a scene'},summary:'Create a new sun world.'}}));
    mocks.generate.mockRejectedValueOnce(new ProposalConstructionNeededError('Should the scene hinge or slide open?'));
    fireEvent.change(screen.getByLabelText('Change your proposal'),{target:{value:'Press a sun to open a scene'}});
    fireEvent.click(screen.getByRole('button',{name:'Update proposal'}));await screen.findByText('Should the scene hinge or slide open?');
    expect(loadProposalSession()?.accepted).toEqual(original.accepted);expect(loadProposalSession()?.context).toEqual(original.context);
    expect(loadProposalSession()?.pending).toMatchObject({scope:'world',assets:{},previous:ids,instruction:'Press a sun to open a scene'});
    expect(screen.getAllByRole('img').map(image=>image.getAttribute('src'))).toEqual(originalImages);
    expect(screen.getByRole('button',{name:'Discard unfinished version'})).toBeEnabled();
    expect(screen.queryByText('What should this world say about your business?')).not.toBeInTheDocument();expect(mocks.generate).toHaveBeenCalledTimes(5);
  });
  it('ignores construction clarification arriving after Stop without discarding the pending request',async()=>{
    const gate=deferred<void>();mocks.generate.mockImplementationOnce(async()=>{await gate.promise;throw new ProposalConstructionNeededError('Should the panel slide?');});
    mount();await introduction();fireEvent.click(screen.getByRole('button',{name:'Generate my proposal'}));
    const pending=loadProposalSession()?.pending;fireEvent.click(screen.getByRole('button',{name:'Stop'}));
    await act(async()=>{gate.resolve();});
    expect(loadProposalSession()?.pending).toEqual(pending);expect(screen.queryByText(/Should the panel slide/)).not.toBeInTheDocument();
    expect(screen.getByText(/Stopped\. Finished sections are saved/)).toBeInTheDocument();expect(mocks.generate).toHaveBeenCalledOnce();
  });
  it('requires explicit packaging confirmation after protected-scope rejection and generates exactly one matching revision',async()=>{mount();await complete();const original=loadProposalSession()!.accepted!;const text='Keep the object and the world exactly as they are. Make only the packaging deep navy blue.';mocks.plan.mockRejectedValueOnce(new Error('The packaging revision also changed the physical concept. Your proposal is unchanged.'));fireEvent.change(screen.getByLabelText('Change your proposal'),{target:{value:text}});fireEvent.click(screen.getByRole('button',{name:'Update proposal'}));await screen.findByRole('region',{name:'Confirm packaging-only change'});expect(mocks.generate).toHaveBeenCalledTimes(4);expect(loadProposalSession()!.accepted).toEqual(original);mocks.generate.mockImplementation(async(body:ProposalRequest)=>fixture(body,{id:'00000000-0000-4000-8000-000000000024',image:'https://images.example/recovered-package.png'}));fireEvent.click(screen.getByRole('button',{name:'Update packaging only'}));await waitFor(()=>expect(loadProposalSession()?.accepted?.assets.packaging).toBe('00000000-0000-4000-8000-000000000024'));expect(mocks.generate).toHaveBeenCalledTimes(5);expect(mocks.generate.mock.calls[4][0]).toMatchObject({stage:'packaging',sourceWorldId:original.assets.world,sourcePhysicalId:original.assets.physical,previousAssetId:original.assets.packaging,context:{...original.context,revisionNotes:text}});expect(loadProposalSession()?.accepted?.assets).toEqual({...original.assets,packaging:'00000000-0000-4000-8000-000000000024'});expect(mocks.plan).toHaveBeenCalledOnce();});
  it('lets the user dismiss packaging recovery without generating or changing accepted data',async()=>{mount();await complete();const original=loadProposalSession()!.accepted;mocks.plan.mockRejectedValueOnce(new Error('The packaging revision also changed the physical concept. Your proposal is unchanged.'));fireEvent.change(screen.getByLabelText('Change your proposal'),{target:{value:'Keep the object; navy packaging only.'}});fireEvent.click(screen.getByRole('button',{name:'Update proposal'}));await screen.findByRole('button',{name:'Update packaging only'});fireEvent.click(screen.getByRole('button',{name:'Go back to my change'}));expect(screen.getByLabelText('Change your proposal')).toHaveValue('Keep the object; navy packaging only.');expect(loadProposalSession()!.accepted).toEqual(original);expect(mocks.generate).toHaveBeenCalledTimes(4);});
  it('clears the previous clarification when an explicitly confirmed packaging recovery completes',async()=>{mount();await complete();mocks.plan.mockResolvedValueOnce({clarification:'Do you mean the object or packaging?'}).mockRejectedValueOnce(new Error('The packaging revision also changed the physical concept. Your proposal is unchanged.'));fireEvent.change(screen.getByLabelText('Change your proposal'),{target:{value:'Make it blue'}});fireEvent.click(screen.getByRole('button',{name:'Update proposal'}));await screen.findAllByText('Do you mean the object or packaging?');fireEvent.change(screen.getByLabelText('Change your proposal'),{target:{value:'Only the packaging'}});fireEvent.click(screen.getByRole('button',{name:'Update proposal'}));await screen.findByRole('button',{name:'Update packaging only'});mocks.generate.mockImplementation(async(body:ProposalRequest)=>fixture(body,{id:'00000000-0000-4000-8000-000000000024'}));fireEvent.click(screen.getByRole('button',{name:'Update packaging only'}));await waitFor(()=>expect(loadProposalSession()?.accepted?.assets.packaging).toBe('00000000-0000-4000-8000-000000000024'));mocks.plan.mockResolvedValueOnce({clarification:'Which part of the world?'});fireEvent.change(screen.getByLabelText('Change your proposal'),{target:{value:'Make the world more open'}});fireEvent.click(screen.getByRole('button',{name:'Update proposal'}));await waitFor(()=>expect(mocks.plan).toHaveBeenCalledTimes(3));expect(mocks.plan.mock.calls[2][0].instruction).toBe('Make the world more open');});
  it('prevents duplicate packaging confirmation and ignores a stopped late image',async()=>{mount();await complete();const original=loadProposalSession()!.accepted;mocks.plan.mockRejectedValueOnce(new Error('The packaging revision also changed the physical concept. Your proposal is unchanged.'));fireEvent.change(screen.getByLabelText('Change your proposal'),{target:{value:'Navy packaging only'}});fireEvent.click(screen.getByRole('button',{name:'Update proposal'}));const confirm=await screen.findByRole('button',{name:'Update packaging only'});const gate=deferred<ProposalConcept>();mocks.generate.mockImplementationOnce(()=>gate.promise);fireEvent.click(confirm);fireEvent.click(confirm);expect(mocks.generate).toHaveBeenCalledTimes(5);const body=mocks.generate.mock.calls[4][0];const signal=mocks.generate.mock.calls[4][1];fireEvent.click(screen.getByRole('button',{name:'Stop'}));expect(signal.aborted).toBe(true);await act(async()=>{gate.resolve(fixture(body,{id:'00000000-0000-4000-8000-000000000024'}));});expect(loadProposalSession()!.accepted).toEqual(original);expect(mocks.generate).toHaveBeenCalledTimes(5);});
  it('clears an unconfirmed packaging recovery on newer navigation',async()=>{mount('/?proposal=1',true);await complete();mocks.plan.mockRejectedValueOnce(new Error('The packaging revision also changed the physical concept. Your proposal is unchanged.'));fireEvent.change(screen.getByLabelText('Change your proposal'),{target:{value:'Navy packaging only'}});fireEvent.click(screen.getByRole('button',{name:'Update proposal'}));await screen.findByRole('button',{name:'Update packaging only'});fireEvent.click(screen.getByRole('link',{name:'Newer route'}));await waitFor(()=>expect(screen.queryByRole('button',{name:'Update packaging only'})).not.toBeInTheDocument());expect(mocks.generate).toHaveBeenCalledTimes(4);});
  it('asks a single clarification and does not generate an ambiguous change',async()=>{mount();await complete();mocks.plan.mockResolvedValue({clarification:'Do you mean the box or the object?'});fireEvent.change(screen.getByLabelText('Change your proposal'),{target:{value:'Make it blue'}});fireEvent.click(screen.getByRole('button',{name:'Update proposal'}));await screen.findAllByText('Do you mean the box or the object?');expect(mocks.generate).toHaveBeenCalledTimes(4);expect(loadProposalSession()?.accepted?.assets).toEqual(ids);});
  it('restores saved images without generation even when generation is unavailable',async()=>{saveProposalSession(saved());mocks.ready.mockResolvedValue(false);mount();fireEvent.click(screen.getByRole('button',{name:'Continue saved proposal'}));await screen.findByRole('heading',{name:'Paper packaging'});expect(mocks.restore).toHaveBeenCalledTimes(4);expect(mocks.generate).not.toHaveBeenCalled();expect(screen.getAllByRole('img')).toHaveLength(4);});
  it('defaults sharing to text-only and requires separate original-metadata opt-in',async()=>{mount();await complete();fireEvent.click(screen.getByRole('button',{name:'Share'}));const d=within(screen.getByRole('dialog'));expect(d.getByRole('checkbox')).not.toBeChecked();fireEvent.click(d.getByRole('button',{name:'Create reviewed link'}));const link=d.getByRole('textbox',{name:'Share link'}) as HTMLInputElement;expect(decodeProposalShare(new URL(link.value).hash)?.accepted).toBeNull();fireEvent.click(d.getByRole('checkbox'));expect(d.getByText(/including details removed/)).toBeInTheDocument();expect(d.getAllByText(/Review original/)).toHaveLength(4);fireEvent.click(d.getByRole('button',{name:'Create reviewed link'}));const imageLink=d.getByRole('textbox',{name:'Share link'}) as HTMLInputElement;expect(decodeProposalShare(new URL(imageLink.value).hash)?.accepted?.assets).toEqual(ids);expect(imageLink.value).not.toContain('images.example');});
  it('imports reviewed text as an independent branch without generating',async()=>{const s=emptyProposalSession();s.context.business='A shared personal paper story';const hash=encodeProposalShare(s);mount('/'+hash);expect(screen.getByRole('dialog')).toBeInTheDocument();expect(loadProposalSession()).toBeNull();fireEvent.click(screen.getByRole('button',{name:'Open my editable version'}));await waitFor(()=>expect(screen.queryByRole('dialog')).not.toBeInTheDocument());expect(loadProposalSession()?.context.business).toBe(s.context.business);expect(loadProposalSession()?.id).not.toBe(s.id);expect(mocks.generate).not.toHaveBeenCalled();});
  it('switches the ordinary public root only when the full capability is ready',async()=>{mount('/');await screen.findByLabelText('Your brand, website or story');expect(screen.queryByRole('button',{name:'Generate my brand world'})).not.toBeInTheDocument();});
  it('keeps the earlier working root with a truthful notice until backend verification',async()=>{mocks.ready.mockResolvedValue(false);mount('/');await screen.findByText(/This earlier canvas creates world and physical studies only/);expect(screen.getByRole('button',{name:'Generate my brand world'})).toBeInTheDocument();expect(screen.getByRole('link',{name:'Open a saved complete proposal'})).toHaveAttribute('href','/?proposal=1');});
  it('bounds a hung root capability check and ignores its late reply',async()=>{vi.useFakeTimers();const gate=deferred<boolean>();mocks.ready.mockImplementationOnce(()=>gate.promise);mount('/');expect(screen.getByText('Opening your creative studio…')).toBeInTheDocument();await act(async()=>{vi.advanceTimersByTime(6000);});expect(screen.getByText(/This earlier canvas creates world and physical studies only/)).toBeInTheDocument();await act(async()=>{gate.resolve(true);});expect(screen.getByRole('button',{name:'Generate my brand world'})).toBeInTheDocument();});
  it('imports a reviewed proposal even when generation readiness is disabled',async()=>{mocks.ready.mockResolvedValue(false);const s=emptyProposalSession();s.context.business='Offline shared direction';mount('/'+encodeProposalShare(s));fireEvent.click(screen.getByRole('button',{name:'Open my editable version'}));await waitFor(()=>expect(loadProposalSession()?.context.business).toBe('Offline shared direction'));expect(screen.queryByRole('dialog')).not.toBeInTheDocument();expect(screen.queryByText(/This earlier canvas creates/)).not.toBeInTheDocument();expect(mocks.generate).not.toHaveBeenCalled();});
  it('keeps the v9 canvas route available separately',()=>{mount('/?canvas=legacy');expect(screen.getByRole('button',{name:'Generate my brand world'})).toBeInTheDocument();expect(screen.queryByRole('button',{name:'Generate my proposal'})).not.toBeInTheDocument();});
  it('simple mode supports refinement and the build-proposal handoff after a complete preview',async()=>{mocks.simple=true;mount();await complete();await screen.findAllByText('Your concept preview is ready.');expect(screen.getByLabelText('Change your proposal')).toBeEnabled();expect(screen.getByRole('button',{name:'Request a Quote & Build Proposal'})).toBeEnabled();expect(screen.queryByText('Edit details')).toBeNull();expect(screen.getAllByRole('button',{name:/Download brief/}).length).toBeGreaterThan(0);});
  it('simple mode replaces the paused banner with a link to example worlds',async()=>{mocks.simple=true;mocks.paused=true;mocks.ready.mockResolvedValue(false);mount('/');expect(await screen.findByRole('link',{name:/Explore the studies/})).toHaveAttribute('href','/showcase');expect(screen.queryByText(/Earlier workflow: visual studies only/)).toBeNull();});
  it('regenerates only details with the original saved physical context after a packaging revision',async()=>{
    mount();await complete();const original=loadProposalSession()!.accepted!;
    fireEvent.change(screen.getByLabelText('Change your proposal'),{target:{value:'Make only the box navy'}});fireEvent.click(screen.getByRole('button',{name:'Update proposal'}));await waitFor(()=>expect(mocks.generate).toHaveBeenCalledTimes(5));await screen.findByRole('button',{name:'Update proposal'});
    const packaged=loadProposalSession()!.accepted!;expect(packaged.context.revisionNotes).toBe('Packaging deep blue; object unchanged');
    const instruction='Show the attached dial action, with matched close views';
    mocks.plan.mockImplementationOnce(async body=>({plan:{scope:'details',context:body.context,summary:'Refine only the detail sheet.',detailsRefinement:{version:'details-refinement-v1',instruction:body.instruction}}}));
    fireEvent.change(screen.getByLabelText('Change your proposal'),{target:{value:instruction}});fireEvent.click(screen.getByRole('button',{name:'Update proposal'}));await waitFor(()=>expect(mocks.generate).toHaveBeenCalledTimes(6));await screen.findByRole('button',{name:'Update proposal'});
    const request=mocks.generate.mock.calls[5][0];expect(request).toMatchObject({stage:'details',context:original.context,sourceWorldId:original.assets.world,sourcePhysicalId:original.assets.physical,previousAssetId:original.assets.details,detailsRefinement:{version:'details-refinement-v1',instruction}});
    const refined=loadProposalSession()!.accepted!;expect(refined.context).toEqual(packaged.context);expect(refined.assets.packaging).toBe(packaged.assets.packaging);expect(refined.assets.world).toBe(original.assets.world);expect(refined.assets.physical).toBe(original.assets.physical);
  });

});


it('keeps a project enquiry usable when an invited buyer has no image allowance',async()=>{
  setPilotInvite('a'.repeat(43));rememberPilotAccess({version:'offkin-pilot-v1',authorized:true,images_remaining:0,planners_remaining:0,expires_at:'2099-01-01T00:00:00Z'});mocks.simple=true;mocks.paused=true;mocks.ready.mockResolvedValue(false);mount('/');
  await screen.findByRole('button',{name:'Plan my project'});expect(screen.getAllByText(/Your pilot image allowance is used/).length).toBeGreaterThan(0);
  fireEvent.click(screen.getByRole('button',{name:'Plan my project'}));expect(screen.getByRole('dialog',{name:'Your project brief'})).toBeInTheDocument();expect(mocks.generate).not.toHaveBeenCalled();
});
it('keeps an accepted preview and its enquiry usable when revision planning is exhausted',async()=>{
  setPilotInvite('a'.repeat(43));rememberPilotAccess({version:'offkin-pilot-v1',authorized:true,images_remaining:1,planners_remaining:0,expires_at:'2099-01-01T00:00:00Z'});mocks.simple=true;saveProposalSession(saved());mount('/');
  fireEvent.click(await screen.findByRole('button',{name:'Continue saved proposal'}));await screen.findByRole('heading',{name:'Paper packaging'});
  fireEvent.change(screen.getByLabelText('Change your proposal'),{target:{value:'Only the box, please'}});expect(screen.getByRole('button',{name:'Update proposal'})).toBeDisabled();expect(screen.getByRole('button',{name:'Request a Quote & Build Proposal'})).toBeEnabled();expect(mocks.generate).not.toHaveBeenCalled();expect(mocks.plan).not.toHaveBeenCalled();
});
it('recovers an interrupted saved planner response without automatically generating its image',async()=>{
  setPilotInvite('a'.repeat(43));rememberPilotAccess({version:'offkin-pilot-v1',authorized:true,images_remaining:5,planners_remaining:1,recovery_available:true,expires_at:'2099-01-01T00:00:00Z'});mount();await complete();
  mocks.plan.mockRejectedValueOnce(new Error('Connection lost after planning'));
  fireEvent.change(screen.getByLabelText('Change your proposal'),{target:{value:'Make only the packaging navy'}});fireEvent.click(screen.getByRole('button',{name:'Update proposal'}));await screen.findByText('Connection lost after planning');
  await act(async()=>{rememberPilotAccess({version:'offkin-pilot-v1',authorized:true,images_remaining:1,planners_remaining:0,recovery_available:true,expires_at:'2099-01-01T00:00:00Z'});});
  fireEvent.click(screen.getByRole('button',{name:'Recover previous revision'}));await screen.findByText(/Saved revision plan recovered without a new AI call/);
  expect(mocks.plan).toHaveBeenCalledTimes(2);expect(mocks.plan.mock.calls[1][2]).toBe(true);expect(mocks.plan.mock.calls[1][0]).toEqual(mocks.plan.mock.calls[0][0]);expect(mocks.generate).toHaveBeenCalledTimes(4);expect(loadProposalSession()?.pending?.scope).toBe('packaging');
});
it('offers a factual story fallback without a public website inspection or anonymous generation',async()=>{
  mocks.simple=true;mocks.paused=true;mocks.ready.mockResolvedValue(false);mount('/');
  fireEvent.click(screen.getByText('Prefer to describe your idea?'));
  fireEvent.change(screen.getByLabelText('Brand or project name'),{target:{value:'Fable Finch'}});fireEvent.change(screen.getByLabelText('Your story'),{target:{value:'We build welcoming spaces'}});
  fireEvent.click(screen.getByRole('button',{name:'Create from my story'}));expect(mocks.generate).not.toHaveBeenCalled();expect(mocks.website).not.toHaveBeenCalled();expect(screen.getByRole('status')).toHaveTextContent('Open your invitation');
});

const research={contractVersion:'offkin-brand-discovery-v1',status:'ready',researchId:'00000000-0000-4000-8000-000000000091',brand:'Fable Finch',website:'https://fable.example/',summary:'Fable Finch is a paper studio making thoughtful illustrated gifts for celebrations, special occasions and everyday moments.',evidence:[{url:'https://fable.example/',title:'Fable Finch',excerpt:'Thoughtful illustrated paper gifts for celebrations.'}],candidates:[],message:'Brand found.'};
it('turns one researched brand entry into all four actual images without audience or repeated name gates',async()=>{
  mocks.simple=true;mocks.discovery.mockResolvedValue(research);mount('/');await waitFor(()=>expect(mocks.ready).toHaveBeenCalled());
  expect(screen.getByRole('heading',{level:1})).toHaveTextContent('Your brand. Made collectible.');
  fireEvent.change(screen.getByLabelText('Your brand name or website'),{target:{value:'Fable Finch'}});fireEvent.click(screen.getByRole('button',{name:'See my concept'}));
  await screen.findByRole('button',{name:'Update proposal'});expect(mocks.discovery).toHaveBeenCalledOnce();expect(mocks.generate.mock.calls.map(([r])=>r.stage)).toEqual(['world','physical','details','packaging']);
  expect(mocks.generate.mock.calls[0][0]).toMatchObject({brandResearchId:research.researchId,brand:'https://fable.example',customerIdentity:{name:'Fable Finch'},context:{business:research.summary}});
  for(const [r]of mocks.generate.mock.calls.slice(1))expect(r).not.toHaveProperty('brandResearchId');
  expect(loadProposalSession()?.accepted?.brandEvidence).toEqual(research.evidence);expect(screen.getByRole('link',{name:'Fable Finch'})).toHaveAttribute('href',research.website);
  expect(screen.queryByText('Who should this story connect with?')).not.toBeInTheDocument();expect(screen.queryByLabelText('Exact brand name')).not.toBeInTheDocument();expect(screen.getByRole('button',{name:'Request a Quote & Build Proposal'})).toBeEnabled();
});
it('shows the real world before the hero and puts the request beside the hero while later panels complete',async()=>{
  mocks.simple=true;mocks.discovery.mockResolvedValue(research);const hero=deferred<ProposalConcept>();const details=deferred<ProposalConcept>();
  mocks.generate.mockImplementation((r:ProposalRequest)=>r.stage==='physical'?hero.promise:r.stage==='details'?details.promise:Promise.resolve(fixture(r)));
  mount('/');await waitFor(()=>expect(mocks.ready).toHaveBeenCalled());fireEvent.change(screen.getByLabelText('Your brand name or website'),{target:{value:'Fable Finch'}});fireEvent.click(screen.getByRole('button',{name:'See my concept'}));
  await waitFor(()=>expect(mocks.generate).toHaveBeenCalledTimes(2));expect(screen.getAllByRole('img')).toHaveLength(1);expect(screen.queryByText('Collectible is not ready yet')).not.toBeInTheDocument();expect(screen.getByText(/Its dimensional concept is next/)).toBeInTheDocument();
  await act(async()=>hero.resolve(fixture(mocks.generate.mock.calls[1][0])));await waitFor(()=>expect(mocks.generate).toHaveBeenCalledTimes(3));
  const request=screen.getByRole('button',{name:'Request a Quote & Build Proposal'});expect(request.closest('.pb-hero-action')).not.toBeNull();expect(request).toBeEnabled();fireEvent.click(request);expect(screen.getByRole('dialog')).toHaveTextContent('Your preview has unfinished sections');
  fireEvent.click(within(screen.getByRole('dialog')).getByRole('button',{name:'Close'}));await act(async()=>details.resolve(fixture(mocks.generate.mock.calls[2][0])));await screen.findByRole('button',{name:'Update proposal'});
});
