import { CUSTOMER_IDENTITY_VERSION, isCustomerIdentity } from '../../supabase/functions/generate-concept/proposal';
import { PROPOSAL_ASSET_TIMEOUT_MS } from '../../supabase/functions/generate-concept/proposal-budget';
import { PROPOSAL_GENERATION_PAUSED, PROPOSAL_PAUSE_MESSAGE } from '@/lib/proposal-availability';
import { useEffect, useRef, useState } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { ArrowRight, ArrowUp, ArrowUpRight, Download, LoaderCircle, Share2, Sparkles, X } from 'lucide-react';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { supabase } from '@/integrations/supabase/client';
import { studioBrand } from '@/lib/studio-brand';
import { requestConcept, type WebsiteEvidence } from '@/lib/concept-api';
import { interpretConversationEntry } from '@/lib/conversation-input';
import { PROPOSAL_CONTRACT_VERSION, PROPOSAL_STAGES, ProposalConstructionNeededError, ProposalContextNeededError, planProposalRevision, requestProposalAsset, restoreProposalAsset, supportsProposalGeneration, findBrand, looksLikeBrandName, type BrandCandidate, type ProposalConcept } from '@/lib/proposal-api';
import { addProposalAsset, addTurn, assetsForVersion, confirmedPackagingChange, decodeProposalShare, emptyProposalSession, encodeProposalShare, isComplete, loadProposalSession, loadProposalSnapshot, pendingProposal, proposalBrand, proposalBrief, requestForStage, saveProposalSession, saveProposalSnapshot, type PendingProposal, type ProposalSession } from '@/lib/proposal-session';
import { loadCanvasSession, newVersion } from '@/lib/canvas-session';
import ProposalBoard from './ProposalBoard';
import BuildProposalRequest from './BuildProposalRequest';
import { proposalExportSnapshot } from '@/lib/proposal-export';
import './proposal-studio.css';
import './studio.css';

const needsCustomerIdentity = (pending:PendingProposal) => !pending.assets.world && !isCustomerIdentity(pending.customerIdentity);
const stageNames = {world:'brand world',physical:'product hero',details:'components & interaction',packaging:'packaging'};
const safeLink=(value:string)=>/^https?:\/\//i.test(value)||(value.startsWith('/')&&!value.startsWith('//'))?value:'/';
export default function ProposalStudio({simple=false}:{simple?:boolean}={}) {
  const location=useLocation();const navigate=useNavigate();
  const [session,setSession]=useState<ProposalSession>(emptyProposalSession);const latest=useRef(session);
  const [saved,setSaved]=useState(loadProposalSession);const [legacySaved]=useState(loadCanvasSession);
  const [identityName,setIdentityName]=useState('');
  const [started,setStarted]=useState(false);const [entry,setEntry]=useState('');const [question,setQuestion]=useState<'start'|'business'|'audience'|'ready'>('start');
  const [packagingRecovery,setPackagingRecovery]=useState<{instruction:string;acceptedId:string}|null>(null);
  const [instruction,setInstruction]=useState('');const [clarification,setClarification]=useState('');const [clarificationInstruction,setClarificationInstruction]=useState('');
  const [all,setAll]=useState<Record<string,ProposalConcept>>({});const allRef=useRef(all);
  const [status,setStatus]=useState('');const [busy,setBusy]=useState('');const busyRef=useRef(false);const controller=useRef<AbortController|null>(null);const epoch=useRef(0);
  const restoreCallback=useRef<((next:ProposalSession)=>Promise<void>)|null>(null);
  const [ready,setReady]=useState<boolean|null>(null);const [retry,setRetry]=useState(0);const [saveError,setSaveError]=useState(false);const [snapshotError,setSnapshotError]=useState(false);const storageError=saveError||snapshotError;
  const [evidence,setEvidence]=useState<WebsiteEvidence|null>(null);const [candidates,setCandidates]=useState<{query:string;list:BrandCandidate[]}|null>(null);const [imageErrors,setImageErrors]=useState<Record<string,boolean>>({});
  const dialogTrigger=useRef<HTMLElement|null>(null);
  const [dialog,setDialog]=useState<'share'|'import'|'image'|null>(null);const [enlarged,setEnlarged]=useState<ProposalConcept|null>(null);
  const [shared,setShared]=useState<ProposalSession|null>(null);const [includeImages,setIncludeImages]=useState(false);const [shareLink,setShareLink]=useState('');const [shareStatus,setShareStatus]=useState('');
  const [settings,setSettings]=useState({title:studioBrand.name,logo:'',link:'/'});
  function commit(next:ProposalSession){latest.current=next;setSession(next);setStarted(true);setSaveError(!saveProposalSession(next));}
  function keep(asset:ProposalConcept){allRef.current={...allRef.current,[asset.id]:asset};setAll(allRef.current);if(!saveProposalSnapshot(asset))setSnapshotError(true);}
  function stop(message=true){epoch.current++;controller.current?.abort();controller.current=null;busyRef.current=false;setBusy('');if(message)setStatus('Stopped. Finished sections are saved. A provider request already started may still use credits; continuing may repeat an unfinished request.');}
  function begin(label:string){busyRef.current=true;controller.current?.abort();const abort=new AbortController();controller.current=abort;const token=++epoch.current;setBusy(label);setStatus('');return {abort,token};}
  const live=(token:number,abort:AbortController)=>token===epoch.current&&!abort.signal.aborted;
  function finish(token:number){if(token===epoch.current){busyRef.current=false;controller.current=null;setBusy('');}}
  useEffect(()=>{let active=true;supabase.from('site_settings').select('key,value').then(({data})=>{if(!active||!data)return;const next={title:studioBrand.name,logo:'',link:'/'};for(const s of data){if(s.key==='site_title'&&s.value&&!['dioramini','briq2.0','briq','form.','brandkin','stive','the absurd marshmallow test'].includes(s.value.trim().toLowerCase()))next.title=s.value;if(s.key==='logo_url'&&/^https?:\/\//i.test(s.value||''))next.logo=s.value;if(s.key==='logo_link'&&s.value&&s.value!=='https://example.com')next.link=safeLink(s.value);}setSettings(next);});return()=>{active=false;};},[]);
  useEffect(()=>{document.title=`${settings.title}｜异趣伙伴 — ${studioBrand.pageTitleSuffix}`;},[settings.title]);
  useEffect(()=>{const abort=new AbortController();setReady(null);supportsProposalGeneration(abort.signal).then(value=>{if(!abort.signal.aborted)setReady(value);});return()=>abort.abort();},[retry]);
  useEffect(()=>{dialogTrigger.current=null;epoch.current++;controller.current?.abort();controller.current=null;busyRef.current=false;setBusy('');setPackagingRecovery(null);setClarification('');setClarificationInstruction('');setShareLink('');setShareStatus('');if(location.hash.startsWith('#proposal=')){const candidate=decodeProposalShare(location.hash);setShared(candidate);setDialog('import');}else{setDialog(null);setShared(null);}},[location.key,location.pathname,location.search,location.hash]);
  useEffect(()=>()=>{epoch.current++;controller.current?.abort();busyRef.current=false;},[]);
  function customerName(value:string){
    if(busyRef.current||latest.current.pending?.assets.world||latest.current.accepted&&!(latest.current.pending?.scope==='world'&&!latest.current.accepted.customerIdentity))return;
    const candidate={version:CUSTOMER_IDENTITY_VERSION,name:value};
    const customerIdentity=isCustomerIdentity(candidate)?candidate:undefined;
    setIdentityName(value);
    const current=latest.current;
    commit({...current,...(!current.accepted?{customerIdentity}:{}),...(current.pending?{pending:{...current.pending,customerIdentity}}:{})});
  }
  function customerIdentityField(rename=false){return <div className="op-detail-grid" style={{gridTemplateColumns:'minmax(0,1fr)'}}><label>Exact brand name<input id="proposal-customer-name" value={identityName} disabled={Boolean(busy)||!rename&&(Boolean(session.pending?.assets.world)||Boolean(session.accepted&&!(session.pending?.scope==='world'&&!session.accepted.customerIdentity)))} onChange={event=>rename?setIdentityName(event.target.value):customerName(event.target.value)} maxLength={120} autoComplete="organization" aria-describedby="proposal-customer-name-help"/></label><p id="proposal-customer-name-help" className="op-subtle">Use the exact customer brand name, including its spelling and capitalisation.</p></div>;}
  function startBrandDirection(){
    const current=latest.current;const accepted=current.accepted;const customerIdentity={version:CUSTOMER_IDENTITY_VERSION,name:identityName};
    if(busyRef.current||!accepted||current.pending||!isCustomerIdentity(customerIdentity)||customerIdentity.name===accepted.customerIdentity?.name)return;
    const instruction=`Change the exact customer brand name to ${JSON.stringify(customerIdentity.name)}.`;
    const pending={...pendingProposal({...current,website:accepted.website},'world',accepted.context,instruction),customerIdentity};
    commit(addTurn({...current,pending},'user',instruction));setClarification('');setClarificationInstruction('');setPackagingRecovery(null);setStatus('Your new brand direction is ready to preview. Your complete proposal stays visible until all four new sections are ready.');
  }
  function field(key:string,value:string){commit({...latest.current,constructionIntent:undefined,context:{...latest.current.context,[key]:value}});}
  function submitEntry(){if(busyRef.current||!entry.trim())return;let next=latest.current;
    if(question==='audience'){if(entry.length>120){setStatus('Keep the audience answer under 120 characters.');return;}next={...next,context:{...next.context,audience:entry}};setQuestion('ready');}
    else{const parsed=interpretConversationEntry(entry);if(parsed.kind==='error'){setStatus(parsed.message);return;}if(parsed.kind==='website'){next={...next,website:parsed.value};setQuestion('business');}else if(question==='start'&&looksLikeBrandName(entry)){void lookupBrand(entry);return;}else{next={...next,context:{...next.context,business:parsed.value}};setQuestion('audience');}}
    commit(addTurn({...next,constructionIntent:undefined},'user',entry));setEntry('');setStatus('');}
  async function lookupBrand(query:string){if(busyRef.current)return;const {abort,token}=begin('Finding your brand');const timer=window.setTimeout(()=>abort.abort(),15000);
    try{const list=await findBrand(query,abort.signal);if(!live(token,abort))return;setEntry('');if(list.length){setCandidates({query,list});}else{asStory(query);setStatus('We couldn’t find a public website for that name, so we’ll use your words. Add the website any time.');}}catch{if(live(token,abort)){asStory(query);setStatus('We couldn’t look that brand up just now, so we’ll use your words.');}}finally{clearTimeout(timer);if(token===epoch.current&&abort.signal.aborted)setStatus('Brand lookup timed out. Enter the website or describe the brand.');finish(token);}}
  function asStory(query:string){setEntry('');const next={...latest.current,constructionIntent:undefined,context:{...latest.current.context,business:query}};commit(addTurn(next,'user',query));setQuestion('audience');}
  function chooseBrand(c:BrandCandidate|null){const query=candidates?.query||'';setCandidates(null);if(!c){customerName(query.trim());setQuestion('business');setStatus('Describe the brand in your own words.');return;}customerName(c.name.trim());const next={...latest.current,website:c.url,constructionIntent:undefined};commit(addTurn(next,'user',`${c.name.trim()} — ${c.url}`));setQuestion('business');setStatus('Researching the selected brand…');void readWebsite();}
  async function readWebsite(){if(busyRef.current)return;let brand;try{brand=proposalBrand(latest.current.website);}catch(e){setStatus((e as Error).message);return;}if(brand==='no-website')return;const {abort,token}=begin('Reading public website');const timer=window.setTimeout(()=>abort.abort(),35000);
    try{const result=await requestConcept({brand,context:'',edition:'icon',format:'miniature',inspectWebsite:true},abort.signal);if(!live(token,abort))return;if(result.website)setEvidence(result.website);else setStatus(result.message||'This page could not be read. Tell us what the business does to continue.');}catch(e){if(live(token,abort))setStatus(e instanceof Error?e.message:'Could not read this page. Describe the business instead.');}finally{clearTimeout(timer);if(token===epoch.current&&abort.signal.aborted)setStatus('Website reading timed out. You can describe the business instead.');finish(token);}}
  async function generatePending(pending:PendingProposal,provided?:{abort:AbortController;token:number}){
    if(!provided&&busyRef.current||latest.current.pending?.id!==pending.id)return;if(needsCustomerIdentity(pending)){setStatus('Enter the exact brand name before generating your proposal.');if(provided)finish(provided.token);return;}const {abort,token}=provided||begin('Preparing your proposal');let working=pending;
    try{for(const stage of PROPOSAL_STAGES){if(working.assets[stage])continue;if(!live(token,abort))return;setBusy(`Creating ${stageNames[stage]}`);const timer=window.setTimeout(()=>abort.abort(),PROPOSAL_ASSET_TIMEOUT_MS);let asset:ProposalConcept;try{asset=await requestProposalAsset(requestForStage(working,stage,assetsForVersion(working,allRef.current).physical?.context),abort.signal);}finally{clearTimeout(timer);}if(!live(token,abort)||latest.current.pending?.id!==pending.id)return;working=addProposalAsset(working,asset);keep(asset);commit({...latest.current,pending:working});setStatus(`${stageNames[stage][0].toUpperCase()+stageNames[stage].slice(1)} is ready. Continuing your proposal…`);}
      if(!live(token,abort)||!isComplete(working))return;const {scope:_scope,previous:_previous,instruction:_instruction,...accepted}=working;commit(addTurn({...latest.current,accepted,pending:null,customerIdentity:accepted.customerIdentity,constructionIntent:accepted.constructionIntent,context:accepted.context,website:accepted.website},'assistant',pending.instruction?'Your proposal has been updated. The unaffected sections are preserved.':'Your complete proposal is ready.'));setStatus('Your complete proposal is ready. Every image belongs to this proposal.');setInstruction('');setClarification('');setClarificationInstruction('');setQuestion('ready');
    }catch(e){if(live(token,abort)){
      setStatus(e instanceof Error?e.message:'This section did not finish. Continue to complete the missing sections.');
      if(latest.current.pending?.id===pending.id&&!latest.current.accepted&&!Object.keys(working.assets).length){
        if(e instanceof ProposalConstructionNeededError&&working.scope==='world'&&!Object.keys(working.previous).length){
          commit({...latest.current,pending:null});setQuestion('ready');
          setStatus(`${e.message} Review your direction under Edit details before generating again.`);
        }else if(e instanceof ProposalContextNeededError){commit({...latest.current,pending:null});setQuestion('business');}
      }
    }}finally{if(token===epoch.current&&abort.signal.aborted)setStatus('This section timed out. Finished sections are saved. Continuing can retry the unfinished request; a previous provider request may still use credits.');finish(token);}}
  function generate(){if(busyRef.current)return;const current=latest.current;if(!current.pending&&!current.accepted&&!isCustomerIdentity(current.customerIdentity)){setStatus('Enter the exact brand name before generating your proposal.');return;}if(!current.context.business?.trim()){setStatus('Tell us what your business does first.');return;}try{proposalBrand(current.website);}catch(e){setStatus((e as Error).message);return;}const pending=current.pending||pendingProposal(current,'world',current.context);commit({...current,pending});void generatePending(pending);}
  async function revise(){if(busyRef.current||!instruction.trim()||!latest.current.accepted||latest.current.pending)return;const original=latest.current;const accepted=original.accepted!;const text=clarificationInstruction?`${clarificationInstruction}\nClarification answer: ${instruction}`:instruction;if(text.length>2000){setStatus('Keep the change under 2,000 characters.');return;}const {abort,token}=begin('Understanding your change');let planningTimedOut=false;const timer=window.setTimeout(()=>{planningTimedOut=true;abort.abort();},65000);
    try{const result=await planProposalRevision({contractVersion:PROPOSAL_CONTRACT_VERSION,action:'plan-revision',brand:proposalBrand(accepted.website),context:accepted.context,instruction:text,sourceWorldId:accepted.assets.world!,sourcePhysicalId:accepted.assets.physical!,detailsId:accepted.assets.details,packagingId:accepted.assets.packaging},abort.signal);clearTimeout(timer);if(!live(token,abort)||latest.current.accepted?.id!==accepted.id)return;if('clarification' in result && result.clarification){setClarification(result.clarification);setClarificationInstruction(text);setInstruction('');commit(addTurn(addTurn(original,'user',text),'assistant',result.clarification));finish(token);return;}if(!('plan' in result)||!result.plan)throw new Error('The change could not be planned safely.');const basePending=pendingProposal({...original,website:accepted.website},result.plan.scope,result.plan.context,text);const pending={...basePending,...(result.plan.selectedElementIds?{selected:result.plan.selectedElementIds}:{}),...(result.plan.heroElementId?{hero:result.plan.heroElementId}:{}),...(result.plan.replacements?{replacements:result.plan.replacements}:{})};setIdentityName(pending.customerIdentity?.name||'');commit(addTurn(addTurn({...original,constructionIntent:result.plan.scope==='packaging'||result.plan.scope==='details'?original.constructionIntent:undefined,pending},'user',text),'assistant',result.plan.summary));setClarification('');setClarificationInstruction('');setStatus(result.plan.summary);await generatePending(pending,{abort,token});
    }catch(e){if(live(token,abort)){setStatus(e instanceof Error?e.message:'This change could not be understood.');if(e instanceof Error&&e.message==='The packaging revision also changed the physical concept. Your proposal is unchanged.')setPackagingRecovery({instruction:text,acceptedId:accepted.id});}finish(token);}finally{clearTimeout(timer);if(token===epoch.current&&planningTimedOut){setStatus('Planning timed out. Your accepted proposal is unchanged.');finish(token);}}}
  function confirmPackagingRecovery(){
    if(busyRef.current||!packagingRecovery)return;
    if(latest.current.accepted?.id!==packagingRecovery.acceptedId){setPackagingRecovery(null);setStatus('The accepted version changed. Describe the change again for this proposal.');return;}
    try{const pending=confirmedPackagingChange(latest.current,packagingRecovery.instruction);commit(addTurn(addTurn({...latest.current,pending},'user',packagingRecovery.instruction),'assistant','Update only the packaging; keep the accepted world, object and component images.'));setPackagingRecovery(null);setClarification('');setClarificationInstruction('');void generatePending(pending);}catch(e){setStatus(e instanceof Error?e.message:'The packaging change could not be prepared safely.');}
  }
  async function restore(next:ProposalSession){if(busyRef.current)return;const s={...next,id:newVersion()};setIdentityName((s.pending||s.accepted||s).customerIdentity?.name||'');commit(s);setSaved(null);setEntry('');setQuestion(s.context.business?'ready':s.website?'business':'start');setEvidence(null);setInstruction('');setClarification('');setClarificationInstruction('');setPackagingRecovery(null);setDialog(null);const ids=[...new Set([...Object.values(s.accepted?.assets||{}),...Object.values(s.pending?.assets||{}),...Object.values(s.pending?.previous||{})])];const snapshots:Record<string,ProposalConcept>={};for(const id of ids){const c=loadProposalSnapshot(id);if(c)snapshots[id]=c;}allRef.current=snapshots;setAll(snapshots);if(!ids.length){setStatus('Your direction is open on this device.');return;}const {abort,token}=begin('Restoring saved proposal');const timer=window.setTimeout(()=>abort.abort(),60000);const failures:string[]=[];try{for(const id of ids){try{const expectedIdentity=[s.accepted,s.pending].find(version=>version&&Object.values(version.assets).includes(id))?.customerIdentity;const asset=await restoreProposalAsset(id,abort.signal,expectedIdentity);if(!live(token,abort))return;keep(asset);}catch{if(!live(token,abort))return;failures.push(id);}}if(live(token,abort))setStatus(failures.length?'Some saved images could not be restored. Your direction and saved section IDs are intact.':'Saved images restored without generation.');}finally{clearTimeout(timer);if(token===epoch.current&&abort.signal.aborted)setStatus('Restoration timed out. Your saved direction is intact.');finish(token);}}
  function download(){const content=proposalBrief(latest.current,allRef.current);const url=URL.createObjectURL(new Blob([content],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`OFFKIN-${(session.accepted?.id||session.id).slice(0,8)}-proposal-brief.txt`;a.click();window.setTimeout(()=>URL.revokeObjectURL(url),1000);setStatus('Brief downloaded. It has not been sent to anyone.');}
  function proposalPath(){const query=new URLSearchParams(location.search);query.set('proposal','1');return location.pathname+'?'+query.toString();}
  function jumpTo(id:string){const target=document.getElementById(id);target?.scrollIntoView({block:'start'});target?.focus({preventScroll:true});}
  function openDialog(kind:'share'|'image',trigger:HTMLElement){dialogTrigger.current=trigger;setDialog(kind);}
  function restoreDialogFocus(){const trigger=dialogTrigger.current;dialogTrigger.current=null;if(trigger?.isConnected)trigger.focus({preventScroll:true});else document.getElementById('proposal-main')?.focus({preventScroll:true});}
  function closeDialog(){setDialog(null);if(location.hash.startsWith('#proposal='))navigate(proposalPath(),{replace:true});}
  async function share(){try{const hash=encodeProposalShare(latest.current,includeImages);const link=window.location.origin+window.location.pathname+hash;setShareLink(link);try{await navigator.clipboard.writeText(link);setShareStatus('Link copied. Anyone with it can open the reviewed content.');}catch{setShareStatus('Copy the link below.');}}catch(e){setShareStatus(e instanceof Error?e.message:'Could not create this link.');}}
  const acceptedAssets=assetsForVersion(session.accepted,all);const pendingAssets=assetsForVersion(session.pending,all);const displayAssets=session.accepted?acceptedAssets:pendingAssets;
  restoreCallback.current=restore;
  const hasResults=Boolean(session.accepted||Object.keys(session.pending?.assets||{}).length);const complete=Boolean(session.accepted);const locked=Boolean(busy);const imported=useRef<ProposalSession|null>(null);
  useEffect(()=>{if(imported.current&&!location.hash){const next=imported.current;imported.current=null;void restoreCallback.current?.(next);}},[location.hash]); // Restoration starts only after navigation has cancelled older work.
  const reviewableImages=complete&&PROPOSAL_STAGES.every(stage=>acceptedAssets[stage]);
  const step=hasResults?4:question==='ready'?3:question==='start'&&!candidates?1:2;
  const doneStages=PROPOSAL_STAGES.filter(stage=>(session.pending?.assets||{})[stage]).length;
  return <div className={`op-app ox${hasResults?' ox--results':''}`}>
    <a href="#proposal-main" className="op-skip-link" onClick={event=>{event.preventDefault();jumpTo('proposal-main');}}>Skip to your proposal</a>
    <header className="ox-header"><a href={settings.link} aria-label={`${settings.title} home`} className="ox-logo">{settings.logo&&<img src={settings.logo} alt=""/>}<span>{settings.title}<small>异趣伙伴</small></span></a><nav className="ox-nav"><Link to="/showcase">Example worlds</Link>{hasResults&&<a href="#proposal-results" onClick={event=>{event.preventDefault();jumpTo('proposal-results');}}>Your proposal</a>}</nav></header>
    <main id="proposal-main" tabIndex={-1}>
      {!hasResults&&<section className="ox-stage" aria-label="Create your concept">
        <ol className="ox-steps" aria-label="Progress">{['Brand','Confirm','Generate','Concept'].map((label,i)=><li key={label} className={i+1===step?'is-active':i+1<step?'is-done':''} aria-current={i+1===step?'step':undefined}><span>{i+1}</span>{label}</li>)}</ol>
        {step===1&&<div className="ox-hero"><p className="ox-kicker">From IP to “I Want That”</p><h1>Your business DNA.{' '}<br/><em>Made collectible.</em></h1><p className="ox-lede">Type a brand. We research its story, then imagine it as a palm-sized collectible world.</p></div>}
        <div id="proposal-conversation" className="ox-card" tabIndex={-1}>
          {step===1&&<p className="op-sr-only">What’s the business, brand or idea?</p>}
          {question==='start'&&candidates&&candidates.list.length>0&&<div role="group" aria-label="Which brand did you mean?"><h2 className="ox-q">Is this the brand?</h2><p className="ox-sub">Pick the right {candidates.query}. We’ll read its public website next.</p><div className="ox-matches">{candidates.list.map(c=><button key={c.url} type="button" className="ox-match" disabled={locked} onClick={()=>chooseBrand(c)}><div><strong>{c.name}</strong><small>{c.url.replace(/^https:\/\//,'')}</small>{c.description&&<p>{c.description}</p>}</div><ArrowRight size={18} aria-hidden="true"/></button>)}</div><button type="button" className="ox-link" disabled={locked} onClick={()=>chooseBrand(null)}>None of these — I’ll describe it</button></div>}
          {question==='business'&&<><h2 className="ox-q">Is this the story to build from?</h2>{!evidence&&<><p className="ox-sub">{session.website?'We can read the public website, or you can describe the brand below.':'Describe what the brand does in a sentence or two.'}</p>{session.website&&<button className="ox-ghost" disabled={locked} onClick={()=>void readWebsite()}>Read public website</button>}</>}{evidence&&<div className="ox-evidence"><span>From their public website</span><strong>{evidence.title}</strong><p>{evidence.excerpt}</p><button className="ox-primary" disabled={locked} onClick={()=>{const business=evidence.excerpt.slice(0,2000);commit(addTurn({...latest.current,constructionIntent:undefined,context:{...latest.current.context,business}},'user',business));setQuestion('audience');setEvidence(null);}}>Yes, build from this<ArrowRight size={16}/></button></div>}</>}
          {question==='audience'&&<><h2 className="ox-q">Who is it for?</h2><p className="ox-sub">Optional — it helps shape the story.</p><div className="ox-chips">{['Clients & partners','Our team','Fans & community','My own collection'].map(value=><button disabled={locked} key={value} onClick={()=>{commit(addTurn({...latest.current,constructionIntent:undefined,context:{...latest.current.context,audience:value}},'user',value));setQuestion('ready');}}>{value}</button>)}<button className="is-quiet" disabled={locked} onClick={()=>setQuestion('ready')}>Let the story lead</button></div></>}
          {question!=='ready'&&!(question==='start'&&candidates)&&<form className="ox-search" onSubmit={e=>{e.preventDefault();submitEntry();}}><label className="op-sr-only" htmlFor="proposal-entry">{question==='audience'?'Your audience':'Your brand, website or story'}</label><textarea id="proposal-entry" value={entry} onChange={e=>setEntry(e.target.value)} placeholder={question==='start'?'Try “Airbnb”, “A24” or your own brand':question==='audience'?'Or say it in your own words':'Describe what the brand does'} rows={1} disabled={locked} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();submitEntry();}}}/><button aria-label={question==='start'?'Explore my brand':'Continue conversation'} disabled={locked||!entry.trim()}>{question==='start'?<><span>Explore my brand</span><ArrowRight size={17} aria-hidden="true"/></>:<ArrowUp size={19} aria-hidden="true"/>}</button></form>}
          {question==='ready'&&!session.pending&&<div className="ox-generate"><h2 className="ox-q">Ready to imagine it.</h2><p className="ox-sub">One click creates four connected images: brand world, collectible hero, details and packaging. It takes a few minutes and uses credits.</p>{customerIdentityField()}<button className="ox-primary ox-primary--lg" onClick={generate} disabled={locked||ready!==true||!isCustomerIdentity(session.customerIdentity)}><Sparkles size={18}/>Generate my proposal</button>{ready===null&&<p className="ox-fine">Checking the studio…</p>}</div>}
          {session.pending&&!hasResults&&locked&&<div className="ox-progress"><h2 className="ox-q">Imagining your world…</h2><ul>{PROPOSAL_STAGES.map((stage,i)=><li key={stage} className={i<doneStages?'is-done':i===doneStages?'is-active':''}>{stageNames[stage]}</li>)}</ul></div>}
          {step===1&&<p className="ox-fine">Private on this device until you choose to share.</p>}
        </div>
        {!started&&saved&&<button className="ox-resume" onClick={()=>void restore(saved)}>Continue saved proposal<ArrowRight size={15}/></button>}
        {!started&&legacySaved&&<p className="ox-fine"><Link to="/?canvas=legacy">Open an earlier two-image canvas</Link></p>}
      </section>}
      {ready===false&&<div className="ox-notice" role="status">{PROPOSAL_GENERATION_PAUSED?(simple?'New generations are paused for a moment.':PROPOSAL_PAUSE_MESSAGE):'The studio isn’t available right now.'} {PROPOSAL_GENERATION_PAUSED&&!simple&&<><Link to="/?canvas=legacy">Earlier workflow: visual studies only</Link> · </>}{!PROPOSAL_GENERATION_PAUSED&&<><button disabled={locked} onClick={()=>setRetry(n=>n+1)}>Try again</button> · </>}<Link to="/showcase">Explore example worlds →</Link></div>}
      {(busy||status||storageError)&&<div className="ox-status" role="status" aria-live="polite">{busy&&<><LoaderCircle size={16} className="op-spin"/><strong>{busy}</strong></>}{status&&<span>{status}</span>}{storageError&&<span>Device storage is full. Download your brief before leaving.</span>}{locked&&<button onClick={()=>stop()}><X size={14}/>Stop</button>}</div>}
      {hasResults&&<section className="ox-results"><div id="proposal-results" tabIndex={-1} className="ox-toolbar"><div><p className="ox-kicker">{session.pending?(complete?'Updating · previous version shown':'Taking shape'):'Your concept'}</p><h1>{(session.accepted||session.pending)?.customerIdentity?.name||'Your brand'}, made collectible.</h1></div><div><button onClick={download}><Download size={15}/>Download brief</button><button disabled={locked} onClick={event=>{openDialog('share',event.currentTarget);setIncludeImages(false);setShareLink('');setShareStatus('');}}><Share2 size={15}/>Share</button></div></div><ProposalBoard assets={displayAssets} pendingAssets={session.accepted?pendingAssets:undefined} updating={Boolean(session.accepted&&session.pending)} progress={busy} imageErrors={imageErrors} onImageError={src=>setImageErrors(v=>({...v,[src]:true}))} onRetryImage={src=>setImageErrors(v=>({...v,[src]:false}))} onEnlarge={(c,trigger)=>{setEnlarged(c);openDialog('image',trigger);}}/></section>}
      {session.pending&&!locked&&<div className="ox-recovery">{!session.pending.assets.world&&(!session.accepted||!session.accepted.customerIdentity)&&customerIdentityField()}<p>{complete?'Your previous concept is kept safe.':'Finished images are saved.'} Continue to create only what’s missing.</p><button className="ox-primary" disabled={ready!==true||needsCustomerIdentity(session.pending)} onClick={()=>void generatePending(session.pending!)}>Continue proposal</button><button className="ox-link" onClick={()=>{if(latest.current.accepted)setIdentityName(latest.current.accepted.customerIdentity?.name||'');commit({...latest.current,pending:null});setStatus('Unfinished version discarded.');}}>Discard unfinished version</button></div>}
      {complete&&!session.pending&&!packagingRecovery&&<section className="ox-refine" aria-label="Refine your proposal"><h2 className="ox-q">{clarification||'Want to change anything?'}</h2><form className="ox-search" onSubmit={e=>{e.preventDefault();void revise();}}><label className="op-sr-only" htmlFor="proposal-change">Change your proposal</label><textarea id="proposal-change" value={instruction} disabled={locked} onChange={e=>setInstruction(e.target.value)} maxLength={2000} placeholder="e.g. Keep the object, make the packaging deep blue" rows={1}/><button aria-label="Update proposal" disabled={locked||ready!==true||!instruction.trim()}><ArrowUp size={19}/></button></form><p className="ox-fine">Only the affected images are regenerated.</p></section>}
      {complete&&!session.pending&&packagingRecovery&&<section className="ox-refine" aria-label="Confirm packaging-only change"><h2 className="ox-q">Update only the packaging?</h2><p className="ox-sub">Your world, object and details images stay unchanged. This creates one new image.</p><div className="ox-chips"><button className="ox-primary" disabled={locked||ready!==true} onClick={confirmPackagingRecovery}>Update packaging only</button><button disabled={locked} onClick={()=>setPackagingRecovery(null)}>Go back to my change</button></div></section>}
      {!simple&&<details className="op-details"><summary>Edit details</summary>{complete&&!session.pending&&<div>{customerIdentityField(true)}<button className="op-primary" disabled={locked||!isCustomerIdentity({version:CUSTOMER_IDENTITY_VERSION,name:identityName})||identityName===session.accepted?.customerIdentity?.name} onClick={startBrandDirection}>Start new brand direction</button></div>}<div className="op-detail-grid">{([['business','Business story',2000],['audience','Audience',120],['angle','Story direction',200],['brandIdentifiers','Brand identifiers & colours',500],['style','Visual style',200],['exactWording','Exact wording',300],['interaction','Interaction',200]] as const).map(([key,label,max])=><label key={key}>{label}<textarea value={session.context[key]||''} disabled={locked||Boolean(session.pending)||complete} onChange={e=>field(key,e.target.value)} maxLength={max} rows={key==='business'?3:2}/></label>)}<label>Public website<input value={session.website} disabled={locked||Boolean(session.pending)||complete} onChange={e=>commit({...latest.current,constructionIntent:undefined,website:e.target.value})} maxLength={300}/></label></div></details>}
      {hasResults&&<div className="ox-request"><BuildProposalRequest key={location.key} brief={proposalBrief(session,all)} snapshot={proposalExportSnapshot(session,all)} disabled={locked} hasPending={Boolean(session.pending)} /></div>}
      {hasResults&&<div className="ox-tools"><button disabled={locked} onClick={()=>void restore(latest.current)}>Refresh saved images</button></div>}
    </main>
    <footer className="ox-footer"><p className="ox-footer-line">Give People Something To Talk About.</p><h2>Make It LIVE.</h2><div className="ox-footer-bottom"><span>{settings.title} / 异趣伙伴</span><span>{hasResults?'Concept preview. Final design, functionality and pricing confirmed during the build proposal.':'Independent minds. Shared imagination.'}</span></div></footer>
    <Dialog open={Boolean(dialog)} onOpenChange={open=>{if(!open)closeDialog();}}><DialogContent onCloseAutoFocus={event=>{event.preventDefault();restoreDialogFocus();}} className={`op-dialog${dialog==='image'?' op-image-dialog':''}`}><DialogHeader><DialogTitle>{dialog==='share'?'Review what this link shares':dialog==='import'?'Open this shared proposal':enlarged?.title||'Proposal image'}</DialogTitle><DialogDescription>{dialog==='share'?'Anyone with the link can read its content. Text-only is the default.':dialog==='import'?'Opening creates your own editable version on this device. It does not change the sender’s version.':'A generated visual concept. Construction, artwork and function still need review.'}</DialogDescription></DialogHeader>
      {dialog==='image'&&enlarged&&<img src={enlarged.image} alt={`${enlarged.title} full generated image`}/>}
      {dialog==='share'&&<><div className="op-share-review"><strong>Current direction</strong><p>Exact brand name: {session.customerIdentity?.name||session.accepted?.customerIdentity?.name||session.pending?.customerIdentity?.name||'Not supplied'}</p><p>{session.website||'No website'}</p>{Object.entries(session.context).map(([key,value])=><p key={key}><b>{key}:</b> {key==='exactWording'?JSON.stringify(value):value}</p>)}</div><label className="op-share-check"><input type="checkbox" checked={includeImages} disabled={!reviewableImages} onChange={e=>{setIncludeImages(e.target.checked);setShareLink('');}}/>Also share generated image access and the original stored metadata</label>{!reviewableImages&&<p>Restore every completed image’s metadata before enabling image access.</p>}{includeImages&&<><p className="op-warning">Anyone with this link can open these images and their original context, story and design, including details removed from your current direction. The link can be forwarded. Image IDs grant access; signed image URLs are not included.</p>{PROPOSAL_STAGES.map(stage=>{const c=acceptedAssets[stage]!;return <details className="op-metadata" key={stage}><summary>Review original {stageNames[stage]} metadata</summary><pre>{JSON.stringify({...c,image:undefined},null,2)}</pre></details>;})}</>}<button className="op-primary" onClick={()=>void share()}>Create reviewed link</button>{shareLink&&<label>Share link<input aria-label="Share link" value={shareLink} readOnly onFocus={e=>e.target.select()}/></label>}{shareStatus&&<p role="status">{shareStatus}</p>}</>}
      {dialog==='import'&&(shared?<><div className="op-share-review"><p>Exact brand name: {shared.customerIdentity?.name||shared.accepted?.customerIdentity?.name||shared.pending?.customerIdentity?.name||'Not supplied'}</p><p>{shared.website||'No website'}</p><p>{shared.context.business}</p><p>{shared.context.audience}</p><p>{shared.accepted?'Includes access to original generated image metadata':'Text-only direction; no generated image access'}</p></div><p>Download your current brief first if you want to keep a separate backup.</p><button onClick={download}>Download current brief</button><button className="op-primary" onClick={()=>{imported.current={...shared,id:newVersion()};navigate(proposalPath(),{replace:true});}}>Open my editable version</button></>:<p>This shared link is invalid or too long. Your current work has not changed.</p>)}
    </DialogContent></Dialog>
  </div>;
}
