import { act, cleanup, fireEvent, render, screen, waitFor, within } from '@testing-library/react';
import { MemoryRouter, Link, useNavigate } from 'react-router-dom';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import Index from '@/pages/Index';
import { PROPOSAL_SESSION_KEY, decodeProposalShare, emptyProposalSession, encodeProposalShare, loadProposalSession, saveProposalSession, type ProposalSession } from '@/lib/proposal-session';
import { ProposalContextNeededError } from '@/lib/proposal-api';
import type { ProposalConcept, ProposalRequest, ProposalStage } from '@/lib/proposal-api';
const mocks=vi.hoisted(()=>({generate:vi.fn(),restore:vi.fn(),plan:vi.fn(),ready:vi.fn(),website:vi.fn()}));
vi.mock('@/lib/proposal-api',async original=>({...await original<object>(),requestProposalAsset:mocks.generate,restoreProposalAsset:mocks.restore,planProposalRevision:mocks.plan,supportsProposalGeneration:mocks.ready}));
vi.mock('@/lib/concept-api',()=>({requestConcept:mocks.website}));
vi.mock('@/integrations/supabase/client',()=>({supabase:{from:()=>({select:async()=>({data:[{key:'site_title',value:'OFFKIN'}]})})}}));
const ids:Record<ProposalStage,string>={world:'00000000-0000-4000-8000-000000000001',physical:'00000000-0000-4000-8000-000000000002',details:'00000000-0000-4000-8000-000000000003',packaging:'00000000-0000-4000-8000-000000000004'};
const elements=[{id:'house',label:'Paper house',description:'A proposed paper neighbourhood.',kind:'proposal' as const},{id:'path',label:'Ribbon path',description:'A proposed connecting path.',kind:'proposal' as const}];
function fixture(body:ProposalRequest,overrides:Partial<ProposalConcept>={}):ProposalConcept{const {previousAssetId:_previous,...publicBody}=body;return {...publicBody,stageVersion:'proposal-assets-v1',id:ids[body.stage],brand:'Paper Studio',title:`Paper ${body.stage}`,story:`A new ${body.stage} made for this customer.`,design:'Rich connected paper design.',interaction:'Turn to reveal another story.',image:`https://images.example/${body.stage}.png`,sourceUrl:'',sourceTitle:'',worldElements:elements,sourceImageIds:[...(body.stage==='physical'?[body.sourceWorldId!]:body.stage==='details'?[body.sourcePhysicalId!]:body.stage==='packaging'?[body.sourcePhysicalId!,body.sourceWorldId!]:[])],...(body.stage==='details'||body.stage==='packaging'?{selectedElementIds:['house','path'],heroElementId:'house',replacements:[]}:{}),...overrides};}
function saved():ProposalSession{const s=emptyProposalSession();s.context.business='We create personalised paper gifts';s.accepted={id:'accepted',context:s.context,website:'',assets:{...ids},selected:['house','path'],hero:'house',replacements:[]};return s;}
function deferred<T>(){let resolve!:(v:T)=>void;const promise=new Promise<T>(done=>{resolve=done;});return {resolve,promise};}
function Navigation(){const navigate=useNavigate();return <nav><Link to="/?next=1">Newer route</Link><button onClick={()=>navigate(-1)}>Back</button></nav>;}
function mount(path='/?proposal=1',nav=false){return render(<MemoryRouter initialEntries={[path]}>{nav&&<Navigation/>}<Index/></MemoryRouter>);}
async function introduction(){fireEvent.change(screen.getByLabelText('Your brand, website or story'),{target:{value:'We create personalised paper gifts'}});fireEvent.click(screen.getByRole('button',{name:'Continue conversation'}));fireEvent.click(screen.getByRole('button',{name:'Clients & partners'}));await waitFor(()=>expect(screen.getByRole('button',{name:'Generate my proposal'})).toBeEnabled());}
async function complete(){await introduction();fireEvent.click(screen.getByRole('button',{name:'Generate my proposal'}));await screen.findByRole('heading',{name:'Paper packaging'});await waitFor(()=>expect(screen.getByRole('button',{name:'Update proposal'})).toBeInTheDocument());}
beforeEach(()=>{localStorage.clear();vi.clearAllMocks();mocks.ready.mockResolvedValue(true);mocks.generate.mockImplementation(async(body:ProposalRequest)=>fixture(body));mocks.restore.mockImplementation(async(id:string)=>{const stage=Object.keys(ids).find(stage=>ids[stage]===id) as ProposalStage;const s=saved();return fixture({contractVersion:'offkin-proposal-v10',stage,brand:'no-website',context:s.context,...(stage!=='world'?{sourceWorldId:ids.world,selectedElementIds:['house','path'],heroElementId:'house',replacements:[]}:{}),...(['details','packaging'].includes(stage)?{sourcePhysicalId:ids.physical}:{})});});mocks.plan.mockImplementation(async body=>({plan:{scope:'packaging',context:{...body.context,revisionNotes:'Packaging deep blue; object unchanged'},summary:'Keep your world and object. Make only the packaging deep blue.'}}));});
afterEach(async()=>{await act(async()=>{});cleanup();vi.useRealTimers();vi.restoreAllMocks();});
describe('Complete proposal journey',()=>{
  it('starts empty and keeps reference brands out of customer state',async()=>{mount();await waitFor(()=>expect(mocks.ready).toHaveBeenCalled());expect(screen.getByRole('heading',{level:1})).toHaveTextContent('Your business DNA. Made collectible.');expect(screen.queryByRole('img')).not.toBeInTheDocument();expect(screen.queryByText(/Airbnb|Tesla|A24/)).not.toBeInTheDocument();expect(localStorage.getItem(PROPOSAL_SESSION_KEY)).toBeNull();expect(mocks.generate).not.toHaveBeenCalled();});
  it('generates all four genuine roles from one explicit action with actual saved lineage',async()=>{mount();await complete();expect(mocks.generate.mock.calls.map(([b])=>b.stage)).toEqual(['world','physical','details','packaging']);const bodies=mocks.generate.mock.calls.map(([b])=>b);expect(bodies[1]).toMatchObject({sourceWorldId:ids.world,selectedElementIds:['house','path'],heroElementId:'house'});expect(bodies[2]).toMatchObject({sourceWorldId:ids.world,sourcePhysicalId:ids.physical});expect(bodies[3]).toMatchObject({sourceWorldId:ids.world,sourcePhysicalId:ids.physical});expect(screen.getAllByRole('img')).toHaveLength(4);expect(loadProposalSession()?.accepted?.assets).toEqual(ids);expect(loadProposalSession()?.pending).toBeNull();});
  it('does not generate on typing, IME composition or audience selection',async()=>{mount();const input=screen.getByLabelText('Your brand, website or story');fireEvent.change(input,{target:{value:'纸世界 Café 🪁'}});fireEvent.keyDown(input,{key:'Enter',isComposing:true});expect(screen.getByText('What’s the business, brand or idea?')).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Continue conversation'}));fireEvent.click(screen.getByRole('button',{name:'Let the story lead'}));expect(mocks.generate).not.toHaveBeenCalled();expect(loadProposalSession()?.context.business).toBe('纸世界 Café 🪁');});
  it('reads a URL only on the explicit website action',async()=>{mocks.website.mockResolvedValue({website:{url:'https://paper.example/',title:'Paper',excerpt:'We fold meaningful paper gifts.'}});mount();fireEvent.change(screen.getByLabelText('Your brand, website or story'),{target:{value:'https://paper.example'}});fireEvent.click(screen.getByRole('button',{name:'Continue conversation'}));expect(mocks.website).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Read public website'}));await screen.findByText('We fold meaningful paper gifts.');expect(mocks.generate).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Use this business description'}));expect(loadProposalSession()?.context.business).toBe('We fold meaningful paper gifts.');});
  it('prevents duplicate generation clicks',async()=>{const gate=deferred<ProposalConcept>();mocks.generate.mockImplementationOnce(()=>gate.promise);mount();await introduction();const button=screen.getByRole('button',{name:'Generate my proposal'});fireEvent.click(button);fireEvent.click(button);expect(mocks.generate).toHaveBeenCalledOnce();await act(async()=>{gate.resolve(fixture(mocks.generate.mock.calls[0][0]));});await screen.findByRole('heading',{name:'Paper packaging'});expect(mocks.generate).toHaveBeenCalledTimes(4);});
  it('saves the first three sections and resumes only failed packaging',async()=>{let failed=false;mocks.generate.mockImplementation(async(body:ProposalRequest)=>{if(body.stage==='packaging'&&!failed){failed=true;throw new Error('Gateway paused');}return fixture(body);});mount();await introduction();fireEvent.click(screen.getByRole('button',{name:'Generate my proposal'}));await screen.findByText('Gateway paused');expect(loadProposalSession()?.pending?.assets).toEqual({world:ids.world,physical:ids.physical,details:ids.details});fireEvent.click(screen.getByRole('button',{name:'Continue proposal'}));await screen.findByRole('heading',{name:'Paper packaging'});expect(mocks.generate.mock.calls.map(([b])=>b.stage)).toEqual(['world','physical','details','packaging','packaging']);});
  it('ignores cancelled late output and never advances to another paid stage',async()=>{const gate=deferred<ProposalConcept>();mocks.generate.mockImplementationOnce(()=>gate.promise);mount();await introduction();fireEvent.click(screen.getByRole('button',{name:'Generate my proposal'}));const signal=mocks.generate.mock.calls[0][1];fireEvent.click(screen.getByRole('button',{name:'Stop'}));expect(signal.aborted).toBe(true);await act(async()=>{gate.resolve(fixture(mocks.generate.mock.calls[0][0]));});expect(mocks.generate).toHaveBeenCalledOnce();expect(loadProposalSession()?.pending?.assets).toEqual({});expect(screen.queryByRole('img')).not.toBeInTheDocument();});
  it('cancels on newer navigation and ignores the stale response',async()=>{const gate=deferred<ProposalConcept>();mocks.generate.mockImplementationOnce(()=>gate.promise);mount('/?proposal=1',true);await introduction();fireEvent.click(screen.getByRole('button',{name:'Generate my proposal'}));const signal=mocks.generate.mock.calls[0][1];fireEvent.click(screen.getByRole('link',{name:'Newer route'}));expect(signal.aborted).toBe(true);await act(async()=>{gate.resolve(fixture(mocks.generate.mock.calls[0][0]));});expect(mocks.generate).toHaveBeenCalledOnce();expect(loadProposalSession()?.pending?.assets).toEqual({});});
  it('actually generates packaging revision while preserving accepted world, hero and details IDs',async()=>{mount();await complete();const replacement='00000000-0000-4000-8000-000000000014';mocks.generate.mockImplementation(async(body:ProposalRequest)=>fixture(body,{id:replacement,image:'https://images.example/blue-packaging.png'}));fireEvent.change(screen.getByLabelText('Change your proposal'),{target:{value:'Keep the object. Make the packaging deep blue.'}});fireEvent.click(screen.getByRole('button',{name:'Update proposal'}));await waitFor(()=>expect(loadProposalSession()?.accepted?.assets.packaging).toBe(replacement));expect(mocks.plan).toHaveBeenCalledOnce();expect(mocks.generate).toHaveBeenCalledTimes(5);expect(mocks.generate.mock.calls[4][0]).toMatchObject({stage:'packaging',previousAssetId:ids.packaging,sourceWorldId:ids.world,sourcePhysicalId:ids.physical});expect(loadProposalSession()?.accepted?.assets).toEqual({...ids,packaging:replacement});});
  it('retains accepted images throughout a partial revision and swaps only when complete',async()=>{mount();await complete();const gate=deferred<ProposalConcept>();mocks.plan.mockImplementation(async body=>({plan:{scope:'physical',context:{...body.context,revisionNotes:'Make the object a cafe'},summary:'Revise the object and dependent sections.'}}));mocks.generate.mockImplementation((body:ProposalRequest)=>body.stage==='packaging'?gate.promise:Promise.resolve(fixture(body,{id:ids[body.stage].replace('00000000000','00000000001'),image:`https://images.example/new-${body.stage}.png`})));
    fireEvent.change(screen.getByLabelText('Change your proposal'),{target:{value:'Make the object a cafe'}});fireEvent.click(screen.getByRole('button',{name:'Update proposal'}));await waitFor(()=>expect(mocks.generate).toHaveBeenCalledTimes(7));expect(screen.getAllByRole('img').map(i=>i.getAttribute('src'))).toContain('https://images.example/physical.png');expect(screen.queryByRole('img',{name:/new-physical/})).not.toBeInTheDocument();const body=mocks.generate.mock.calls[6][0];await act(async()=>{gate.resolve(fixture(body,{id:'00000000-0000-4000-8000-000000000014',image:'https://images.example/new-packaging.png'}));});await waitFor(()=>expect(loadProposalSession()?.pending).toBeNull());expect(screen.getAllByRole('img').map(i=>i.getAttribute('src'))).toContain('https://images.example/new-physical.png');});
  it('applies validated component replacements to the generated physical request',async()=>{mount();await complete();mocks.plan.mockImplementation(async body=>({plan:{scope:'physical',context:{...body.context,revisionNotes:'Replace house with a cafe'},summary:'Replace the house with a cafe.',selectedElementIds:['house','path'],heroElementId:'house',replacements:[{id:'house',label:'Paper cafe',description:'A welcoming cafe replaces the house.'}]}}));mocks.generate.mockImplementation(async(body:ProposalRequest)=>fixture(body,{id:ids[body.stage].replace('00000000000','00000000001')}));fireEvent.change(screen.getByLabelText('Change your proposal'),{target:{value:'Replace the house with a cafe'}});fireEvent.click(screen.getByRole('button',{name:'Update proposal'}));await waitFor(()=>expect(mocks.generate).toHaveBeenCalledTimes(7));expect(mocks.generate.mock.calls[4][0]).toMatchObject({stage:'physical',selectedElementIds:['house','path'],replacements:[{id:'house',label:'Paper cafe',description:'A welcoming cafe replaces the house.'}]});expect(loadProposalSession()?.accepted?.assets.world).toBe(ids.world);});
  it('reopens one business question when the generator needs facts before any image exists',async()=>{mocks.generate.mockRejectedValueOnce(new ProposalContextNeededError('Tell us what the business does.'));mount();await introduction();fireEvent.click(screen.getByRole('button',{name:'Generate my proposal'}));await screen.findByText('Tell us what the business does.');expect(screen.getByText('What should this world say about your business?')).toBeInTheDocument();expect(screen.getByLabelText('Your brand, website or story')).toBeEnabled();expect(loadProposalSession()?.pending).toBeNull();expect(mocks.generate).toHaveBeenCalledOnce();});
  it('asks a single clarification and does not generate an ambiguous change',async()=>{mount();await complete();mocks.plan.mockResolvedValue({clarification:'Do you mean the box or the object?'});fireEvent.change(screen.getByLabelText('Change your proposal'),{target:{value:'Make it blue'}});fireEvent.click(screen.getByRole('button',{name:'Update proposal'}));await screen.findAllByText('Do you mean the box or the object?');expect(mocks.generate).toHaveBeenCalledTimes(4);expect(loadProposalSession()?.accepted?.assets).toEqual(ids);});
  it('restores saved images without generation even when generation is unavailable',async()=>{saveProposalSession(saved());mocks.ready.mockResolvedValue(false);mount();fireEvent.click(screen.getByRole('button',{name:'Continue saved proposal'}));await screen.findByRole('heading',{name:'Paper packaging'});expect(mocks.restore).toHaveBeenCalledTimes(4);expect(mocks.generate).not.toHaveBeenCalled();expect(screen.getAllByRole('img')).toHaveLength(4);});
  it('defaults sharing to text-only and requires separate original-metadata opt-in',async()=>{mount();await complete();fireEvent.click(screen.getByRole('button',{name:'Share'}));const d=within(screen.getByRole('dialog'));expect(d.getByRole('checkbox')).not.toBeChecked();fireEvent.click(d.getByRole('button',{name:'Create reviewed link'}));const link=d.getByRole('textbox',{name:'Share link'}) as HTMLInputElement;expect(decodeProposalShare(new URL(link.value).hash)?.accepted).toBeNull();fireEvent.click(d.getByRole('checkbox'));expect(d.getByText(/including details removed/)).toBeInTheDocument();expect(d.getAllByText(/Review original/)).toHaveLength(4);fireEvent.click(d.getByRole('button',{name:'Create reviewed link'}));const imageLink=d.getByRole('textbox',{name:'Share link'}) as HTMLInputElement;expect(decodeProposalShare(new URL(imageLink.value).hash)?.accepted?.assets).toEqual(ids);expect(imageLink.value).not.toContain('images.example');});
  it('imports reviewed text as an independent branch without generating',async()=>{const s=emptyProposalSession();s.context.business='A shared personal paper story';const hash=encodeProposalShare(s);mount('/'+hash);expect(screen.getByRole('dialog')).toBeInTheDocument();expect(loadProposalSession()).toBeNull();fireEvent.click(screen.getByRole('button',{name:'Open my editable version'}));await waitFor(()=>expect(screen.queryByRole('dialog')).not.toBeInTheDocument());expect(loadProposalSession()?.context.business).toBe(s.context.business);expect(loadProposalSession()?.id).not.toBe(s.id);expect(mocks.generate).not.toHaveBeenCalled();});
  it('switches the ordinary public root only when the full capability is ready',async()=>{mount('/');await screen.findByLabelText('Your brand, website or story');expect(screen.queryByRole('button',{name:'Generate my brand world'})).not.toBeInTheDocument();});
  it('keeps the earlier working root with a truthful notice until backend verification',async()=>{mocks.ready.mockResolvedValue(false);mount('/');await screen.findByText(/This earlier canvas creates world and physical studies only/);expect(screen.getByRole('button',{name:'Generate my brand world'})).toBeInTheDocument();expect(screen.getByRole('link',{name:'Open a saved complete proposal'})).toHaveAttribute('href','/?proposal=1');});
  it('bounds a hung root capability check and ignores its late reply',async()=>{vi.useFakeTimers();const gate=deferred<boolean>();mocks.ready.mockImplementationOnce(()=>gate.promise);mount('/');expect(screen.getByText('Opening your creative studio…')).toBeInTheDocument();await act(async()=>{vi.advanceTimersByTime(6000);});expect(screen.getByText(/This earlier canvas creates world and physical studies only/)).toBeInTheDocument();await act(async()=>{gate.resolve(true);});expect(screen.getByRole('button',{name:'Generate my brand world'})).toBeInTheDocument();});
  it('imports a reviewed proposal even when generation readiness is disabled',async()=>{mocks.ready.mockResolvedValue(false);const s=emptyProposalSession();s.context.business='Offline shared direction';mount('/'+encodeProposalShare(s));fireEvent.click(screen.getByRole('button',{name:'Open my editable version'}));await waitFor(()=>expect(loadProposalSession()?.context.business).toBe('Offline shared direction'));expect(screen.queryByRole('dialog')).not.toBeInTheDocument();expect(screen.queryByText(/This earlier canvas creates/)).not.toBeInTheDocument();expect(mocks.generate).not.toHaveBeenCalled();});
  it('keeps the v9 canvas route available separately',()=>{mount('/?canvas=legacy');expect(screen.getByRole('button',{name:'Generate my brand world'})).toBeInTheDocument();expect(screen.queryByRole('button',{name:'Generate my proposal'})).not.toBeInTheDocument();});
});
