import { CanvasFailure } from './canvas.ts';
import { readCompanyWebsite, validatePublicWebsiteUrl, WebsiteReadError } from './website.ts';
import { PAIRED_CONTRACT_VERSION, PAIRED_ROLES, STORY_LENSES, buildPairedArtifacts, freezePairedDesign, parsePairedStoredManifest, restorePairedRow, serializePairedStoredManifest, validatePairedDesign, verifyFrozenDesign, type FrozenPairedDesign, type PairedDesignInput, type PairedRole } from './paired-design.ts';

type Row={id:string;cache_key?:string;brand:string;title:string;story:string;image_path:string;prompt_version:string;interaction?:string;source_url?:string;source_title?:string;edition?:'inside';format?:'miniature'};
type Result<T>={data?:T;error?:unknown};
type BlobLike={size:number;arrayBuffer():Promise<ArrayBuffer>};
export type PairedRuntime={enabled:boolean;textModel:string;imageModel:string;hash(value:string):Promise<string>;reserve():Promise<void>;ai(path:string,body:unknown):Promise<unknown>;respond(data:unknown,status?:number):Response;deliver(row:Row):Promise<Response>;db:{from(name:string):{select(fields:string):{eq(field:string,value:unknown):{maybeSingle():PromiseLike<Result<Row|null>>}};insert(row:Row):PromiseLike<{error?:unknown}>};storage:{from(name:string):{download(path:string):PromiseLike<Result<BlobLike>>;upload(path:string,bytes:Uint8Array,options:{contentType:string;upsert:boolean}):PromiseLike<{error?:unknown}>;remove(paths:string[]):PromiseLike<unknown>}}}};
const columns='id,cache_key,brand,title,story,image_path,interaction,source_url,source_title,prompt_version';
const record=(v:unknown):v is Record<string,unknown>=>Boolean(v&&typeof v==='object'&&!Array.isArray(v));
const uuid=(v:unknown):v is string=>typeof v==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(v);
const text=(v:unknown,max:number):v is string=>typeof v==='string'&&Boolean(v.trim())&&v.length<=max;
function imageResult(result:unknown){const data=record(result)&&Array.isArray(result.data)?result.data:null;const b64=data?.length===1&&record(data[0])?data[0].b64_json:null;if(typeof b64!=='string'||b64.length>14000000||!/^[A-Za-z0-9+/]*={0,2}$/.test(b64))throw new CanvasFailure(502,'The image provider returned no supported image.');let bytes:Uint8Array;try{bytes=Uint8Array.from(atob(b64),c=>c.charCodeAt(0));}catch{throw new CanvasFailure(502,'The image provider returned an invalid image.');}const mime=bytes.length>=12&&bytes[0]===137&&bytes[1]===80?'image/png':bytes[0]===255&&bytes[1]===216?'image/jpeg':String.fromCharCode(...bytes.slice(0,4))==='RIFF'?'image/webp':null;if(!mime||bytes.length>10*1024*1024)throw new CanvasFailure(502,'The image is unsupported or too large to save.');return{bytes,mime};}
function plannerResult(result:unknown):unknown{try{if(!record(result)||!Array.isArray(result.choices)||!record(result.choices[0])||!record(result.choices[0].message)||typeof result.choices[0].message.content!=='string')throw new Error();return JSON.parse(result.choices[0].message.content);}catch{throw new CanvasFailure(502,'The paired design plan was incomplete. No image was generated.');}}
const planPrompt=`Return JSON only. Create one OFFKIN paired concept from the supplied confirmed public evidence and chosen lens. Never invent a brand fact. Output exactly: {"truth":{"quote":string},"symbolism":string,"plan":{"status":"unverified-concept","object":string,"silhouette":string,"components":[{"id":lowercase-kebab,"name":string,"form":string,"role":"body|moving|support|symbol"}],"purchasedParts":[{"id":lowercase-kebab,"name":string,"purpose":string}],"mechanic":null|{"kind":"press|slide|turn","inputPartId":string,"outputPartId":string,"purchasedPartIds":[string],"effect":string},"process":"undecided|FDM|resin","caveats":[string]},"card":{"headline":string,"narrative":string,"frames":2|3},"localizedBrandAccents":[string]}. The quote must be verbatim from evidence. Use one distinctive palm-sized silhouette, 3-5 major printed components as an editorial target, zero or one meaningful mechanic, explicit caveats, and one causal narrative sentence containing the quote, exact object name and because/so/therefore. No generic shoebox, cluttered diorama, logo plaque, pasted-on logo, random props, working machinery, CAD or production claims. OFFKIN style is warm ivory, black ink, muted coral and a tiny yellow accent.`;
export async function handlePaired(input:unknown,req:Request,runtime:PairedRuntime):Promise<Response>{
 const active=()=>{if(req.signal.aborted)throw new CanvasFailure(499,'The request was cancelled.');};
 if(!runtime.enabled)throw new CanvasFailure(503,'Linked pair generation is not enabled yet. No AI request was sent.');
 if(!record(input)||input.contractVersion!==PAIRED_CONTRACT_VERSION||!['plan','render'].includes(String(input.action)))throw new CanvasFailure(400,'Use a supported linked-pair request.');
 if(input.action==='plan'){
  if(!text(input.brand,120)||!text(input.website,300)||!STORY_LENSES.includes(input.lens as never)||typeof input.exactText!=='string'||input.exactText.length>300||!record(input.context)||typeof input.context.business!=='string'||input.context.business.length>2000)throw new CanvasFailure(400,'Confirm a brand, public website, story lens and bounded direction.');
  let websiteUrl='';try{websiteUrl=validatePublicWebsiteUrl(input.website.trim()).href;}catch(error){throw new CanvasFailure(400,error instanceof Error?error.message:'Enter a public website.');}
  let website;try{website=await readCompanyWebsite(websiteUrl);}catch(error){if(error instanceof WebsiteReadError)throw new CanvasFailure(error.status,error.message);throw new CanvasFailure(422,'The public website could not be read. Use a verified public source or owner statement.');}
  active();await runtime.reserve();active();
  const result=await runtime.ai('chat/completions',{model:runtime.textModel,messages:[{role:'system',content:planPrompt},{role:'user',content:JSON.stringify({brand:input.brand,lens:input.lens,exactText:input.exactText,context:input.context,evidence:website})}],response_format:{type:'json_object'},max_tokens:5000});active();
  const planned=plannerResult(result);if(!record(planned))throw new CanvasFailure(502,'The paired design plan was incomplete. No image was generated.');
  const evidence={id:'public-source',kind:'public-source' as const,text:website.excerpt,sourceUrl:website.url,sourceTitle:website.title};
  const plannedTruth=record(planned.truth)&&typeof planned.truth.quote==='string'?{evidenceId:evidence.id,quote:planned.truth.quote}:planned.truth;
  const design:PairedDesignInput={brand:input.brand,exactText:input.exactText,evidence:[evidence],evidenceConfirmed:true,lens:input.lens as PairedDesignInput['lens'],truth:plannedTruth as PairedDesignInput['truth'],symbolism:planned.symbolism as string,plan:planned.plan as PairedDesignInput['plan'],card:planned.card as PairedDesignInput['card'],localizedBrandAccents:planned.localizedBrandAccents as string[]};
  const issues=validatePairedDesign(design);if(issues.length)return runtime.respond({issues,message:issues.map(issue=>issue.message).join(' ')},422);
  const manifest=await freezePairedDesign(design);return runtime.respond({manifest,evidence:website});
 }
 if(!record(input.manifest)||!await verifyFrozenDesign(input.manifest as FrozenPairedDesign)||!PAIRED_ROLES.includes(input.role as PairedRole))throw new CanvasFailure(400,'Restore a valid locked paired design and choose its next artifact.');
 const manifest=input.manifest as FrozenPairedDesign;const role=input.role as PairedRole;const artifacts=await buildPairedArtifacts(manifest);const artifact=artifacts.find(item=>item.role===role);if(!artifact)throw new CanvasFailure(400,'Choose a supported paired artifact.');
 let source:Row|null=null;let sourceBytes:Uint8Array|null=null;let sourceMime='';
 if(role==='story-card'){
  if(!uuid(input.sourceCollectibleId))throw new CanvasFailure(400,'Generate and save the matching collectible first.');
  const loaded=await runtime.db.from('brick_concepts').select(columns).eq('id',input.sourceCollectibleId).maybeSingle();source=loaded.data||null;if(loaded.error||!source)throw new CanvasFailure(404,'The matching collectible could not be found.');
  const stored=source.prompt_version===PAIRED_CONTRACT_VERSION?await parsePairedStoredManifest(source.story):null;if(!stored||stored.role!=='collectible'||stored.manifest.manifestId!==manifest.manifestId||stored.specDigest!==artifact.specDigest)throw new CanvasFailure(400,'The collectible belongs to a different locked design.');
  const downloaded=await runtime.db.storage.from('brick-concepts').download(source.image_path);if(downloaded.error||!downloaded.data||downloaded.data.size>10*1024*1024)throw new CanvasFailure(503,'The saved collectible is unavailable. No image generation was started.');sourceBytes=new Uint8Array(await downloaded.data.arrayBuffer());sourceMime=source.image_path.endsWith('.png')?'image/png':source.image_path.endsWith('.jpeg')?'image/jpeg':'image/webp';
 }
 const cacheKey=await runtime.hash(JSON.stringify([PAIRED_CONTRACT_VERSION,manifest.manifestId,role,artifact.specDigest,source?source.id:null,runtime.textModel,runtime.imageModel]));
 const cached=await runtime.db.from('brick_concepts').select(columns).eq('cache_key',cacheKey).maybeSingle();if(cached.error)throw new CanvasFailure(503,'Paired concept storage is temporarily unavailable.');if(cached.data)return runtime.deliver(cached.data);
 active();await runtime.reserve();active();
 let body:Record<string,unknown>|FormData={model:runtime.imageModel,prompt:artifact.prompt,n:1,size:'1536x1024',quality:'medium'};let path='images/generations';
 if(sourceBytes){const form=new FormData();for(const [key,value] of Object.entries(body))form.append(key,String(value));form.append('image[]',new Blob([sourceBytes],{type:sourceMime}),'approved-collectible.'+sourceMime.split('/')[1]);body=form;path='images/edits';}
 const generated=await runtime.ai(path,body);active();const{bytes,mime}=imageResult(generated);const id=crypto.randomUUID();const imagePath=`${id}.${mime.split('/')[1]}`;const upload=await runtime.db.storage.from('brick-concepts').upload(imagePath,bytes,{contentType:mime,upsert:false});if(upload.error)throw new CanvasFailure(503,'The paired concept image could not be saved.');
 if(req.signal.aborted){await runtime.db.storage.from('brick-concepts').remove([imagePath]);active();}
 const serialized=await serializePairedStoredManifest({contractVersion:PAIRED_CONTRACT_VERSION,assetVersion:'offkin-paired-assets-v1',role,manifest,specDigest:artifact.specDigest,sourceCollectibleId:source?.id||null});
 const row:Row={id,cache_key:cacheKey,brand:manifest.brand,title:role==='collectible'?manifest.plan.object:manifest.card.headline,story:serialized,image_path:imagePath,prompt_version:PAIRED_CONTRACT_VERSION,edition:'inside',format:'miniature',interaction:manifest.plan.mechanic?.effect||'Display only',source_url:manifest.evidence[0]?.sourceUrl||'',source_title:manifest.evidence[0]?.sourceTitle||''};
 const saved=await runtime.db.from('brick_concepts').insert(row);if(saved.error){await runtime.db.storage.from('brick-concepts').remove([imagePath]);const existing=await runtime.db.from('brick_concepts').select(columns).eq('cache_key',cacheKey).maybeSingle();if(existing.data)return runtime.deliver(existing.data);throw new CanvasFailure(503,'The paired concept image could not be saved.');}return runtime.deliver(row);
}